# Generated by Django 4.2.6 on 2023-11-07 14:25

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("location", "0002_countryname"),
        ("journal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="contact_address",
            field=models.TextField(blank=True, null=True, verbose_name="Address"),
        ),
        migrations.AddField(
            model_name="journal",
            name="contact_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="location.location",
            ),
        ),
        migrations.AddField(
            model_name="journal",
            name="contact_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="journal",
            name="medline_short_title",
            field=models.TextField(blank=True, null=True, verbose_name="Medline Title"),
        ),
        migrations.CreateModel(
            name="JournalEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "journal",
                    modelcluster.fields.ParentalKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="journal_email",
                        to="journal.journal",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
