# Generated by Django 4.1.10 on 2023-08-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="scielojournal",
            new_name="journal_sci_collect_aa562a_idx",
            old_fields=("collection", "journal_acron"),
        ),
        migrations.RenameIndex(
            model_name="scielojournal",
            new_name="journal_sci_collect_89a5d2_idx",
            old_fields=("collection", "issn_scielo"),
        ),
        migrations.AddIndex(
            model_name="journal",
            index=models.Index(fields=["title"], name="journal_jou_title_4d0afb_idx"),
        ),
        migrations.AddIndex(
            model_name="journal",
            index=models.Index(
                fields=["short_title"], name="journal_jou_short_t_37385e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journal",
            index=models.Index(
                fields=["submission_online_url"], name="journal_jou_submiss_f1e7c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journal",
            index=models.Index(
                fields=["open_access"], name="journal_jou_open_ac_0eb1e2_idx"
            ),
        ),
    ]
