# Generated by Django 4.1.10 on 2023-09-18 02:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0002_remove_journal_name_remove_journal_url_and_more"),
        (
            "journal",
            "0002_rename_scielojournal_collection_journal_acron_journal_sci_collect_aa562a_idx_and_more",
        ),
    ]

    operations = []
