# Generated by Django 4.2.7 on 2023-12-20 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reference", "0001_initial"),
        ("core", "0002_licensestatement_and_more"),
        ("journal", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journal",
            name="abstract_language",
            field=models.ManyToManyField(
                blank=True,
                related_name="abstract_language",
                to="core.language",
                verbose_name="Abstract Languages",
            ),
        ),
        migrations.AlterField(
            model_name="journal",
            name="additional_indexed_at",
            field=models.ManyToManyField(
                blank=True,
                to="journal.additionalindexedat",
                verbose_name="Additional Index At",
            ),
        ),
        migrations.AlterField(
            model_name="journal",
            name="indexed_at",
            field=models.ManyToManyField(
                blank=True, to="journal.indexedat", verbose_name="Indexed At"
            ),
        ),
        migrations.AlterField(
            model_name="journal",
            name="other_titles",
            field=models.ManyToManyField(
                blank=True, to="reference.journaltitle", verbose_name="Other titles"
            ),
        ),
        migrations.AlterField(
            model_name="journal",
            name="subject",
            field=models.ManyToManyField(
                blank=True, to="journal.subject", verbose_name="Study Areas"
            ),
        ),
        migrations.AlterField(
            model_name="journal",
            name="subject_descriptor",
            field=models.ManyToManyField(
                blank=True,
                to="journal.subjectdescriptor",
                verbose_name="Subject Descriptors",
            ),
        ),
        migrations.AlterField(
            model_name="journal",
            name="text_language",
            field=models.ManyToManyField(
                blank=True,
                related_name="text_language",
                to="core.language",
                verbose_name="Text Languages",
            ),
        ),
        migrations.AlterField(
            model_name="journal",
            name="wos_area",
            field=models.ManyToManyField(
                blank=True,
                to="journal.webofknowledgesubjectcategory",
                verbose_name="Web of Knowledge Subject Categories",
            ),
        ),
        migrations.AlterField(
            model_name="journal",
            name="wos_db",
            field=models.ManyToManyField(
                blank=True,
                to="journal.webofknowledge",
                verbose_name="Web of Knowledge Databases",
            ),
        ),
        migrations.AlterField(
            model_name="officialjournal",
            name="old_title",
            field=models.ManyToManyField(blank=True, to="journal.officialjournal"),
        ),
        migrations.AlterField(
            model_name="officialjournal",
            name="parallel_titles",
            field=models.ManyToManyField(
                blank=True, to="journal.journalparalleltitles"
            ),
        ),
    ]
