# Generated by Django 4.1.10 on 2023-08-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reference", "0001_initial"),
        ("journal", "0002_remove_journal_name_remove_journal_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="other_title",
            field=models.ManyToManyField(
                to="reference.journalreference", verbose_name="Other titles"
            ),
        ),
    ]
