# Generated by Django 4.2.6 on 2023-11-15 13:36

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0002_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="journalhistory",
            name="journal_jou_occurre_d59679_idx",
        ),
        migrations.RemoveField(
            model_name="journalhistory",
            name="final_day",
        ),
        migrations.RemoveField(
            model_name="journalhistory",
            name="final_month",
        ),
        migrations.RemoveField(
            model_name="journalhistory",
            name="final_year",
        ),
        migrations.RemoveField(
            model_name="journalhistory",
            name="initial_day",
        ),
        migrations.RemoveField(
            model_name="journalhistory",
            name="initial_month",
        ),
        migrations.RemoveField(
            model_name="journalhistory",
            name="initial_year",
        ),
        migrations.RemoveField(
            model_name="journalhistory",
            name="occurrence_type",
        ),
        migrations.RemoveField(
            model_name="scielojournal",
            name="journal_history",
        ),
        migrations.AddField(
            model_name="journalhistory",
            name="day",
            field=models.CharField(
                blank=True, max_length=2, null=True, verbose_name="Event day"
            ),
        ),
        migrations.AddField(
            model_name="journalhistory",
            name="event_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ADMITTED", "Admitted to the collection"),
                    ("INTERRUPTED", "Indexing interrupted"),
                ],
                max_length=16,
                null=True,
                verbose_name="Event type",
            ),
        ),
        migrations.AddField(
            model_name="journalhistory",
            name="interruption_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ceased", "Ceased journal"),
                    ("not-open-access", "Not open access"),
                    ("by-committee", "by the committee"),
                    ("by-editor", "by the editor"),
                ],
                max_length=16,
                null=True,
                verbose_name="Indexing interruption reason",
            ),
        ),
        migrations.AddField(
            model_name="journalhistory",
            name="month",
            field=models.CharField(
                blank=True,
                choices=[
                    ("01", "January"),
                    ("02", "February"),
                    ("03", "March"),
                    ("04", "April"),
                    ("05", "May"),
                    ("06", "June"),
                    ("07", "July"),
                    ("08", "August"),
                    ("09", "September"),
                    ("10", "October"),
                    ("11", "November"),
                    ("12", "December"),
                ],
                max_length=2,
                null=True,
                verbose_name="Event month",
            ),
        ),
        migrations.AddField(
            model_name="journalhistory",
            name="scielo_journal",
            field=modelcluster.fields.ParentalKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="journal_history",
                to="journal.scielojournal",
            ),
        ),
        migrations.AddField(
            model_name="journalhistory",
            name="sort_order",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="journalhistory",
            name="year",
            field=models.CharField(
                blank=True, max_length=4, null=True, verbose_name="Event year"
            ),
        ),
        migrations.AddIndex(
            model_name="journalhistory",
            index=models.Index(
                fields=["event_type"], name="journal_jou_event_t_693227_idx"
            ),
        ),
    ]
