# Generated by Django 4.1.10 on 2023-09-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0002_remove_journal_name_remove_journal_url_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="scielojournal",
            new_name="journal_sci_collect_aa562a_idx",
            old_fields=("collection", "journal_acron"),
        ),
        migrations.RenameIndex(
            model_name="scielojournal",
            new_name="journal_sci_collect_89a5d2_idx",
            old_fields=("collection", "issn_scielo"),
        ),
        migrations.AddIndex(
            model_name="journal",
            index=models.Index(fields=["title"], name="journal_jou_title_4d0afb_idx"),
        ),
    ]
