# Generated by Django 4.2.6 on 2023-11-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0002_journal_contact_address_journal_contact_location_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="officialjournal",
            name="old_title",
        ),
        migrations.AddField(
            model_name="officialjournal",
            name="old_title",
            field=models.ManyToManyField(
                blank=True, null=True, to="journal.officialjournal"
            ),
        ),
    ]
