# Generated by Django 4.1.7 on 2023-02-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0002_alter_mission_creator_alter_mission_updated_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journalsocialnetwork",
            name="name",
            field=models.TextField(
                blank=True,
                choices=[
                    ("facebook", "Facebook"),
                    ("twitter", "Twitter"),
                    ("journal", "Journal URL"),
                ],
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="journalsocialnetwork",
            name="url",
            field=models.URLField(blank=True, null=True, verbose_name="URL"),
        ),
        migrations.AlterField(
            model_name="officialjournal",
            name="title",
            field=models.TextField(
                blank=True, null=True, verbose_name="Official Title"
            ),
        ),
        migrations.AlterField(
            model_name="scielojournal",
            name="name",
            field=models.TextField(
                blank=True,
                choices=[
                    ("facebook", "Facebook"),
                    ("twitter", "Twitter"),
                    ("journal", "Journal URL"),
                ],
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="scielojournal",
            name="short_title",
            field=models.TextField(blank=True, null=True, verbose_name="Short Title"),
        ),
        migrations.AlterField(
            model_name="scielojournal",
            name="submission_online_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="Submission online URL"
            ),
        ),
        migrations.AlterField(
            model_name="scielojournal",
            name="title",
            field=models.TextField(
                blank=True, null=True, verbose_name="SciELO Journal Title"
            ),
        ),
        migrations.AlterField(
            model_name="scielojournal",
            name="url",
            field=models.URLField(blank=True, null=True, verbose_name="URL"),
        ),
    ]
