# Generated by Django 4.2.7 on 2024-01-04 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="officialjournal",
            options={
                "ordering": ["title"],
                "verbose_name": "ISSN Journal",
                "verbose_name_plural": "ISSN Journals",
            },
        ),
        migrations.AlterField(
            model_name="journal",
            name="official",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="journal.officialjournal",
                verbose_name="ISSN Journal",
            ),
        ),
        migrations.AlterField(
            model_name="officialjournal",
            name="title",
            field=models.TextField(blank=True, null=True, verbose_name="ISSN Title"),
        ),
    ]
