# Generated by Django 4.2.6 on 2023-11-21 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("journal", "0003_remove_authorresponsibility_plain_text_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articlesubmissionformat",
            name="language_of_article",
        ),
        migrations.AlterField(
            model_name="articlesubmissionformat",
            name="language",
            field=models.ForeignKey(
                blank=True,
                help_text="Language of Articles",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.language",
                verbose_name="Language",
            ),
        ),
        migrations.AlterField(
            model_name="articlesubmissionformat",
            name="manuscript_length",
            field=models.IntegerField(
                default=False,
                help_text="Manuscript Length (consider spacing)",
                verbose_name="Manuscript Length",
            ),
        ),
    ]
