# Generated by Django 4.2.6 on 2023-11-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0003_journal_journal_jou_use_lic_75bf1c_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indexedat",
            name="acronym",
            field=models.TextField(blank=True, null=True, verbose_name="Acronym"),
        ),
        migrations.AlterField(
            model_name="indexedat",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="indexedat",
            name="name",
            field=models.TextField(blank=True, null=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="indexedat",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DATABASE", "DATABASE"),
                    ("DIRECTORY", "DIRECTORY"),
                    ("OTHER", "OTHER"),
                ],
                max_length=20,
                null=True,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="indexedat",
            name="url",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="URL"
            ),
        ),
    ]
