# Generated by Django 4.1.8 on 2023-05-02 15:30

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_license_options_rename_license_license_url_and_more"),
        ("journal", "0003_alter_journalsocialnetwork_name_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="mission",
            new_name="journal_mis_languag_a94f2f_idx",
            old_name="journal_mis_languag_bfebee_idx",
        ),
        migrations.RemoveField(
            model_name="mission",
            name="text",
        ),
        migrations.AddField(
            model_name="mission",
            name="plain_text",
            field=models.TextField(blank=True, null=True, verbose_name="Plain Text"),
        ),
        migrations.AddField(
            model_name="mission",
            name="rich_text",
            field=wagtail.fields.RichTextField(
                blank=True, null=True, verbose_name="Rich Text"
            ),
        ),
        migrations.AlterField(
            model_name="mission",
            name="language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.language",
                verbose_name="Idioma",
            ),
        ),
    ]
