# Generated by Django 4.2.7 on 2024-01-04 22:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "journal",
            "0003_alter_officialjournal_options_alter_journal_official_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scielojournal",
            options={
                "ordering": ["journal__title"],
                "verbose_name": "SciELO Journal",
                "verbose_name_plural": "SciELO Journals",
            },
        ),
    ]
