# Generated by Django 4.2.7 on 2023-12-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_gender_unique_together"),
        ("reference", "0001_initial"),
        ("journal", "0003_ethics_digitalpreservation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journal",
            name="abstract_language",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="abstract_language",
                to="core.language",
                verbose_name="Abstract Languages",
            ),
        ),
        migrations.AlterField(
            model_name="journal",
            name="indexed_at",
            field=models.ManyToManyField(blank=True, null=True, to="journal.indexedat"),
        ),
        migrations.AlterField(
            model_name="journal",
            name="other_titles",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                to="reference.journaltitle",
                verbose_name="Other titles",
            ),
        ),
        migrations.AlterField(
            model_name="journal",
            name="subject",
            field=models.ManyToManyField(
                blank=True, null=True, to="journal.subject", verbose_name="Study Areas"
            ),
        ),
        migrations.AlterField(
            model_name="journal",
            name="subject_descriptor",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                to="journal.subjectdescriptor",
                verbose_name="Subject Descriptors",
            ),
        ),
        migrations.AlterField(
            model_name="journal",
            name="text_language",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="text_language",
                to="core.language",
                verbose_name="Text Languages",
            ),
        ),
        migrations.AlterField(
            model_name="journal",
            name="wos_area",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                to="journal.webofknowledgesubjectcategory",
                verbose_name="Web of Knowledge Subject Categories",
            ),
        ),
        migrations.AlterField(
            model_name="journal",
            name="wos_db",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                to="journal.webofknowledge",
                verbose_name="Web of Knowledge Databases",
            ),
        ),
    ]
