# Generated by Django 4.1.10 on 2023-09-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0003_merge_20230918_0225"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="url_of_journal",
            field=models.URLField(blank=True, null=True, verbose_name="Url of Journal"),
        ),
    ]
