# Generated by Django 4.2.7 on 2024-01-05 21:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0003_digitalpreservationagency_journal_digital_pa_and_more"),
        ("journal", "0004_alter_scielojournal_options"),
    ]

    operations = []
