# Generated by Django 4.2.6 on 2023-11-21 01:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0004_remove_articlesubmissionformat_language_of_article_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlesubmissionformat",
            name="manuscript_length",
            field=models.IntegerField(
                blank=True,
                help_text="Manuscript Length (consider spacing)",
                null=True,
                verbose_name="Manuscript Length",
            ),
        ),
    ]
