# Generated by Django 4.2.7 on 2024-01-05 15:40

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_licensestatement_unique_together"),
        ("journal", "0004_alter_scielojournal_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalParallelTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(blank=True, null=True, verbose_name="Texto")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="journalparalleltitles",
            name="language",
        ),
        migrations.RemoveIndex(
            model_name="officialjournal",
            name="journal_off_foundat_fcc7eb_idx",
        ),
        migrations.RemoveField(
            model_name="officialjournal",
            name="foundation_year",
        ),
        migrations.AlterField(
            model_name="officialjournal",
            name="terminate_month",
            field=models.CharField(
                blank=True,
                choices=[
                    ("01", "January"),
                    ("02", "February"),
                    ("03", "March"),
                    ("04", "April"),
                    ("05", "May"),
                    ("06", "June"),
                    ("07", "July"),
                    ("08", "August"),
                    ("09", "September"),
                    ("10", "October"),
                    ("11", "November"),
                    ("12", "December"),
                ],
                max_length=2,
                null=True,
                verbose_name="Termination month",
            ),
        ),
        migrations.AlterField(
            model_name="officialjournal",
            name="terminate_year",
            field=models.CharField(
                blank=True, max_length=4, null=True, verbose_name="Termination year"
            ),
        ),
        migrations.AddIndex(
            model_name="officialjournal",
            index=models.Index(
                fields=["initial_year"], name="journal_off_initial_3cf21d_idx"
            ),
        ),
        migrations.DeleteModel(
            name="JournalParallelTitles",
        ),
        migrations.AddField(
            model_name="journalparalleltitle",
            name="language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.language",
                verbose_name="Idioma",
            ),
        ),
        migrations.AddField(
            model_name="journalparalleltitle",
            name="official_journal",
            field=modelcluster.fields.ParentalKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parallel_title",
                to="journal.officialjournal",
            ),
        ),
        migrations.AlterField(
            model_name="officialjournal",
            name="parallel_titles",
            field=models.ManyToManyField(blank=True, to="journal.journalparalleltitle"),
        ),
    ]
