# Generated by Django 4.1.8 on 2023-05-13 01:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0005_websiteresponsibility_review_preprint_policies_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scielojournal",
            name="open_science",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", ""),
                    ("diamond", "Diamond"),
                    ("gold", "Gold"),
                    ("hybrid", "Hybrid"),
                    ("bronze", "Bronze"),
                    ("green", "Green"),
                    ("closed", "Closed"),
                ],
                max_length=10,
                null=True,
                verbose_name="Open Science",
            ),
        ),
        migrations.AddField(
            model_name="scielojournal",
            name="url_oa",
            field=models.URLField(
                blank=True,
                help_text="Suggested form: <a target='_blank' href='https://wp.scielo.org/wp-content/uploads/Formulario-de-Conformidade-Ciencia-Aberta.docx'>https://wp.scielo.org/wp-content/uploads/Formulario-de-Conformidade-Ciencia-Aberta.docx</a>",
                null=True,
                verbose_name="Open Science accordance form",
            ),
        ),
    ]
