# Generated by Django 4.2.7 on 2024-01-08 14:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0005_journalparalleltitle_and_more"),
        ("journal", "0005_merge_20240105_2114"),
    ]

    operations = []
