# Generated by Django 4.2.7 on 2024-01-07 21:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0003_digitalpreservationagency_journal_digital_pa_and_more"),
        ("journal", "0005_journalparalleltitle_and_more"),
    ]

    operations = []
