# Generated by Django 4.1.10 on 2023-09-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0005_annotation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotation",
            name="creation_date",
            field=models.DateField(blank=True, null=True, verbose_name="Creation Date"),
        ),
        migrations.AlterField(
            model_name="annotation",
            name="update_date",
            field=models.DateField(blank=True, null=True, verbose_name="Update Date"),
        ),
    ]
