# Generated by Django 4.1.10 on 2023-09-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0006_alter_annotation_creation_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="acronym_letters",
            field=models.CharField(
                blank=True, max_length=8, null=True, verbose_name="Acronym Letters"
            ),
        ),
        migrations.AddField(
            model_name="journal",
            name="center_code",
            field=models.TextField(
                blank=True, null=True, verbose_name="Center Code"
            ),
        ),
        migrations.AddField(
            model_name="journal",
            name="ftp",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Ftp"
            ),
        ),
        migrations.AddField(
            model_name="journal",
            name="has_supplement",
            field=models.TextField(
                blank=True, null=True, verbose_name="Has Supplement"
            ),
        ),
        migrations.AddField(
            model_name="journal",
            name="identification_number",
            field=models.CharField(
                blank=True,
                max_length=9,
                null=True,
                verbose_name="Identification Number",
            ),
        ),
        migrations.AddField(
            model_name="journal",
            name="is_supplement",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Is supplement"
            ),
        ),
        migrations.AddField(
            model_name="journal",
            name="section",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Section"
            ),
        ),
        migrations.AddField(
            model_name="journal",
            name="subtitle",
            field=models.TextField(blank=True, null=True, verbose_name="Subtitle"),
        ),
        migrations.AddField(
            model_name="journal",
            name="user_subscription",
            field=models.CharField(
                blank=True, max_length=3, null=True, verbose_name="User Subscription"
            ),
        ),
    ]
