# Generated by Django 4.1.8 on 2023-07-24 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("collection", "0005_alter_collectionname_language"),
        ("journal", "0006_scielojournal_open_access_scielojournal_url_oa"),
    ]

    operations = [
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("facebook", "Facebook"),
                            ("twitter", "Twitter"),
                            ("journal", "Journal URL"),
                        ],
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                ("url", models.URLField(blank=True, null=True, verbose_name="URL")),
                (
                    "title",
                    models.TextField(
                        blank=True, null=True, verbose_name="Journal Title"
                    ),
                ),
                (
                    "short_title",
                    models.TextField(blank=True, null=True, verbose_name="Short Title"),
                ),
                (
                    "submission_online_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="Submission online URL"
                    ),
                ),
                (
                    "open_access",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", ""),
                            ("diamond", "Diamond"),
                            ("gold", "Gold"),
                            ("hybrid", "Hybrid"),
                            ("bronze", "Bronze"),
                            ("green", "Green"),
                            ("closed", "Closed"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="Open Access status",
                    ),
                ),
                (
                    "url_oa",
                    models.URLField(
                        blank=True,
                        help_text="Suggested form: <a target='_blank' href='https://wp.scielo.org/wp-content/uploads/Formulario-de-Conformidade-Ciencia-Aberta.docx'>https://wp.scielo.org/wp-content/uploads/Formulario-de-Conformidade-Ciencia-Aberta.docx</a>",
                        null=True,
                        verbose_name="Open Science accordance form",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal",
                "verbose_name_plural": "Journals",
            },
        ),
        migrations.RemoveIndex(
            model_name="scielojournal",
            name="journal_sci_issn_sc_bfe46e_idx",
        ),
        migrations.RemoveIndex(
            model_name="scielojournal",
            name="journal_sci_title_2b7b30_idx",
        ),
        migrations.RemoveIndex(
            model_name="scielojournal",
            name="journal_sci_short_t_54db21_idx",
        ),
        migrations.RemoveIndex(
            model_name="scielojournal",
            name="journal_sci_submiss_fa957f_idx",
        ),
        migrations.AddField(
            model_name="scielojournal",
            name="journal_acron",
            field=models.TextField(
                blank=True, null=True, verbose_name="Journal Acronym"
            ),
        ),
        migrations.AlterIndexTogether(
            name="scielojournal",
            index_together={
                ("collection", "issn_scielo"),
                ("collection", "journal_acron"),
            },
        ),
        migrations.AddField(
            model_name="journal",
            name="collection",
            field=models.ManyToManyField(
                to="collection.collection", verbose_name="Collection"
            ),
        ),
        migrations.AddField(
            model_name="journal",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AddField(
            model_name="journal",
            name="logo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="journal",
            name="official",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="journal.officialjournal",
                verbose_name="Official Journal",
            ),
        ),
        migrations.AddField(
            model_name="journal",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updater",
            ),
        ),
        migrations.RemoveField(
            model_name="scielojournal",
            name="logo",
        ),
        migrations.RemoveField(
            model_name="scielojournal",
            name="official",
        ),
        migrations.RemoveField(
            model_name="scielojournal",
            name="open_access",
        ),
        migrations.RemoveField(
            model_name="scielojournal",
            name="short_title",
        ),
        migrations.RemoveField(
            model_name="scielojournal",
            name="submission_online_url",
        ),
        migrations.RemoveField(
            model_name="scielojournal",
            name="title",
        ),
        migrations.RemoveField(
            model_name="scielojournal",
            name="url_oa",
        ),
        migrations.AddField(
            model_name="scielojournal",
            name="journal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="journal.journal",
                verbose_name="Journal",
            ),
        ),
        migrations.AlterField(
            model_name="authorresponsibility",
            name="journal",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author_responsibility",
                to="journal.journal",
            ),
        ),
        migrations.AlterField(
            model_name="conflictpolicy",
            name="journal",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conflict_policy",
                to="journal.journal",
            ),
        ),
        migrations.AlterField(
            model_name="copyright",
            name="journal",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="copyright",
                to="journal.journal",
            ),
        ),
        migrations.AlterField(
            model_name="ecommittee",
            name="journal",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ecommittee",
                to="journal.journal",
            ),
        ),
        migrations.AlterField(
            model_name="editorialmanager",
            name="page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="editorialmanager",
                to="journal.journal",
            ),
        ),
        migrations.AlterField(
            model_name="focus",
            name="journal",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="focus",
                to="journal.journal",
            ),
        ),
        migrations.AlterField(
            model_name="history",
            name="journal",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history",
                to="journal.journal",
            ),
        ),
        migrations.AlterField(
            model_name="journalsocialnetwork",
            name="page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journalsocialnetwork",
                to="journal.journal",
            ),
        ),
        migrations.AlterField(
            model_name="mission",
            name="journal",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mission",
                to="journal.journal",
            ),
        ),
        migrations.AlterField(
            model_name="opendata",
            name="journal",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="open_data",
                to="journal.journal",
            ),
        ),
        migrations.AlterField(
            model_name="owner",
            name="page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner",
                to="journal.journal",
            ),
        ),
        migrations.AlterField(
            model_name="policies",
            name="journal",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="policies",
                to="journal.journal",
            ),
        ),
        migrations.AlterField(
            model_name="preprint",
            name="journal",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preprint",
                to="journal.journal",
            ),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="publisher",
                to="journal.journal",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="journal",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review",
                to="journal.journal",
            ),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sponsor",
                to="journal.journal",
            ),
        ),
        migrations.AlterField(
            model_name="websiteresponsibility",
            name="journal",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="website_responsibility",
                to="journal.journal",
            ),
        ),
        migrations.AddIndex(
            model_name="journal",
            index=models.Index(
                fields=["official"], name="journal_jou_officia_c67937_idx"
            ),
        ),
    ]
