# Generated by Django 4.2.7 on 2024-01-08 20:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0007_alter_journal_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="titleindatabase",
            options={
                "verbose_name": "Title in Database",
                "verbose_name_plural": "Title in databases",
            },
        ),
        migrations.AlterUniqueTogether(
            name="titleindatabase",
            unique_together={("journal", "indexed_at",)},
        ),
    ]
