# Generated by Django 4.2.7 on 2024-01-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0008_alter_titleindatabase_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="officialjournal",
            name="next_journal_title",
            field=models.TextField(
                blank=True, null=True, verbose_name="Next Journal Title"
            ),
        ),
        migrations.AddField(
            model_name="officialjournal",
            name="previous_journal_titles",
            field=models.TextField(
                blank=True, null=True, verbose_name="Previous Journal titles"
            ),
        ),
    ]
