# Generated by Django 4.2.7 on 2024-01-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0009_officialjournal_next_journal_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="officialjournal",
            name="issn_print_status",
            field=models.BooleanField(default=False),
        ),
    ]
