# Generated by Django 4.1.10 on 2023-09-21 17:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0009_alter_annotation_journal_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="journal",
            name="collection",
        ),
    ]
