# Generated by Django 4.1.10 on 2023-09-21 17:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0003_officialjournal_final_number_and_more"),
        ("journal", "0010_remove_journal_collection"),
    ]

    operations = []
