# Generated by Django 4.2.7 on 2024-01-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0010_officialjournal_issn_print_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="valid",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
