# Generated by Django 4.1.10 on 2023-09-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0011_merge_20230921_1756"),
    ]

    operations = [
        migrations.AlterField(
            model_name="officialjournal",
            name="terminate_month",
            field=models.CharField(
                blank=True,
                choices=[
                    ("01", "January"),
                    ("02", "February"),
                    ("03", "March"),
                    ("04", "April"),
                    ("05", "May"),
                    ("06", "June"),
                    ("07", "July"),
                    ("08", "August"),
                    ("09", "September"),
                    ("10", "October"),
                    ("11", "November"),
                    ("12", "December"),
                ],
                max_length=2,
                null=True,
                verbose_name="Terminate month",
            ),
        ),
    ]
