# Generated by Django 4.2.7 on 2024-01-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0011_journal_valid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="additionalindexedat",
            name="name",
            field=models.TextField(blank=True, null=True, verbose_name="Name"),
        ),
    ]
