# Generated by Django 4.1.10 on 2023-09-22 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("journal", "0013_officialjournal_initial_month_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "occurrence_date_year",
                    models.CharField(max_length=4, verbose_name="Occurrence date year", blank=True, null=True,)
                ),
                (
                    "occurrence_date_month",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("01", "January"),
                            ("02", "February"),
                            ("03", "March"),
                            ("04", "April"),
                            ("05", "May"),
                            ("06", "June"),
                            ("07", "July"),
                            ("08", "August"),
                            ("09", "September"),
                            ("10", "October"),
                            ("11", "November"),
                            ("12", "December"),
                        ],
                        max_length=2,
                        null=True,
                        verbose_name="Occurrence date month",
                    ),
                ),
                (
                    "occurrence_date_day",
                    models.CharField(
                        blank=True,
                        max_length=2,
                        null=True,
                        verbose_name="Occurrence date day",
                    ),
                ),
                (
                    "occurrence_type",
                    models.TextField(
                        blank=True, null=True, verbose_name="Occurrence type"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
            },
        ),
        migrations.AddField(
            model_name="scielojournal",
            name="journal_history",
            field=models.ManyToManyField(
                to="journal.journalhistory", verbose_name="Journal History"
            ),
        ),
        migrations.AddIndex(
            model_name="journalhistory",
            index=models.Index(
                fields=["occurrence_type"], name="journal_jou_occurre_d59679_idx"
            ),
        ),
    ]
