# Generated by Django 4.1.10 on 2023-09-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0014_journalhistory_scielojournal_journal_history_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="journalhistory",
            name="occurrence_date_day",
        ),
        migrations.RemoveField(
            model_name="journalhistory",
            name="occurrence_date_month",
        ),
        migrations.RemoveField(
            model_name="journalhistory",
            name="occurrence_date_year",
        ),
        migrations.AddField(
            model_name="journalhistory",
            name="final_day",
            field=models.CharField(
                blank=True,
                max_length=2,
                null=True,
                verbose_name="Final Occurrence date day",
            ),
        ),
        migrations.AddField(
            model_name="journalhistory",
            name="final_month",
            field=models.CharField(
                blank=True,
                choices=[
                    ("01", "January"),
                    ("02", "February"),
                    ("03", "March"),
                    ("04", "April"),
                    ("05", "May"),
                    ("06", "June"),
                    ("07", "July"),
                    ("08", "August"),
                    ("09", "September"),
                    ("10", "October"),
                    ("11", "November"),
                    ("12", "December"),
                ],
                max_length=2,
                null=True,
                verbose_name="Final Occurrence date month",
            ),
        ),
        migrations.AddField(
            model_name="journalhistory",
            name="final_year",
            field=models.CharField(
                blank=True,
                max_length=4,
                null=True,
                verbose_name="Final Occurrence date year",
            ),
        ),
        migrations.AddField(
            model_name="journalhistory",
            name="initial_day",
            field=models.CharField(
                blank=True,
                max_length=2,
                null=True,
                verbose_name="Initial Occurrence date day",
            ),
        ),
        migrations.AddField(
            model_name="journalhistory",
            name="initial_month",
            field=models.CharField(
                blank=True,
                choices=[
                    ("01", "January"),
                    ("02", "February"),
                    ("03", "March"),
                    ("04", "April"),
                    ("05", "May"),
                    ("06", "June"),
                    ("07", "July"),
                    ("08", "August"),
                    ("09", "September"),
                    ("10", "October"),
                    ("11", "November"),
                    ("12", "December"),
                ],
                max_length=2,
                null=True,
                verbose_name="Initial Occurrence date month",
            ),
        ),
        migrations.AddField(
            model_name="journalhistory",
            name="initial_year",
            field=models.CharField(
                blank=True,
                max_length=4,
                null=True,
                verbose_name="Initial Occurrence date year",
            ),
        ),
    ]
