# Generated by Django 4.2.7 on 2024-01-31 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0014_remove_officialjournal_issn_print_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journalsocialnetwork",
            name="name",
            field=models.CharField(
                blank=True,
                choices=[("facebook", "Facebook"), ("twitter", "Twitter")],
                max_length=20,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="scielojournal",
            name="name",
            field=models.CharField(
                blank=True,
                choices=[("facebook", "Facebook"), ("twitter", "Twitter")],
                max_length=20,
                null=True,
                verbose_name="Name",
            ),
        ),
    ]
