# Generated by Django 4.1.10 on 2023-10-11 01:41

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        (
            "institution",
            "0006_copyrightholder_editorialmanager_owner_publisher_and_more",
        ),
        ("journal", "0015_remove_journalhistory_occurrence_date_day_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CopyrightHolderHistory",
            fields=[
                (
                    "copyrightholderhistoryitem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="institution.copyrightholderhistoryitem",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
            bases=("institution.copyrightholderhistoryitem", models.Model),
        ),
        migrations.CreateModel(
            name="EditorialManagerHistory",
            fields=[
                (
                    "editorialmanagerhistoryitem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="institution.editorialmanagerhistoryitem",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
            bases=("institution.editorialmanagerhistoryitem", models.Model),
        ),
        migrations.CreateModel(
            name="OwnerHistory",
            fields=[
                (
                    "ownerhistoryitem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="institution.ownerhistoryitem",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
            bases=("institution.ownerhistoryitem", models.Model),
        ),
        migrations.CreateModel(
            name="PublisherHistory",
            fields=[
                (
                    "publisherhistoryitem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="institution.publisherhistoryitem",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
            bases=("institution.publisherhistoryitem", models.Model),
        ),
        migrations.CreateModel(
            name="SponsorHistory",
            fields=[
                (
                    "sponsorhistoryitem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="institution.sponsorhistoryitem",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
            bases=("institution.sponsorhistoryitem", models.Model),
        ),
        migrations.RemoveField(
            model_name="owner",
            name="institutionhistory_ptr",
        ),
        migrations.RemoveField(
            model_name="owner",
            name="page",
        ),
        migrations.RemoveField(
            model_name="publisher",
            name="institutionhistory_ptr",
        ),
        migrations.RemoveField(
            model_name="publisher",
            name="page",
        ),
        migrations.RemoveField(
            model_name="sponsor",
            name="institutionhistory_ptr",
        ),
        migrations.RemoveField(
            model_name="sponsor",
            name="page",
        ),
        migrations.RemoveField(
            model_name="journal",
            name="url_of_journal",
        ),
        migrations.AddField(
            model_name="journal",
            name="journal_url",
            field=models.URLField(blank=True, null=True, verbose_name="Journal URL"),
        ),
        migrations.AlterField(
            model_name="officialjournal",
            name="new_title",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="new_title_journal",
                to="journal.officialjournal",
                verbose_name="New Title",
            ),
        ),
        migrations.AlterField(
            model_name="officialjournal",
            name="old_title",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="old_title_journal",
                to="journal.officialjournal",
                verbose_name="Old Title",
            ),
        ),
        migrations.DeleteModel(
            name="EditorialManager",
        ),
        migrations.DeleteModel(
            name="Owner",
        ),
        migrations.DeleteModel(
            name="Publisher",
        ),
        migrations.DeleteModel(
            name="Sponsor",
        ),
        migrations.AddField(
            model_name="sponsorhistory",
            name="journal",
            field=modelcluster.fields.ParentalKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sponsor_history",
                to="journal.journal",
            ),
        ),
        migrations.AddField(
            model_name="publisherhistory",
            name="journal",
            field=modelcluster.fields.ParentalKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="publisher_history",
                to="journal.journal",
            ),
        ),
        migrations.AddField(
            model_name="ownerhistory",
            name="journal",
            field=modelcluster.fields.ParentalKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owner_history",
                to="journal.journal",
            ),
        ),
        migrations.AddField(
            model_name="editorialmanagerhistory",
            name="journal",
            field=modelcluster.fields.ParentalKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="editorialmanager_history",
                to="journal.journal",
            ),
        ),
        migrations.AddField(
            model_name="copyrightholderhistory",
            name="journal",
            field=modelcluster.fields.ParentalKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="copyright_holder_history",
                to="journal.journal",
            ),
        ),
    ]
