# Generated by Django 4.2.7 on 2024-02-07 18:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0015_alter_journalsocialnetwork_name_and_more"),
        ("journal", "0015_alter_subjectdescriptor_value"),
    ]

    operations = []
