# Generated by Django 4.2.7 on 2024-02-26 01:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0016_merge_20240207_1816"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="journal",
            name="other_titles",
        ),
    ]
