# Generated by Django 4.2.7 on 2024-02-26 04:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("journal", "0018_journallogo"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="journallogo",
            unique_together={("journal", "logo")},
        ),
    ]
