# Generated by Django 5.0.3 on 2024-05-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0023_alter_officialjournal_issn_electronic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="officialjournal",
            name="issn_electronic",
            field=models.CharField(
                blank=True, max_length=9, null=True, verbose_name="Electronic ISSN"
            ),
        ),
        migrations.AlterField(
            model_name="officialjournal",
            name="issn_print",
            field=models.CharField(
                blank=True, max_length=9, null=True, verbose_name="Print ISSN"
            ),
        ),
    ]
