# Generated by Django 5.0.3 on 2024-08-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0026_editorialpolicy_opensciencecompliance"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="doi_prefix",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
