# Generated by Django 5.0.8 on 2025-02-04 18:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0028_journaltocsection_tocitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scielojournal",
            name="journal_acron",
            field=models.TextField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_journal_acron",
                        message="Only letters are allowed",
                        regex="^[a-zA-Z]+$",
                    )
                ],
                verbose_name="Journal Acronym",
            ),
        ),
    ]
