# Generated by Django 5.0.8 on 2025-04-30 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institution", "0005_institution_institution_type_scielo_and_more"),
        ("journal", "0031_copyrightholderhistory_organization_and_more"),
        (
            "organization",
            "0002_orglevelcopyrightholderhistory_orglevelownerhistory_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="copyrightholderhistory",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                help_text="Field containing non-standardized institution names from the Institution model.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="institution.copyrightholder",
            ),
        ),
        migrations.AlterField(
            model_name="copyrightholderhistory",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Field containing standardized institution names selected from the Organization model.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="organization.organization",
            ),
        ),
        migrations.AlterField(
            model_name="ownerhistory",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                help_text="Field containing non-standardized institution names from the Institution model.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="institution.owner",
            ),
        ),
        migrations.AlterField(
            model_name="ownerhistory",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Field containing standardized institution names selected from the Organization model.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="organization.organization",
            ),
        ),
        migrations.AlterField(
            model_name="publisherhistory",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                help_text="Field containing non-standardized institution names from the Institution model.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="institution.publisher",
            ),
        ),
        migrations.AlterField(
            model_name="publisherhistory",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Field containing standardized institution names selected from the Organization model.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="organization.organization",
            ),
        ),
        migrations.AlterField(
            model_name="sponsorhistory",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                help_text="Field containing non-standardized institution names from the Institution model.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="institution.sponsor",
            ),
        ),
        migrations.AlterField(
            model_name="sponsorhistory",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Field containing standardized institution names selected from the Organization model.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="organization.organization",
            ),
        ),
    ]
