# Generated by Django 5.0.8 on 2025-04-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0031_copyrightholderhistory_organization_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journal",
            name="additional_indexed_at",
            field=models.ManyToManyField(
                blank=True,
                help_text="Values from additional scientific databases that are not standardized.",
                to="journal.additionalindexedat",
                verbose_name="Additional Index At",
            ),
        ),
        migrations.AlterField(
            model_name="journal",
            name="indexed_at",
            field=models.ManyToManyField(
                blank=True,
                help_text="Standardized values from recognized scientific databases, such as: Dimensions, DOAJ, Google Scholar, Latindex, MEDLINE, SCImago, etc.",
                to="journal.indexedat",
                verbose_name="Indexed At",
            ),
        ),
    ]
