# Generated by Django 5.0.8 on 2025-05-13 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0032_alter_journal_additional_indexed_at_and_more"),
        ("journal", "0032_alter_journal_options"),
    ]

    operations = []
