# Generated by Django 5.0.8 on 2025-05-20 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0032_alter_copyrightholderhistory_institution_and_more"),
        ("journal", "0033_merge_20250513_1813"),
    ]

    operations = []
