# Generated by Django 5.0.8 on 2025-05-26 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0035_alter_accepteddocumenttypes_created_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="journal",
            options={
                "ordering": ("title",),
                "verbose_name": "Journal",
                "verbose_name_plural": "Journals",
            },
        ),
    ]
