# Generated by Django 5.0.8 on 2025-05-26 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0037_remove_permissions_journal"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="journal",
            options={
                "ordering": ("title",),
                "permissions": [],
                "verbose_name": "Journal",
                "verbose_name_plural": "Journals",
            },
        ),
    ]
