# Generated by Django 5.0.8 on 2025-06-10 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0038_alter_journal_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalProxyEditor",
            fields=[],
            options={
                "verbose_name": "Journal Editor",
                "verbose_name_plural": "Journal Editors",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("journal.journal",),
        ),
    ]
