# Generated by Django 5.0.8 on 2025-07-24 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0039_journalproxyeditor"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="journal",
            options={
                "ordering": ("title",),
                "verbose_name": "Journal",
                "verbose_name_plural": "Journals",
            },
        ),
    ]
