# Generated by Django 5.0.8 on 2025-07-18 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0040_subject_journal_sub_value_0138a4_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalProxyPanelInstructionsForAuthors",
            fields=[],
            options={
                "verbose_name": "Journal Instructions for Authors",
                "verbose_name_plural": "Journal Instructions for Authors",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("journal.journal",),
        ),
        migrations.CreateModel(
            name="JournalProxyPanelPolicy",
            fields=[],
            options={
                "verbose_name": "Journal Policy",
                "verbose_name_plural": "Journal Policy",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("journal.journal",),
        ),
    ]
