# Generated by Django 5.2.3 on 2025-08-04 22:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0040_alter_journal_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalProxyPanelInstructionsForAuthors",
            fields=[],
            options={
                "verbose_name": "Journal Instructions for Authors",
                "verbose_name_plural": "Journal Instructions for Authors",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("journal.journal",),
        ),
        migrations.CreateModel(
            name="JournalProxyPanelPolicy",
            fields=[],
            options={
                "verbose_name": "Journal Policy",
                "verbose_name_plural": "Journal Policy",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("journal.journal",),
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(fields=["value"], name="journal_sub_value_0138a4_idx"),
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(fields=["code"], name="journal_sub_code_2d8324_idx"),
        ),
        migrations.AddIndex(
            model_name="subjectdescriptor",
            index=models.Index(fields=["value"], name="journal_sub_value_e05034_idx"),
        ),
    ]
