# Generated by Django 5.2.3 on 2025-08-01 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0040_alter_journal_options"),
        ("journal", "0041_journalproxypanelinstructionsforauthors_and_more"),
    ]

    operations = []
