# Generated by Django 5.2.3 on 2025-08-04 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0042_merge_20250801_1525"),
        (
            "organization",
            "0008_remove_organization_organizatio_is_offi_538fd2_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="copyrightholderhistory",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the standardized organization data",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="organization.organization",
            ),
        ),
        migrations.AlterField(
            model_name="journalsocialnetwork",
            name="name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("facebook", "Facebook"),
                    ("twitter", "Twitter"),
                    ("mastodon", "Mastodon"),
                    ("bsky", "Discover Blue Sky"),
                    ("youtube", "Youtube"),
                ],
                max_length=20,
                null=True,
                verbose_name="Nome",
            ),
        ),
        migrations.AlterField(
            model_name="ownerhistory",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the standardized organization data",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="organization.organization",
            ),
        ),
        migrations.AlterField(
            model_name="publisherhistory",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the standardized organization data",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="organization.organization",
            ),
        ),
        migrations.AlterField(
            model_name="scielojournal",
            name="name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("facebook", "Facebook"),
                    ("twitter", "Twitter"),
                    ("mastodon", "Mastodon"),
                    ("bsky", "Discover Blue Sky"),
                    ("youtube", "Youtube"),
                ],
                max_length=20,
                null=True,
                verbose_name="Nome",
            ),
        ),
        migrations.AlterField(
            model_name="sponsorhistory",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the standardized organization data",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="organization.organization",
            ),
        ),
    ]
