# Generated by Django 5.2.3 on 2025-09-05 15:10

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0044_alter_officialjournal_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authorresponsibility",
            name="rich_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text='The author\'s declaration of responsibility for the content published in\n            the journal that owns the copyright Ex. DOAJ: The terms of copyright must not contradict\n            the terms of the license or the terms of the open access policy. "All rights reserved" is\n            never appropriate for open access content',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="authorscontributions",
            name="rich_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Description of how authors contributions should be specified.\n        Does it use any taxonomy? If yes, which one?\n        Does the article text explicitly state the authors contributions?\n        Preferably, use the CREDiT taxonomy structure: <a target='_blank'\n            href='https://casrai.org/credit/'>https://casrai.org/credit/</a>\n        ",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="copyright",
            name="rich_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Describe the policy used by the journal on copyright issues.\n            We recommend that this section be in accordance with the recommendations of the SciELO criteria,\n            item 5.2.10.1.2. - Copyright",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ecommittee",
            name="rich_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Authors must attach a statement of approval from the ethics committee of\n            the institution responsible for approving the research",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="feecharging",
            name="rich_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Please describe any charges to authors related to the submission or publication of works.\n        For article publication: Clearly state when no fees are charged.\n        Under what circumstances are charges applicable? Are there any discounts?\n        SciELO Statement on Financial Sustainability: <a target='_blank'\n            href='https://mailchi.mp/scielo/declaracao-sobre-sustentabilidade'>\n            https://mailchi.mp/scielo/declaracao-sobre-sustentabilidade</a>\n        ",
                null=True,
                verbose_name="Concepts",
            ),
        ),
        migrations.AlterField(
            model_name="opendata",
            name="rich_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Refers to sharing data, codes, methods and other materials used and\n            resulting from research that are usually the basis of the texts of articles published by journals.\n            Guide: <a target='_blank' href='https://wp.scielo.org/wp-content/uploads/Guia_TOP_pt.pdf'>https://wp.scielo.org/wp-content/uploads/Guia_TOP_pt.pdf</a>",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="policies",
            name="rich_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Describe here how the journal will deal with ethical issues and/or\n            issues that may damage the journal's reputation. What is the journal's position regarding\n            the retraction policy that the journal will adopt in cases of misconduct.\n            Best practice guide: <a target='_blank'\n            href='https://wp.scielo.org/wp-content/uploads/Guia-de-Boas-Praticas-para-o-Fortalecimento-da-Etica-na-Publicacao-Cientifica.pdf'>\n            https://wp.scielo.org/wp-content/uploads/Guia-de-Boas-Praticas-para-o-Fortalecimento-da-Etica-na-Publicacao-Cientifica.pdf</a>",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="preprint",
            name="rich_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="A preprint is defined as a manuscript ready for submission to a journal that is deposited\n            with trusted preprint servers before or in parallel with submission to a journal.\n            This practice joins that of continuous publication as mechanisms to speed up research communication.\n            Preprints share with journals the originality in the publication of articles and inhibit the use of\n            the double-blind procedure in the evaluation of manuscripts.\n            The use of preprints is an option and choice of the authors and it is up to the journals to adapt\n            their policies to accept the submission of manuscripts previously deposited in a preprints server\n            recognized by the journal.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="websiteresponsibility",
            name="rich_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="EX. DOAJ: Copyright terms applied to posted content must be clearly stated and separate\n            from copyright terms applied to the website",
                null=True,
            ),
        ),
    ]
