# Generated by Django 5.2.3 on 2025-09-25 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0046_rename_scielo_issn_amjournal_pid_journalexporter_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="JournalExporter",
        ),
    ]
