# Generated by Django 5.2.3 on 2025-09-25 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0048_journalexporter"),
        ("location", "0003_alter_city_options_alter_country_options_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="officialjournal",
            name="journal_off_issnl_4304c5_idx",
        ),
        migrations.AddField(
            model_name="officialjournal",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="location.country",
                verbose_name="Country",
            ),
        ),
    ]
