# Generated by Django 5.2.3 on 2025-09-30 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "collection",
            "0006_alter_collection_options_alter_collection_acron2_and_more",
        ),
        (
            "journal",
            "0049_remove_officialjournal_journal_off_issnl_4304c5_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="scielojournal",
            name="collection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="collection.collection",
                verbose_name="Collection",
            ),
        ),
    ]
