# Generated by Django 5.2.3 on 2025-10-21 10:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0052_amjournal_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scielojournal",
            name="journal_acron",
            field=models.CharField(
                blank=True,
                max_length=16,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_journal_acron",
                        message="Only lowercase letters are allowed",
                        regex="^[a-z]+$",
                    )
                ],
                verbose_name="Journal Acronym",
            ),
        ),
    ]
