# Generated by Django 5.2.7 on 2025-12-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0054_journaltableofcontents"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="journal",
            name="url_oa",
        ),
        migrations.AlterField(
            model_name="journal",
            name="digital_pa",
            field=models.ManyToManyField(
                blank=True,
                to="journal.digitalpreservationagency",
                verbose_name="Digital Preservation (SciELO)",
            ),
        ),
    ]
