# Generated by Django 5.2.7 on 2026-01-31 21:41

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0054_journaltableofcontents"),
        ("organization", "0011_organizationallevel_raworganization_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="additionalindexedat",
            name="name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="indexedat",
            name="acronym",
            field=models.CharField(max_length=32, null=True, verbose_name="Acronym"),
        ),
        migrations.AlterField(
            model_name="indexedat",
            name="description",
            field=models.CharField(null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="indexedat",
            name="name",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="journal",
            name="center_code",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Center code"
            ),
        ),
        migrations.AlterField(
            model_name="journal",
            name="classification",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="Classification"
            ),
        ),
        migrations.AlterField(
            model_name="journal",
            name="contact_address",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Address"
            ),
        ),
        migrations.AlterField(
            model_name="journal",
            name="contact_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="journal",
            name="has_supplement",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Has Supplement"
            ),
        ),
        migrations.AlterField(
            model_name="journal",
            name="national_code",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="National Code"
            ),
        ),
        migrations.AlterField(
            model_name="journal",
            name="short_title",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Short Title"
            ),
        ),
        migrations.AlterField(
            model_name="journal",
            name="subtitle",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Subtitle"
            ),
        ),
        migrations.AlterField(
            model_name="journal",
            name="title",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Journal Title"
            ),
        ),
        migrations.AlterField(
            model_name="journalothertitle",
            name="title",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="officialjournal",
            name="iso_short_title",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ISO Short Title"
            ),
        ),
        migrations.AlterField(
            model_name="officialjournal",
            name="next_journal_title",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Next Journal Title"
            ),
        ),
        migrations.AlterField(
            model_name="officialjournal",
            name="previous_journal_titles",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Previous Journal titles",
            ),
        ),
        migrations.AlterField(
            model_name="officialjournal",
            name="title",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ISSN Title"
            ),
        ),
        migrations.AlterField(
            model_name="standard",
            name="value",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="titleindatabase",
            name="title",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Title"
            ),
        ),
        migrations.CreateModel(
            name="JournalOrganization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "initial_date",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Initial Date",
                    ),
                ),
                (
                    "final_date",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Final Date"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("coordinator", "Coordinator"),
                            ("owner", "Owner"),
                            ("publisher", "Publisher"),
                            ("sponsor", "Sponsor"),
                            ("copyright_holder", "Copyright Holder"),
                            ("partner", "Partner"),
                            ("funder", "Funder"),
                            ("host", "Host"),
                            ("provider", "Provider"),
                            ("company", "Company"),
                        ],
                        max_length=50,
                        verbose_name="Role",
                    ),
                ),
                (
                    "original_data",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Original data",
                    ),
                ),
                (
                    "journal",
                    modelcluster.fields.ParentalKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organizations",
                        to="journal.journal",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Select the standardized organization data",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="organization.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal Organization",
                "verbose_name_plural": "Journal Organizations",
                "unique_together": {
                    ("journal", "role", "organization"),
                    ("journal", "role", "original_data"),
                },
            },
        ),
    ]
