# Generated by Django 5.2.7 on 2026-02-24 23:02

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_licensestatement_options_and_more"),
        ("journal", "0054_journaltableofcontents"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalProxyAdminOnly",
            fields=[],
            options={
                "verbose_name": "Journal (Admin Only)",
                "verbose_name_plural": "Journals (Admin Only)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("journal.journal",),
        ),
        migrations.AddField(
            model_name="copyrightholderhistory",
            name="raw_city_name",
            field=models.CharField(
                blank=True,
                help_text="Raw city name as provided",
                max_length=255,
                null=True,
                verbose_name="Raw City Name",
            ),
        ),
        migrations.AddField(
            model_name="copyrightholderhistory",
            name="raw_country_code",
            field=models.CharField(
                blank=True,
                help_text="Raw country code (ISO) as provided",
                max_length=3,
                null=True,
                verbose_name="Raw Country Code",
            ),
        ),
        migrations.AddField(
            model_name="copyrightholderhistory",
            name="raw_country_name",
            field=models.CharField(
                blank=True,
                help_text="Raw country name as provided",
                max_length=255,
                null=True,
                verbose_name="Raw Country Name",
            ),
        ),
        migrations.AddField(
            model_name="copyrightholderhistory",
            name="raw_institution_name",
            field=models.CharField(
                blank=True,
                help_text="Raw institution name as provided",
                max_length=510,
                null=True,
                verbose_name="Raw Institution Name",
            ),
        ),
        migrations.AddField(
            model_name="copyrightholderhistory",
            name="raw_state_acron",
            field=models.CharField(
                blank=True,
                help_text="Raw state acronym as provided",
                max_length=10,
                null=True,
                verbose_name="Raw State Acronym",
            ),
        ),
        migrations.AddField(
            model_name="copyrightholderhistory",
            name="raw_state_name",
            field=models.CharField(
                blank=True,
                help_text="Raw state name as provided",
                max_length=255,
                null=True,
                verbose_name="Raw State Name",
            ),
        ),
        migrations.AddField(
            model_name="copyrightholderhistory",
            name="raw_text",
            field=models.TextField(
                blank=True,
                help_text="Free text, unstructured organization data",
                null=True,
                verbose_name="Raw Text",
            ),
        ),
        migrations.AddField(
            model_name="ownerhistory",
            name="raw_city_name",
            field=models.CharField(
                blank=True,
                help_text="Raw city name as provided",
                max_length=255,
                null=True,
                verbose_name="Raw City Name",
            ),
        ),
        migrations.AddField(
            model_name="ownerhistory",
            name="raw_country_code",
            field=models.CharField(
                blank=True,
                help_text="Raw country code (ISO) as provided",
                max_length=3,
                null=True,
                verbose_name="Raw Country Code",
            ),
        ),
        migrations.AddField(
            model_name="ownerhistory",
            name="raw_country_name",
            field=models.CharField(
                blank=True,
                help_text="Raw country name as provided",
                max_length=255,
                null=True,
                verbose_name="Raw Country Name",
            ),
        ),
        migrations.AddField(
            model_name="ownerhistory",
            name="raw_institution_name",
            field=models.CharField(
                blank=True,
                help_text="Raw institution name as provided",
                max_length=510,
                null=True,
                verbose_name="Raw Institution Name",
            ),
        ),
        migrations.AddField(
            model_name="ownerhistory",
            name="raw_state_acron",
            field=models.CharField(
                blank=True,
                help_text="Raw state acronym as provided",
                max_length=10,
                null=True,
                verbose_name="Raw State Acronym",
            ),
        ),
        migrations.AddField(
            model_name="ownerhistory",
            name="raw_state_name",
            field=models.CharField(
                blank=True,
                help_text="Raw state name as provided",
                max_length=255,
                null=True,
                verbose_name="Raw State Name",
            ),
        ),
        migrations.AddField(
            model_name="ownerhistory",
            name="raw_text",
            field=models.TextField(
                blank=True,
                help_text="Free text, unstructured organization data",
                null=True,
                verbose_name="Raw Text",
            ),
        ),
        migrations.AddField(
            model_name="publisherhistory",
            name="raw_city_name",
            field=models.CharField(
                blank=True,
                help_text="Raw city name as provided",
                max_length=255,
                null=True,
                verbose_name="Raw City Name",
            ),
        ),
        migrations.AddField(
            model_name="publisherhistory",
            name="raw_country_code",
            field=models.CharField(
                blank=True,
                help_text="Raw country code (ISO) as provided",
                max_length=3,
                null=True,
                verbose_name="Raw Country Code",
            ),
        ),
        migrations.AddField(
            model_name="publisherhistory",
            name="raw_country_name",
            field=models.CharField(
                blank=True,
                help_text="Raw country name as provided",
                max_length=255,
                null=True,
                verbose_name="Raw Country Name",
            ),
        ),
        migrations.AddField(
            model_name="publisherhistory",
            name="raw_institution_name",
            field=models.CharField(
                blank=True,
                help_text="Raw institution name as provided",
                max_length=510,
                null=True,
                verbose_name="Raw Institution Name",
            ),
        ),
        migrations.AddField(
            model_name="publisherhistory",
            name="raw_state_acron",
            field=models.CharField(
                blank=True,
                help_text="Raw state acronym as provided",
                max_length=10,
                null=True,
                verbose_name="Raw State Acronym",
            ),
        ),
        migrations.AddField(
            model_name="publisherhistory",
            name="raw_state_name",
            field=models.CharField(
                blank=True,
                help_text="Raw state name as provided",
                max_length=255,
                null=True,
                verbose_name="Raw State Name",
            ),
        ),
        migrations.AddField(
            model_name="publisherhistory",
            name="raw_text",
            field=models.TextField(
                blank=True,
                help_text="Free text, unstructured organization data",
                null=True,
                verbose_name="Raw Text",
            ),
        ),
        migrations.AddField(
            model_name="sponsorhistory",
            name="raw_city_name",
            field=models.CharField(
                blank=True,
                help_text="Raw city name as provided",
                max_length=255,
                null=True,
                verbose_name="Raw City Name",
            ),
        ),
        migrations.AddField(
            model_name="sponsorhistory",
            name="raw_country_code",
            field=models.CharField(
                blank=True,
                help_text="Raw country code (ISO) as provided",
                max_length=3,
                null=True,
                verbose_name="Raw Country Code",
            ),
        ),
        migrations.AddField(
            model_name="sponsorhistory",
            name="raw_country_name",
            field=models.CharField(
                blank=True,
                help_text="Raw country name as provided",
                max_length=255,
                null=True,
                verbose_name="Raw Country Name",
            ),
        ),
        migrations.AddField(
            model_name="sponsorhistory",
            name="raw_institution_name",
            field=models.CharField(
                blank=True,
                help_text="Raw institution name as provided",
                max_length=510,
                null=True,
                verbose_name="Raw Institution Name",
            ),
        ),
        migrations.AddField(
            model_name="sponsorhistory",
            name="raw_state_acron",
            field=models.CharField(
                blank=True,
                help_text="Raw state acronym as provided",
                max_length=10,
                null=True,
                verbose_name="Raw State Acronym",
            ),
        ),
        migrations.AddField(
            model_name="sponsorhistory",
            name="raw_state_name",
            field=models.CharField(
                blank=True,
                help_text="Raw state name as provided",
                max_length=255,
                null=True,
                verbose_name="Raw State Name",
            ),
        ),
        migrations.AddField(
            model_name="sponsorhistory",
            name="raw_text",
            field=models.TextField(
                blank=True,
                help_text="Free text, unstructured organization data",
                null=True,
                verbose_name="Raw Text",
            ),
        ),
        migrations.AlterField(
            model_name="accepteddocumenttypes",
            name="journal",
            field=modelcluster.fields.ParentalKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accepted_document_types",
                to="journal.journal",
            ),
        ),
        migrations.AlterField(
            model_name="annotation",
            name="journal",
            field=modelcluster.fields.ParentalKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notes",
                to="journal.journal",
            ),
        ),
        migrations.AlterField(
            model_name="ecommittee",
            name="journal",
            field=modelcluster.fields.ParentalKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ethics_committee",
                to="journal.journal",
            ),
        ),
        migrations.AlterField(
            model_name="fileopenscience",
            name="journal",
            field=modelcluster.fields.ParentalKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="open_science_form_files",
                to="journal.journal",
            ),
        ),
        migrations.AlterField(
            model_name="journalsocialnetwork",
            name="page",
            field=modelcluster.fields.ParentalKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="social_networks",
                to="journal.journal",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="journal",
            field=modelcluster.fields.ParentalKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="peer_review",
                to="journal.journal",
            ),
        ),
        migrations.CreateModel(
            name="ArtificialIntelligence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "rich_text",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Describe the journal's policy on the use of Artificial Intelligence in the preparation, review, and publication of manuscripts.",
                        null=True,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "journal",
                    modelcluster.fields.ParentalKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="artificial_intelligence",
                        to="journal.journal",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.language",
                        verbose_name="Language",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OpenAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "rich_text",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Open access refers to the practice of making research publications freely available to the public without subscription or payment barriers. \n            This ensures that research findings are accessible to anyone with an internet connection, promoting the dissemination of knowledge and fostering collaboration and innovation.",
                        null=True,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "journal",
                    modelcluster.fields.ParentalKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="open_access_text",
                        to="journal.journal",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.language",
                        verbose_name="Language",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
