# Generated by Django 5.2.7 on 2026-02-26 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0055_journalproxyadminonly_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="JournalLogo",
        ),
    ]
