# Generated by Django 5.2.7 on 2026-02-07 22:46

from django.db import migrations
import modelcluster.fields
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0057_artificialintelligence"),
    ]

    operations = [
        # Rename related_name: journalsocialnetwork -> social_networks
        migrations.AlterField(
            model_name="journalsocialnetwork",
            name="page",
            field=modelcluster.fields.ParentalKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="social_networks",
                to="journal.journal",
            ),
        ),
        # Rename related_name: annotation -> notes
        migrations.AlterField(
            model_name="annotation",
            name="journal",
            field=modelcluster.fields.ParentalKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notes",
                to="journal.journal",
            ),
        ),
        # Rename related_name: accepted_documment_types -> accepted_document_types (fix typo)
        migrations.AlterField(
            model_name="accepteddocumenttypes",
            name="journal",
            field=modelcluster.fields.ParentalKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accepted_document_types",
                to="journal.journal",
            ),
        ),
        # Rename related_name: file_oa -> open_science_form_files
        migrations.AlterField(
            model_name="fileopenscience",
            name="journal",
            field=modelcluster.fields.ParentalKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="open_science_form_files",
                to="journal.journal",
            ),
        ),
        # Rename related_name: ecommittee -> ethics_committee
        migrations.AlterField(
            model_name="ecommittee",
            name="journal",
            field=modelcluster.fields.ParentalKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ethics_committee",
                to="journal.journal",
            ),
        ),
        # Rename related_name: review -> peer_review
        migrations.AlterField(
            model_name="review",
            name="journal",
            field=modelcluster.fields.ParentalKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="peer_review",
                to="journal.journal",
            ),
        ),
    ]
