# Generated by Django 5.2.7 on 2026-03-12 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0058_remove_journal_doi_prefix_journal_crossref_configuration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="digitalpreservationagency",
            options={
                "verbose_name": "Digital Preservation Agency",
                "verbose_name_plural": "Digital Preservation Agencies",
            },
        ),
    ]
