# Generated by Django 5.2.7 on 2026-02-08 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0058_rename_journal_inline_panel_related_names"),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalProxyAdminOnly",
            fields=[],
            options={
                "verbose_name": "Journal (Admin Only)",
                "verbose_name_plural": "Journals (Admin Only)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("journal.journal",),
        ),
    ]
