# Generated by Django 5.2.7 on 2026-05-22 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_licensestatement_options_and_more"),
        ("journal", "0059_alter_digitalpreservationagency_options"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="journalparalleltitle",
            unique_together={("official_journal", "text", "language")},
        ),
    ]
