from django.utils.translation import gettext_lazy as _

DATA_STATUS_PENDING = "PENDING"
DATA_STATUS_DELETED = "DELETED"
DATA_STATUS_MOVED = "MOVED"
DATA_STATUS_PUBLIC = "PUBLIC"
DATA_STATUS_UNDEF = "UNDEF"
DATA_STATUS_INVALID = "NVALID"
DATA_STATUS_DUPLICATED = "DUP"
DATA_STATUS_DEDUPLICATED = "DEDUP"

DATA_STATUS = (
    (DATA_STATUS_PUBLIC, _("public")),
    (DATA_STATUS_PENDING, _("pending")),
    (DATA_STATUS_MOVED, _("moved")),
    (DATA_STATUS_DELETED, _("deleted")),
    (DATA_STATUS_UNDEF, _("undefined")),
    (DATA_STATUS_INVALID, _("invalid")),
    (DATA_STATUS_DUPLICATED, _("duplicated")),
    (DATA_STATUS_DEDUPLICATED, _("deduplicated")),
)

DATA_STATUS_EXCLUSION_LIST = [
    DATA_STATUS_DELETED,
    DATA_STATUS_MOVED,
    DATA_STATUS_INVALID,
    DATA_STATUS_DUPLICATED,
]
DATA_STATUS_INCLUSION_LIST = [
    DATA_STATUS_PUBLIC,
    DATA_STATUS_PENDING,
    DATA_STATUS_UNDEF,
    DATA_STATUS_DEDUPLICATED,
]
