class XMLSPSArticleSaveError(Exception): ...


class LicenseDoesNotExist(Exception): ...


class LoadArticlePublisherNameException(Exception): ...


class LoadArticleFundingError(Exception): ...


class LoadArticleTocSectionError(Exception): ...


class LoadArticleKeywordError(Exception): ...


class LoadArticleAbstractError(Exception): ...


class LoadArticleContribError(Exception): ...


class LoadArticleCollabError(Exception): ...


class LoadArticleTitleError(Exception): ...


class LoadArticleSponsorError(Exception): ...


class LoadArticleIssueError(Exception): ...
