# Generated by Django 4.2.6 on 2023-11-13 00:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("location", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="address",
            name="location",
        ),
        migrations.RemoveField(
            model_name="address",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="region",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="region",
            name="updated_by",
        ),
        migrations.AlterModelOptions(
            name="countryname",
            options={
                "verbose_name": "Country name",
                "verbose_name_plural": "Country names",
            },
        ),
        migrations.RemoveField(
            model_name="location",
            name="region",
        ),
        migrations.RemoveField(
            model_name="state",
            name="region",
        ),
        migrations.AddIndex(
            model_name="countryname",
            index=models.Index(
                fields=["language"], name="location_co_languag_eee0e2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="countryname",
            index=models.Index(fields=["text"], name="location_co_text_b4fd37_idx"),
        ),
        migrations.DeleteModel(
            name="Address",
        ),
        migrations.DeleteModel(
            name="Region",
        ),
    ]
