# Generated by Django 5.0.8 on 2025-05-26 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={"verbose_name": "Cidade", "verbose_name_plural": "Cidades"},
        ),
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name": "País", "verbose_name_plural": "Países"},
        ),
        migrations.AlterModelOptions(
            name="countryname",
            options={
                "verbose_name": "Nome do país",
                "verbose_name_plural": "Nomes dos países",
            },
        ),
        migrations.AlterModelOptions(
            name="location",
            options={
                "verbose_name": "Localização",
                "verbose_name_plural": "Localizações",
            },
        ),
        migrations.AlterModelOptions(
            name="state",
            options={"verbose_name": "Estado", "verbose_name_plural": "Estados"},
        ),
        migrations.AlterField(
            model_name="city",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Data de criação"
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criador",
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.TextField(unique=True, verbose_name="Nome da cidade"),
        ),
        migrations.AlterField(
            model_name="city",
            name="updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Data da última atualização"
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Atualizador",
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="acron3",
            field=models.CharField(
                blank=True,
                max_length=3,
                null=True,
                verbose_name="Acrônimo do País (3 caracteres)",
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="acronym",
            field=models.CharField(
                blank=True,
                max_length=2,
                null=True,
                verbose_name="Acrônimo do País (2 caracteres)",
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Data de criação"
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criador",
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Nome do País"
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Data da última atualização"
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Atualizador",
            ),
        ),
        migrations.AlterField(
            model_name="countryfile",
            name="is_valid",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="É válido?"
            ),
        ),
        migrations.AlterField(
            model_name="countryfile",
            name="line_count",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Número de linhas"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="location.city",
                verbose_name="Cidade",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="location.country",
                verbose_name="País",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Data de criação"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criador",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="location.state",
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Data da última atualização"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Atualizador",
            ),
        ),
        migrations.AlterField(
            model_name="state",
            name="acronym",
            field=models.CharField(
                blank=True, max_length=2, null=True, verbose_name="Acrônimo do estado"
            ),
        ),
        migrations.AlterField(
            model_name="state",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Data de criação"
            ),
        ),
        migrations.AlterField(
            model_name="state",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criador",
            ),
        ),
        migrations.AlterField(
            model_name="state",
            name="name",
            field=models.TextField(
                blank=True, null=True, verbose_name="Nome do estado"
            ),
        ),
        migrations.AlterField(
            model_name="state",
            name="updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Data da última atualização"
            ),
        ),
        migrations.AlterField(
            model_name="state",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Atualizador",
            ),
        ),
    ]
