# Generated by Django 4.2.7 on 2023-12-09 22:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_gender_unique_together"),
        ("location", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="city",
            unique_together={("name",)},
        ),
        migrations.AlterUniqueTogether(
            name="countryname",
            unique_together={("country", "language")},
        ),
        migrations.AlterUniqueTogether(
            name="location",
            unique_together={("country", "state", "city")},
        ),
        migrations.AlterUniqueTogether(
            name="state",
            unique_together={("name", "acronym")},
        ),
    ]
