# Generated by Django 4.1.7 on 2023-02-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("location", "0002_alter_city_creator_alter_city_updated_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.TextField(
                default="", unique=True, verbose_name="Name of the city"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="state",
            name="acronym",
            field=models.CharField(
                blank=True, max_length=2, null=True, verbose_name="State Acronym"
            ),
        ),
        migrations.AlterField(
            model_name="state",
            name="name",
            field=models.CharField(
                default="", max_length=19, unique=True, verbose_name="State name"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="state",
            name="region",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", ""),
                    ("Norte", "Norte"),
                    ("Nordeste", "Nordeste"),
                    ("Centro-Oeste", "Centro-Oeste"),
                    ("Sudeste", "Sudeste"),
                    ("Sul", "Sul"),
                ],
                max_length=12,
                null=True,
                verbose_name="Region",
            ),
        ),
    ]
