# Generated by Django 4.1.10 on 2023-09-18 02:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("location", "0002_city_location_ci_name_673b17_idx_and_more"),
        ("location", "0002_country_acron3_countryfile"),
    ]

    operations = []
