# Generated by Django 4.1.10 on 2023-09-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("location", "0003_merge_20230918_0225"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="acron3",
            field=models.CharField(
                blank=True,
                max_length=3,
                null=True,
                verbose_name="Country Acronym (3 char)",
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="acronym",
            field=models.CharField(
                blank=True,
                max_length=2,
                null=True,
                verbose_name="Country Acronym (2 char)",
            ),
        ),
    ]
