# Generated by Django 4.1.7 on 2023-03-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "location",
            "0003_alter_city_name_alter_state_acronym_alter_state_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="state",
            name="name",
            field=models.TextField(verbose_name="State name"),
        ),
    ]
