# Generated by Django 5.2.7 on 2026-01-08 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0003_alter_city_options_alter_country_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="city",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="city",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RAW", "RAW"),
                    ("CLEANED", "CLEANED"),
                    ("MATCHED", "MATCHED"),
                    ("PROCESSED", "PROCESSED"),
                    ("OFFICIAL", "OFFICIAL"),
                    ("REJECTED", "REJECTED"),
                ],
                default="RAW",
                max_length=9,
            ),
        ),
        migrations.AddField(
            model_name="country",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RAW", "RAW"),
                    ("CLEANED", "CLEANED"),
                    ("MATCHED", "MATCHED"),
                    ("PROCESSED", "PROCESSED"),
                    ("OFFICIAL", "OFFICIAL"),
                    ("REJECTED", "REJECTED"),
                ],
                default="RAW",
                max_length=9,
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RAW", "RAW"),
                    ("CLEANED", "CLEANED"),
                    ("MATCHED", "MATCHED"),
                    ("PROCESSED", "PROCESSED"),
                    ("OFFICIAL", "OFFICIAL"),
                    ("REJECTED", "REJECTED"),
                ],
                default="RAW",
                max_length=9,
            ),
        ),
        migrations.AddField(
            model_name="state",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RAW", "RAW"),
                    ("CLEANED", "CLEANED"),
                    ("MATCHED", "MATCHED"),
                    ("PROCESSED", "PROCESSED"),
                    ("OFFICIAL", "OFFICIAL"),
                    ("REJECTED", "REJECTED"),
                ],
                default="RAW",
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="state",
            name="acronym",
            field=models.CharField(
                blank=True, max_length=3, null=True, verbose_name="State Acronym"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="city",
            unique_together={("name", "status")},
        ),
        migrations.CreateModel(
            name="CountryMatched",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        default=1.0, help_text="Confiança do match (0.0 a 1.0)"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "matched",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Variações/duplicatas que correspondem a este país oficial",
                        limit_choices_to={"status__in": ["RAW", "CLEANED"]},
                        related_name="official_match",
                        to="location.country",
                        verbose_name="Matched Countries",
                    ),
                ),
                (
                    "official",
                    models.OneToOneField(
                        help_text="País oficial verificado (do pycountry)",
                        limit_choices_to={"status": "VERIFIED"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matched_countries",
                        to="location.country",
                        verbose_name="Official Country",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
            options={
                "verbose_name": "Country Match",
                "verbose_name_plural": "Country Matches",
            },
        ),
        migrations.CreateModel(
            name="StateMatched",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        default=1.0, help_text="Confiança do match (0.0 a 1.0)"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "matched",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Variações/duplicatas que correspondem a este estado oficial",
                        limit_choices_to={"status__in": ["RAW", "CLEANED"]},
                        related_name="official_match_state",
                        to="location.state",
                        verbose_name="Matched States",
                    ),
                ),
                (
                    "official",
                    models.OneToOneField(
                        help_text="Estado oficial verificado",
                        limit_choices_to={"status": "OFFICIAL"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matched_states",
                        to="location.state",
                        verbose_name="Official State",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
            options={
                "verbose_name": "State Match",
                "verbose_name_plural": "State Matches",
            },
        ),
    ]
