# Generated by Django 4.1.10 on 2023-09-19 02:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("location", "0004_alter_country_acron3_alter_country_acronym"),
    ]

    operations = [
        migrations.AlterField(
            model_name="state",
            name="name",
            field=models.TextField(blank=True, null=True, verbose_name="State name"),
        ),
    ]
