# Generated by Django 4.1.10 on 2023-09-20 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("location", "0006_address_address_location_ad_name_5128b2_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="location.address",
                verbose_name="Address",
            ),
        ),
    ]
