# Generated by Django 4.1.10 on 2023-10-12 01:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("location", "0003_merge_20230923_1955"),
        ("location", "0007_location_address"),
    ]

    operations = []
