# Generated by Django 4.2.6 on 2023-10-17 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("location", "0008_merge_0003_merge_20230923_1955_0007_location_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="address",
        ),
        migrations.AddField(
            model_name="address",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="location.location",
                verbose_name="Address",
            ),
        ),
    ]
