exclude: "^docs/|/migrations/"
default_stages: [push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        stages: [commit]
      - id: end-of-file-fixer

  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: ["--profile", "black"]   # garante compatibilidade com Black
        stages: [push]

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        stages: [push]

ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
