version: '3'

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: core_production_django
    platform: linux/x86_64
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  pgbouncer:
    image: edoburu/pgbouncer:1.14.0
    restart: always
    environment:
      - DATABASE_URL=postgres://GVRFlLmcCNfGLhsFvSnCioYOPJPYpyfj:DAkWfpsnPHcAxMeQk2QmPOIZuz4BXG5qGFWi2hCCQE6kvndJHTuzz8SjnxOJY5qj@postgres/core
      - MAX_CLIENT_CONN=100
    ports:
      - 6434:5432
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: core_production_postgres
    volumes:
      - ../scms_data/template/data_prod:/var/lib/postgresql/data:Z
      - ../scms_data/template/data_prod_backup:/backups:z
    env_file:
      - ./.envs/.production/.postgres

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: core_production_traefik
    depends_on:
      - django
    volumes:
      - ../scms_data/template/traefik:/etc/traefik/acme:z
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      - "0.0.0.0:5555:5555"

  redis:
    image: redis:6

  celeryworker:
    <<: *django
    image: core_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: core_production_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: core_production_flower
    command: /start-flower
