# Generated by Django 5.0.8 on 2025-03-31 14:16

import django.db.models.deletion
import modelcluster.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("location", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationInstitutionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        blank=True,
                        null=True,
                        unique=True,
                        verbose_name="Institution Type",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrganizationCopyrightHolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                ("name", models.TextField(blank=True, null=True, verbose_name="Nome")),
                (
                    "acronym",
                    models.TextField(
                        blank=True, null=True, verbose_name="Institution Acronym"
                    ),
                ),
                ("url", models.URLField(blank=True, null=True, verbose_name="url")),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="Logo"
                    ),
                ),
                (
                    "institution_type_mec",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", ""),
                            (
                                "agência de apoio à pesquisa",
                                "agência de apoio à pesquisa",
                            ),
                            (
                                "universidade e instâncias ligadas à universidades",
                                "universidade e instâncias ligadas à universidades",
                            ),
                            (
                                "empresa ou instituto ligadas ao governo",
                                "empresa ou instituto ligadas ao governo",
                            ),
                            ("organização privada", "organização privada"),
                            (
                                "organização sem fins de lucros",
                                "organização sem fins de lucros",
                            ),
                            (
                                "sociedade científica, associação pós-graduação, associação profissional",
                                "sociedade científica, associação pós-graduação, associação profissional",
                            ),
                            ("outros", "outros"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Institution Type (MEC)",
                    ),
                ),
                (
                    "is_official",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Is official"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="location.location",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
                (
                    "institution_type_scielo",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        to="organization.organizationinstitutiontype",
                        verbose_name="Institution Type (SciELO)",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrganizationAffiliation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                ("name", models.TextField(blank=True, null=True, verbose_name="Nome")),
                (
                    "acronym",
                    models.TextField(
                        blank=True, null=True, verbose_name="Institution Acronym"
                    ),
                ),
                ("url", models.URLField(blank=True, null=True, verbose_name="url")),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="Logo"
                    ),
                ),
                (
                    "institution_type_mec",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", ""),
                            (
                                "agência de apoio à pesquisa",
                                "agência de apoio à pesquisa",
                            ),
                            (
                                "universidade e instâncias ligadas à universidades",
                                "universidade e instâncias ligadas à universidades",
                            ),
                            (
                                "empresa ou instituto ligadas ao governo",
                                "empresa ou instituto ligadas ao governo",
                            ),
                            ("organização privada", "organização privada"),
                            (
                                "organização sem fins de lucros",
                                "organização sem fins de lucros",
                            ),
                            (
                                "sociedade científica, associação pós-graduação, associação profissional",
                                "sociedade científica, associação pós-graduação, associação profissional",
                            ),
                            ("outros", "outros"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Institution Type (MEC)",
                    ),
                ),
                (
                    "is_official",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Is official"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="location.location",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
                (
                    "institution_type_scielo",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        to="organization.organizationinstitutiontype",
                        verbose_name="Institution Type (SciELO)",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrganizationOwner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                ("name", models.TextField(blank=True, null=True, verbose_name="Nome")),
                (
                    "acronym",
                    models.TextField(
                        blank=True, null=True, verbose_name="Institution Acronym"
                    ),
                ),
                ("url", models.URLField(blank=True, null=True, verbose_name="url")),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="Logo"
                    ),
                ),
                (
                    "institution_type_mec",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", ""),
                            (
                                "agência de apoio à pesquisa",
                                "agência de apoio à pesquisa",
                            ),
                            (
                                "universidade e instâncias ligadas à universidades",
                                "universidade e instâncias ligadas à universidades",
                            ),
                            (
                                "empresa ou instituto ligadas ao governo",
                                "empresa ou instituto ligadas ao governo",
                            ),
                            ("organização privada", "organização privada"),
                            (
                                "organização sem fins de lucros",
                                "organização sem fins de lucros",
                            ),
                            (
                                "sociedade científica, associação pós-graduação, associação profissional",
                                "sociedade científica, associação pós-graduação, associação profissional",
                            ),
                            ("outros", "outros"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Institution Type (MEC)",
                    ),
                ),
                (
                    "is_official",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Is official"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "institution_type_scielo",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        to="organization.organizationinstitutiontype",
                        verbose_name="Institution Type (SciELO)",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="location.location",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrganizationPublisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                ("name", models.TextField(blank=True, null=True, verbose_name="Nome")),
                (
                    "acronym",
                    models.TextField(
                        blank=True, null=True, verbose_name="Institution Acronym"
                    ),
                ),
                ("url", models.URLField(blank=True, null=True, verbose_name="url")),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="Logo"
                    ),
                ),
                (
                    "institution_type_mec",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", ""),
                            (
                                "agência de apoio à pesquisa",
                                "agência de apoio à pesquisa",
                            ),
                            (
                                "universidade e instâncias ligadas à universidades",
                                "universidade e instâncias ligadas à universidades",
                            ),
                            (
                                "empresa ou instituto ligadas ao governo",
                                "empresa ou instituto ligadas ao governo",
                            ),
                            ("organização privada", "organização privada"),
                            (
                                "organização sem fins de lucros",
                                "organização sem fins de lucros",
                            ),
                            (
                                "sociedade científica, associação pós-graduação, associação profissional",
                                "sociedade científica, associação pós-graduação, associação profissional",
                            ),
                            ("outros", "outros"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Institution Type (MEC)",
                    ),
                ),
                (
                    "is_official",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Is official"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "institution_type_scielo",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        to="organization.organizationinstitutiontype",
                        verbose_name="Institution Type (SciELO)",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="location.location",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrganizationSponsor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                ("name", models.TextField(blank=True, null=True, verbose_name="Nome")),
                (
                    "acronym",
                    models.TextField(
                        blank=True, null=True, verbose_name="Institution Acronym"
                    ),
                ),
                ("url", models.URLField(blank=True, null=True, verbose_name="url")),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="Logo"
                    ),
                ),
                (
                    "institution_type_mec",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", ""),
                            (
                                "agência de apoio à pesquisa",
                                "agência de apoio à pesquisa",
                            ),
                            (
                                "universidade e instâncias ligadas à universidades",
                                "universidade e instâncias ligadas à universidades",
                            ),
                            (
                                "empresa ou instituto ligadas ao governo",
                                "empresa ou instituto ligadas ao governo",
                            ),
                            ("organização privada", "organização privada"),
                            (
                                "organização sem fins de lucros",
                                "organização sem fins de lucros",
                            ),
                            (
                                "sociedade científica, associação pós-graduação, associação profissional",
                                "sociedade científica, associação pós-graduação, associação profissional",
                            ),
                            ("outros", "outros"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Institution Type (MEC)",
                    ),
                ),
                (
                    "is_official",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Is official"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "institution_type_scielo",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        to="organization.organizationinstitutiontype",
                        verbose_name="Institution Type (SciELO)",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="location.location",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrgLevelOrganizationCopyrightHolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "level_1",
                    models.TextField(
                        blank=True, null=True, verbose_name="Organization Level 1"
                    ),
                ),
                (
                    "level_2",
                    models.TextField(
                        blank=True, null=True, verbose_name="Organization Level 2"
                    ),
                ),
                (
                    "level_3",
                    models.TextField(
                        blank=True, null=True, verbose_name="Organization Level 3"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "organization",
                    modelcluster.fields.ParentalKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="org_level",
                        to="organization.organizationcopyrightholder",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrgLevelOrganizationOwner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "level_1",
                    models.TextField(
                        blank=True, null=True, verbose_name="Organization Level 1"
                    ),
                ),
                (
                    "level_2",
                    models.TextField(
                        blank=True, null=True, verbose_name="Organization Level 2"
                    ),
                ),
                (
                    "level_3",
                    models.TextField(
                        blank=True, null=True, verbose_name="Organization Level 3"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "organization",
                    modelcluster.fields.ParentalKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="org_level",
                        to="organization.organizationowner",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrgLevelOrganizationPublisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "level_1",
                    models.TextField(
                        blank=True, null=True, verbose_name="Organization Level 1"
                    ),
                ),
                (
                    "level_2",
                    models.TextField(
                        blank=True, null=True, verbose_name="Organization Level 2"
                    ),
                ),
                (
                    "level_3",
                    models.TextField(
                        blank=True, null=True, verbose_name="Organization Level 3"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "organization",
                    modelcluster.fields.ParentalKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="org_level",
                        to="organization.organizationpublisher",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrgLevelOrganizationSponsor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "level_1",
                    models.TextField(
                        blank=True, null=True, verbose_name="Organization Level 1"
                    ),
                ),
                (
                    "level_2",
                    models.TextField(
                        blank=True, null=True, verbose_name="Organization Level 2"
                    ),
                ),
                (
                    "level_3",
                    models.TextField(
                        blank=True, null=True, verbose_name="Organization Level 3"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "organization",
                    modelcluster.fields.ParentalKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="org_level",
                        to="organization.organizationsponsor",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="organizationcopyrightholder",
            index=models.Index(fields=["name"], name="organizatio_name_28d34f_idx"),
        ),
        migrations.AddIndex(
            model_name="organizationcopyrightholder",
            index=models.Index(
                fields=["acronym"], name="organizatio_acronym_893d22_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationcopyrightholder",
            index=models.Index(
                fields=["is_official"], name="organizatio_is_offi_d59182_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="organizationcopyrightholder",
            unique_together={("name", "acronym", "location")},
        ),
        migrations.AddIndex(
            model_name="organizationaffiliation",
            index=models.Index(fields=["name"], name="organizatio_name_7aff91_idx"),
        ),
        migrations.AddIndex(
            model_name="organizationaffiliation",
            index=models.Index(
                fields=["acronym"], name="organizatio_acronym_17c45f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationaffiliation",
            index=models.Index(
                fields=["is_official"], name="organizatio_is_offi_3f08bd_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="organizationaffiliation",
            unique_together={("name", "acronym", "location")},
        ),
        migrations.AddIndex(
            model_name="organizationowner",
            index=models.Index(fields=["name"], name="organizatio_name_fee22d_idx"),
        ),
        migrations.AddIndex(
            model_name="organizationowner",
            index=models.Index(
                fields=["acronym"], name="organizatio_acronym_02bd1d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationowner",
            index=models.Index(
                fields=["is_official"], name="organizatio_is_offi_1727a7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="organizationowner",
            unique_together={("name", "acronym", "location")},
        ),
        migrations.AddIndex(
            model_name="organizationpublisher",
            index=models.Index(fields=["name"], name="organizatio_name_c1534a_idx"),
        ),
        migrations.AddIndex(
            model_name="organizationpublisher",
            index=models.Index(
                fields=["acronym"], name="organizatio_acronym_0a9495_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationpublisher",
            index=models.Index(
                fields=["is_official"], name="organizatio_is_offi_0601aa_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="organizationpublisher",
            unique_together={("name", "acronym", "location")},
        ),
        migrations.AddIndex(
            model_name="organizationsponsor",
            index=models.Index(fields=["name"], name="organizatio_name_10e0d3_idx"),
        ),
        migrations.AddIndex(
            model_name="organizationsponsor",
            index=models.Index(
                fields=["acronym"], name="organizatio_acronym_ef28c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationsponsor",
            index=models.Index(
                fields=["is_official"], name="organizatio_is_offi_8f3ebc_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="organizationsponsor",
            unique_together={("name", "acronym", "location")},
        ),
    ]
