# Generated by Django 5.0.8 on 2025-04-10 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("location", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationInstitutionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        blank=True,
                        null=True,
                        unique=True,
                        verbose_name="Institution Type",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                ("name", models.TextField(blank=True, null=True, verbose_name="Nome")),
                (
                    "acronym",
                    models.TextField(
                        blank=True, null=True, verbose_name="Institution Acronym"
                    ),
                ),
                ("url", models.URLField(blank=True, null=True, verbose_name="url")),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="Logo"
                    ),
                ),
                (
                    "institution_type_mec",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", ""),
                            (
                                "agência de apoio à pesquisa",
                                "agência de apoio à pesquisa",
                            ),
                            (
                                "universidade e instâncias ligadas à universidades",
                                "universidade e instâncias ligadas à universidades",
                            ),
                            (
                                "empresa ou instituto ligadas ao governo",
                                "empresa ou instituto ligadas ao governo",
                            ),
                            ("organização privada", "organização privada"),
                            (
                                "organização sem fins de lucros",
                                "organização sem fins de lucros",
                            ),
                            (
                                "sociedade científica, associação pós-graduação, associação profissional",
                                "sociedade científica, associação pós-graduação, associação profissional",
                            ),
                            ("outros", "outros"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Institution Type (MEC)",
                    ),
                ),
                (
                    "is_official",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Is official"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="location.location",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
                (
                    "institution_type_scielo",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        to="organization.organizationinstitutiontype",
                        verbose_name="Institution Type (SciELO)",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(fields=["name"], name="organizatio_name_2d216c_idx"),
                    models.Index(
                        fields=["acronym"], name="organizatio_acronym_546868_idx"
                    ),
                    models.Index(
                        fields=["is_official"], name="organizatio_is_offi_538fd2_idx"
                    ),
                ],
                "unique_together": {("name", "acronym", "location")},
            },
        ),
    ]
