# Generated by Django 5.0.8 on 2025-04-29 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0001_initial"),
        (
            "organization",
            "0002_orglevelcopyrightholderhistory_orglevelownerhistory_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="location.location"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.TextField(verbose_name="Nome"),
        ),
    ]
