# Generated by Django 5.0.8 on 2025-05-19 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0001_initial"),
        (
            "organization",
            "0002_orglevelcopyrightholderhistory_orglevelownerhistory_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="acronym",
            field=models.TextField(null=True, verbose_name="Institution Acronym"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="location.location",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.TextField(null=True, verbose_name="Nome"),
        ),
    ]
