# Generated by Django 5.0.8 on 2025-05-20 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0003_alter_organization_acronym_and_more"),
        ("organization", "0003_alter_organization_location_alter_organization_name"),
    ]

    operations = []
