# Generated by Django 5.0.8 on 2025-05-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0004_merge_20250520_1740"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="acronym",
            field=models.TextField(
                blank=True, null=True, verbose_name="Institution Acronym"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.TextField(verbose_name="Nome"),
        ),
    ]
