# Generated by Django 5.0.8 on 2025-05-26 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0005_alter_organization_acronym_alter_organization_name"),
        ("organization", "0005_alter_organization_acronym_and_more"),
    ]

    operations = []
