# Generated by Django 5.0.8 on 2025-05-26 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0006_merge_20250526_1846"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="acronym",
            field=models.TextField(
                blank=True, null=True, verbose_name="Acrônimo da Instituição"
            ),
        ),
    ]
