# Generated by Django 5.2.3 on 2025-08-04 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0007_alter_organization_acronym"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="organization",
            name="organizatio_is_offi_538fd2_idx",
        ),
        migrations.AlterField(
            model_name="organization",
            name="institution_type_scielo",
            field=models.ManyToManyField(
                blank=True,
                to="organization.organizationinstitutiontype",
                verbose_name="Tipo de Instituição (SciELO)",
            ),
        ),
    ]
