# Generated by Django 5.2.3 on 2025-09-01 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "organization",
            "0008_remove_organization_organizatio_is_offi_538fd2_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="acronym",
            field=models.TextField(
                blank=True, null=True, verbose_name="Acronismo de Institución"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creation date"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="institution_type_mec",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", ""),
                    ("agência de apoio à pesquisa", "agência de apoio à pesquisa"),
                    (
                        "universidade e instâncias ligadas à universidades",
                        "universidade e instâncias ligadas à universidades",
                    ),
                    (
                        "empresa ou instituto ligadas ao governo",
                        "empresa ou instituto ligadas ao governo",
                    ),
                    ("organização privada", "organização privada"),
                    (
                        "organização sem fins de lucros",
                        "organização sem fins de lucros",
                    ),
                    (
                        "sociedade científica, associação pós-graduação, associação profissional",
                        "sociedade científica, associação pós-graduação, associação profissional",
                    ),
                    ("outros", "outros"),
                ],
                max_length=100,
                null=True,
                verbose_name="Tipo de Institución (MEC)",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="institution_type_scielo",
            field=models.ManyToManyField(
                blank=True,
                to="organization.organizationinstitutiontype",
                verbose_name="Tipo de Institución (SciELO)",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="is_official",
            field=models.BooleanField(blank=True, null=True, verbose_name="Es oficial"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.TextField(verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Last update date"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updater",
            ),
        ),
        migrations.AlterField(
            model_name="organizationinstitutiontype",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creation date"),
        ),
        migrations.AlterField(
            model_name="organizationinstitutiontype",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AlterField(
            model_name="organizationinstitutiontype",
            name="name",
            field=models.TextField(
                blank=True, null=True, unique=True, verbose_name="Tipo de Institución"
            ),
        ),
        migrations.AlterField(
            model_name="organizationinstitutiontype",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Last update date"),
        ),
        migrations.AlterField(
            model_name="organizationinstitutiontype",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updater",
            ),
        ),
        migrations.AlterField(
            model_name="orglevelcopyrightholderhistory",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creation date"),
        ),
        migrations.AlterField(
            model_name="orglevelcopyrightholderhistory",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AlterField(
            model_name="orglevelcopyrightholderhistory",
            name="level_1",
            field=models.TextField(
                blank=True, null=True, verbose_name="Nivel de Organización 1"
            ),
        ),
        migrations.AlterField(
            model_name="orglevelcopyrightholderhistory",
            name="level_2",
            field=models.TextField(
                blank=True, null=True, verbose_name="Nivel de Organización 2"
            ),
        ),
        migrations.AlterField(
            model_name="orglevelcopyrightholderhistory",
            name="level_3",
            field=models.TextField(
                blank=True, null=True, verbose_name="Nivel de Organización 3"
            ),
        ),
        migrations.AlterField(
            model_name="orglevelcopyrightholderhistory",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Last update date"),
        ),
        migrations.AlterField(
            model_name="orglevelcopyrightholderhistory",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updater",
            ),
        ),
        migrations.AlterField(
            model_name="orglevelownerhistory",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creation date"),
        ),
        migrations.AlterField(
            model_name="orglevelownerhistory",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AlterField(
            model_name="orglevelownerhistory",
            name="level_1",
            field=models.TextField(
                blank=True, null=True, verbose_name="Nivel de Organización 1"
            ),
        ),
        migrations.AlterField(
            model_name="orglevelownerhistory",
            name="level_2",
            field=models.TextField(
                blank=True, null=True, verbose_name="Nivel de Organización 2"
            ),
        ),
        migrations.AlterField(
            model_name="orglevelownerhistory",
            name="level_3",
            field=models.TextField(
                blank=True, null=True, verbose_name="Nivel de Organización 3"
            ),
        ),
        migrations.AlterField(
            model_name="orglevelownerhistory",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Last update date"),
        ),
        migrations.AlterField(
            model_name="orglevelownerhistory",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updater",
            ),
        ),
        migrations.AlterField(
            model_name="orglevelpublisherhistory",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creation date"),
        ),
        migrations.AlterField(
            model_name="orglevelpublisherhistory",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AlterField(
            model_name="orglevelpublisherhistory",
            name="level_1",
            field=models.TextField(
                blank=True, null=True, verbose_name="Nivel de Organización 1"
            ),
        ),
        migrations.AlterField(
            model_name="orglevelpublisherhistory",
            name="level_2",
            field=models.TextField(
                blank=True, null=True, verbose_name="Nivel de Organización 2"
            ),
        ),
        migrations.AlterField(
            model_name="orglevelpublisherhistory",
            name="level_3",
            field=models.TextField(
                blank=True, null=True, verbose_name="Nivel de Organización 3"
            ),
        ),
        migrations.AlterField(
            model_name="orglevelpublisherhistory",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Last update date"),
        ),
        migrations.AlterField(
            model_name="orglevelpublisherhistory",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updater",
            ),
        ),
        migrations.AlterField(
            model_name="orglevelsponsorhistory",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creation date"),
        ),
        migrations.AlterField(
            model_name="orglevelsponsorhistory",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AlterField(
            model_name="orglevelsponsorhistory",
            name="level_1",
            field=models.TextField(
                blank=True, null=True, verbose_name="Nivel de Organización 1"
            ),
        ),
        migrations.AlterField(
            model_name="orglevelsponsorhistory",
            name="level_2",
            field=models.TextField(
                blank=True, null=True, verbose_name="Nivel de Organización 2"
            ),
        ),
        migrations.AlterField(
            model_name="orglevelsponsorhistory",
            name="level_3",
            field=models.TextField(
                blank=True, null=True, verbose_name="Nivel de Organización 3"
            ),
        ),
        migrations.AlterField(
            model_name="orglevelsponsorhistory",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Last update date"),
        ),
        migrations.AlterField(
            model_name="orglevelsponsorhistory",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updater",
            ),
        ),
    ]
