# Generated by Django 5.2.3 on 2025-09-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0009_alter_organization_acronym_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="acronym",
            field=models.TextField(
                blank=True, null=True, verbose_name="Institution Acronym"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="institution_type_mec",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", ""),
                    ("agência de apoio à pesquisa", "agência de apoio à pesquisa"),
                    (
                        "universidade e instâncias ligadas à universidades",
                        "universidade e instâncias ligadas à universidades",
                    ),
                    (
                        "empresa ou instituto ligadas ao governo",
                        "empresa ou instituto ligadas ao governo",
                    ),
                    ("organização privada", "organização privada"),
                    (
                        "organização sem fins de lucros",
                        "organização sem fins de lucros",
                    ),
                    (
                        "sociedade científica, associação pós-graduação, associação profissional",
                        "sociedade científica, associação pós-graduação, associação profissional",
                    ),
                    ("outros", "outros"),
                ],
                max_length=100,
                null=True,
                verbose_name="Institution Type (MEC)",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="institution_type_scielo",
            field=models.ManyToManyField(
                blank=True,
                to="organization.organizationinstitutiontype",
                verbose_name="Institution Type (SciELO)",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="is_official",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Is official"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Logo"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.TextField(verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="organizationinstitutiontype",
            name="name",
            field=models.TextField(
                blank=True, null=True, unique=True, verbose_name="Institution Type"
            ),
        ),
        migrations.AlterField(
            model_name="orglevelcopyrightholderhistory",
            name="level_1",
            field=models.TextField(
                blank=True, null=True, verbose_name="Organization Level 1"
            ),
        ),
        migrations.AlterField(
            model_name="orglevelcopyrightholderhistory",
            name="level_2",
            field=models.TextField(
                blank=True, null=True, verbose_name="Organization Level 2"
            ),
        ),
        migrations.AlterField(
            model_name="orglevelcopyrightholderhistory",
            name="level_3",
            field=models.TextField(
                blank=True, null=True, verbose_name="Organization Level 3"
            ),
        ),
        migrations.AlterField(
            model_name="orglevelownerhistory",
            name="level_1",
            field=models.TextField(
                blank=True, null=True, verbose_name="Organization Level 1"
            ),
        ),
        migrations.AlterField(
            model_name="orglevelownerhistory",
            name="level_2",
            field=models.TextField(
                blank=True, null=True, verbose_name="Organization Level 2"
            ),
        ),
        migrations.AlterField(
            model_name="orglevelownerhistory",
            name="level_3",
            field=models.TextField(
                blank=True, null=True, verbose_name="Organization Level 3"
            ),
        ),
        migrations.AlterField(
            model_name="orglevelpublisherhistory",
            name="level_1",
            field=models.TextField(
                blank=True, null=True, verbose_name="Organization Level 1"
            ),
        ),
        migrations.AlterField(
            model_name="orglevelpublisherhistory",
            name="level_2",
            field=models.TextField(
                blank=True, null=True, verbose_name="Organization Level 2"
            ),
        ),
        migrations.AlterField(
            model_name="orglevelpublisherhistory",
            name="level_3",
            field=models.TextField(
                blank=True, null=True, verbose_name="Organization Level 3"
            ),
        ),
        migrations.AlterField(
            model_name="orglevelsponsorhistory",
            name="level_1",
            field=models.TextField(
                blank=True, null=True, verbose_name="Organization Level 1"
            ),
        ),
        migrations.AlterField(
            model_name="orglevelsponsorhistory",
            name="level_2",
            field=models.TextField(
                blank=True, null=True, verbose_name="Organization Level 2"
            ),
        ),
        migrations.AlterField(
            model_name="orglevelsponsorhistory",
            name="level_3",
            field=models.TextField(
                blank=True, null=True, verbose_name="Organization Level 3"
            ),
        ),
    ]
