# Generated by Django 5.2.7 on 2026-02-24 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0003_alter_city_options_alter_country_options_and_more"),
        ("organization", "0010_alter_organization_acronym_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NormAffiliation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "level_1",
                    models.CharField(
                        blank=True,
                        help_text="First level of organization division",
                        max_length=255,
                        null=True,
                        verbose_name="Level 1",
                    ),
                ),
                (
                    "level_2",
                    models.CharField(
                        blank=True,
                        help_text="Second level of organization division",
                        max_length=255,
                        null=True,
                        verbose_name="Level 2",
                    ),
                ),
                (
                    "level_3",
                    models.CharField(
                        blank=True,
                        help_text="Third level of organization division",
                        max_length=255,
                        null=True,
                        verbose_name="Level 3",
                    ),
                ),
            ],
        ),
        migrations.RemoveIndex(
            model_name="organization",
            name="organizatio_name_2d216c_idx",
        ),
        migrations.RemoveIndex(
            model_name="organization",
            name="organizatio_acronym_546868_idx",
        ),
        migrations.AlterField(
            model_name="organization",
            name="acronym",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Institution Acronym"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="organizationinstitutiontype",
            name="name",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Institution Type",
            ),
        ),
        migrations.AlterField(
            model_name="orglevelcopyrightholderhistory",
            name="level_1",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Organization Level 1",
            ),
        ),
        migrations.AlterField(
            model_name="orglevelcopyrightholderhistory",
            name="level_2",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Organization Level 2",
            ),
        ),
        migrations.AlterField(
            model_name="orglevelcopyrightholderhistory",
            name="level_3",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Organization Level 3",
            ),
        ),
        migrations.AlterField(
            model_name="orglevelownerhistory",
            name="level_1",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Organization Level 1",
            ),
        ),
        migrations.AlterField(
            model_name="orglevelownerhistory",
            name="level_2",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Organization Level 2",
            ),
        ),
        migrations.AlterField(
            model_name="orglevelownerhistory",
            name="level_3",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Organization Level 3",
            ),
        ),
        migrations.AlterField(
            model_name="orglevelpublisherhistory",
            name="level_1",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Organization Level 1",
            ),
        ),
        migrations.AlterField(
            model_name="orglevelpublisherhistory",
            name="level_2",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Organization Level 2",
            ),
        ),
        migrations.AlterField(
            model_name="orglevelpublisherhistory",
            name="level_3",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Organization Level 3",
            ),
        ),
        migrations.AlterField(
            model_name="orglevelsponsorhistory",
            name="level_1",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Organization Level 1",
            ),
        ),
        migrations.AlterField(
            model_name="orglevelsponsorhistory",
            name="level_2",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Organization Level 2",
            ),
        ),
        migrations.AlterField(
            model_name="orglevelsponsorhistory",
            name="level_3",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Organization Level 3",
            ),
        ),
        migrations.AddField(
            model_name="normaffiliation",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AddField(
            model_name="normaffiliation",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="Standardized location reference",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="location.location",
                verbose_name="Location",
            ),
        ),
        migrations.AddField(
            model_name="normaffiliation",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Standardized organization reference",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="organization.organization",
                verbose_name="Organization",
            ),
        ),
        migrations.AddField(
            model_name="normaffiliation",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updater",
            ),
        ),
        migrations.AddIndex(
            model_name="normaffiliation",
            index=models.Index(
                fields=["organization"], name="organizatio_organiz_3ad0fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="normaffiliation",
            index=models.Index(
                fields=["location"], name="organizatio_locatio_b9a6c8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="normaffiliation",
            unique_together={
                ("organization", "location", "level_1", "level_2", "level_3")
            },
        ),
    ]
