# Generated by Django 5.2.7 on 2026-02-02 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0003_alter_city_options_alter_country_options_and_more"),
        ("organization", "0010_alter_organization_acronym_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationalLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "level_1",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Faculty, School, Institute",
                        max_length=255,
                        null=True,
                        verbose_name="Level 1",
                    ),
                ),
                (
                    "level_2",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Department, Division",
                        max_length=255,
                        null=True,
                        verbose_name="Level 2",
                    ),
                ),
                (
                    "level_3",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Laboratory, Graduate Program",
                        max_length=255,
                        null=True,
                        verbose_name="Level 3",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organizational Level",
                "verbose_name_plural": "Organizational Levels",
            },
        ),
        migrations.CreateModel(
            name="RawOrganization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the organization",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "acronym",
                    models.CharField(
                        blank=True,
                        help_text="Acronym (e.g., USP, FIOCRUZ)",
                        max_length=50,
                        null=True,
                        verbose_name="Acronym",
                    ),
                ),
                (
                    "level_1",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Faculty, School, Institute",
                        max_length=255,
                        null=True,
                        verbose_name="Level 1",
                    ),
                ),
                (
                    "level_2",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Department, Division",
                        max_length=255,
                        null=True,
                        verbose_name="Level 2",
                    ),
                ),
                (
                    "level_3",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Laboratory, Graduate Program",
                        max_length=255,
                        null=True,
                        verbose_name="Level 3",
                    ),
                ),
                (
                    "original",
                    models.CharField(
                        blank=True,
                        help_text="Original text",
                        max_length=300,
                        null=True,
                        verbose_name="Original",
                    ),
                ),
                (
                    "normalized_name",
                    models.CharField(
                        blank=True,
                        help_text="Normalized name",
                        max_length=255,
                        null=True,
                        verbose_name="Normalized name",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        help_text="Country as received (e.g., 'Brasil', 'Brazil', 'BR')",
                        max_length=100,
                        null=True,
                        verbose_name="Country",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        help_text="State/province as received",
                        max_length=100,
                        null=True,
                        verbose_name="State",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        help_text="City as received",
                        max_length=100,
                        null=True,
                        verbose_name="City",
                    ),
                ),
                (
                    "match_status",
                    models.CharField(
                        choices=[
                            ("unmatched", "Unmatched"),
                            ("auto", "Auto-matched"),
                            ("manual", "Manually matched"),
                        ],
                        default="unmatched",
                        help_text="Status of link to Organization",
                        max_length=20,
                        verbose_name="Match Status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Raw Organization",
                "verbose_name_plural": "Raw Organizations",
            },
        ),
        migrations.AlterModelOptions(
            name="organization",
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
            },
        ),
        migrations.AlterModelOptions(
            name="organizationinstitutiontype",
            options={
                "verbose_name": "Institution Type",
                "verbose_name_plural": "Institution Types",
            },
        ),
        migrations.RemoveIndex(
            model_name="organization",
            name="organizatio_acronym_546868_idx",
        ),
        migrations.AlterUniqueTogether(
            name="organization",
            unique_together={("name", "location", "external_id", "source")},
        ),
        migrations.AddField(
            model_name="organization",
            name="external_id",
            field=models.CharField(
                blank=True,
                help_text="Identifier from external system (e.g., ROR ID)",
                max_length=300,
                null=True,
                verbose_name="External ID",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="institution_type",
            field=models.ManyToManyField(
                blank=True,
                help_text="Types of institution (university, hospital, etc.)",
                related_name="organizations",
                to="organization.organizationinstitutiontype",
                verbose_name="Institution Type",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("user", "user"),
                    ("legacy", "legacy"),
                    ("MEC", "Ministério da Educação e Cultura"),
                    ("ror", "Research Organization Registry"),
                ],
                default="user",
                help_text="Data source (ror, isni, manual, etc.)",
                max_length=50,
                null=True,
                verbose_name="Source",
            ),
        ),
        migrations.AddField(
            model_name="organizationinstitutiontype",
            name="source",
            field=models.CharField(
                blank=True,
                default="unknown",
                help_text="Authority that defined this type (e.g., scielo, mec, scimago)",
                max_length=50,
                null=True,
                verbose_name="Source",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="acronym",
            field=models.CharField(
                blank=True,
                help_text="Acronym (e.g., USP, FIOCRUZ)",
                max_length=50,
                null=True,
                verbose_name="Acronym",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="Location (country, state, city)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="location.location",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="organizations/logos/",
                verbose_name="Logo",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.CharField(
                help_text="Name of the organization",
                max_length=255,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="url",
            field=models.URLField(
                blank=True, help_text="Official website", null=True, verbose_name="URL"
            ),
        ),
        migrations.AlterField(
            model_name="organizationinstitutiontype",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Name of the institution type as defined by the authority",
                max_length=255,
                null=True,
                verbose_name="Institution Type",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="organizationinstitutiontype",
            unique_together={("name", "source")},
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["source"], name="organizatio_source_89543c_idx"),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["external_id"], name="organizatio_externa_8d4226_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationinstitutiontype",
            index=models.Index(fields=["name"], name="organizatio_name_26b88e_idx"),
        ),
        migrations.AddIndex(
            model_name="organizationinstitutiontype",
            index=models.Index(fields=["source"], name="organizatio_source_3e6f62_idx"),
        ),
        migrations.AddField(
            model_name="organizationallevel",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AddField(
            model_name="organizationallevel",
            name="organization",
            field=models.ForeignKey(
                help_text="Parent organization (required)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organizational_levels",
                to="organization.organization",
            ),
        ),
        migrations.AddField(
            model_name="organizationallevel",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updater",
            ),
        ),
        migrations.AddField(
            model_name="raworganization",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AddField(
            model_name="raworganization",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Standardized organization (after normalization)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="raw_organizations",
                to="organization.organization",
                verbose_name="Organization",
            ),
        ),
        migrations.AddField(
            model_name="raworganization",
            name="organizational_level",
            field=models.ForeignKey(
                blank=True,
                help_text="Standardized levels (requires organization)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="raw_organization_levels",
                to="organization.organizationallevel",
                verbose_name="Organizational Level",
            ),
        ),
        migrations.AddField(
            model_name="raworganization",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updater",
            ),
        ),
        migrations.RemoveField(
            model_name="organization",
            name="institution_type_mec",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="institution_type_scielo",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="is_official",
        ),
        migrations.AddIndex(
            model_name="organizationallevel",
            index=models.Index(
                fields=["level_1"], name="organizatio_level_1_52c0fe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationallevel",
            index=models.Index(
                fields=["level_2"], name="organizatio_level_2_20a00b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationallevel",
            index=models.Index(
                fields=["level_3"], name="organizatio_level_3_92408c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="organizationallevel",
            unique_together={("organization", "level_1", "level_2", "level_3")},
        ),
        migrations.AddIndex(
            model_name="raworganization",
            index=models.Index(
                fields=["original"], name="organizatio_origina_2d699b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="raworganization",
            index=models.Index(
                fields=["country"], name="organizatio_country_155e76_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="raworganization",
            index=models.Index(fields=["state"], name="organizatio_state_c384b8_idx"),
        ),
        migrations.AddIndex(
            model_name="raworganization",
            index=models.Index(fields=["city"], name="organizatio_city_1511dc_idx"),
        ),
        migrations.AddIndex(
            model_name="raworganization",
            index=models.Index(
                fields=["level_1"], name="organizatio_level_1_6365d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="raworganization",
            index=models.Index(
                fields=["level_2"], name="organizatio_level_2_567f1f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="raworganization",
            index=models.Index(
                fields=["level_3"], name="organizatio_level_3_d2fff0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="raworganization",
            index=models.Index(
                fields=["match_status"], name="organizatio_match_s_1e9207_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="raworganization",
            unique_together={
                (
                    "original",
                    "country",
                    "state",
                    "city",
                    "level_1",
                    "level_2",
                    "level_3",
                )
            },
        ),
    ]
