# Generated by Django 5.2.7 on 2026-01-31 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0011_organizationallevel_raworganization_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="raworganization",
            name="organizatio_name_fe835e_idx",
        ),
        migrations.AlterField(
            model_name="organization",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("user", "user"),
                    ("legacy", "legacy"),
                    ("MEC", "Ministério da Educação e Cultura"),
                    ("ror", "Research Organization Registry"),
                ],
                default="user",
                help_text="Data source (ror, isni, manual, etc.)",
                max_length=50,
                null=True,
                verbose_name="Source",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="raworganization",
            unique_together={
                (
                    "original",
                    "country",
                    "state",
                    "city",
                    "level_1",
                    "level_2",
                    "level_3",
                )
            },
        ),
        migrations.AddIndex(
            model_name="raworganization",
            index=models.Index(
                fields=["original"], name="organizatio_origina_2d699b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="raworganization",
            index=models.Index(
                fields=["level_1"], name="organizatio_level_1_6365d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="raworganization",
            index=models.Index(
                fields=["level_2"], name="organizatio_level_2_567f1f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="raworganization",
            index=models.Index(
                fields=["level_3"], name="organizatio_level_3_d2fff0_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="raworganization",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="raworganization",
            name="organizational_level",
        ),
        migrations.AddField(
            model_name="raworganization",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Standardized organization (after normalization)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="raw_organizations",
                to="organization.organization",
                verbose_name="Organization",
            ),
        ),
        migrations.AddField(
            model_name="raworganization",
            name="organizational_level",
            field=models.ForeignKey(
                blank=True,
                help_text="Standardized levels (requires organization)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="raw_organization_levels",
                to="organization.organizationallevel",
                verbose_name="Organizational Level",
            ),
        ),
    ]
