# Generated by Django 4.1.8 on 2023-05-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("issue", "0002_alter_issue_creator_alter_issue_updated_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="season",
            field=models.CharField(
                blank=True,
                help_text="Ex: Jan-Abr.",
                max_length=20,
                null=True,
                verbose_name="Issue season",
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="month",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Issue month"
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="year",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Issue year"
            ),
        ),
    ]
