# Generated by Django 4.2.7 on 2023-12-09 23:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("issue", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="member",
            name="editorial_board",
        ),
        migrations.RemoveField(
            model_name="member",
            name="member",
        ),
        migrations.RemoveField(
            model_name="member",
            name="updated_by",
        ),
        migrations.DeleteModel(
            name="EditorialBoard",
        ),
        migrations.DeleteModel(
            name="Member",
        ),
    ]
