# Generated by Django 4.1.10 on 2023-09-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("issue", "0002_bibliographicstrip_creator_bibliographicstrip_issue_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="tocsection",
            index=models.Index(
                fields=["plain_text"], name="issue_tocse_plain_t_7515e1_idx"
            ),
        ),
    ]
