# Generated by Django 4.1.10 on 2023-08-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("issue", "0002_bibliographicstrip_creator_bibliographicstrip_issue_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bibliographicstrip",
            options={},
        ),
        migrations.AlterModelOptions(
            name="issuetitle",
            options={},
        ),
        migrations.AddIndex(
            model_name="bibliographicstrip",
            index=models.Index(fields=["text"], name="issue_bibli_text_e8090a_idx"),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(fields=["season"], name="issue_issue_season_32d648_idx"),
        ),
        migrations.AddIndex(
            model_name="issuetitle",
            index=models.Index(fields=["title"], name="issue_issue_title_832688_idx"),
        ),
        migrations.AddIndex(
            model_name="tocsection",
            index=models.Index(fields=["text"], name="issue_tocse_text_50a243_idx"),
        ),
        migrations.AddIndex(
            model_name="tocsection",
            index=models.Index(
                fields=["plain_text"], name="issue_tocse_plain_t_7515e1_idx"
            ),
        ),
    ]
