# Generated by Django 5.0.8 on 2025-07-10 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issue", "0004_alter_bibliographicstrip_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="markup_done",
            field=models.BooleanField(default=True, verbose_name="Markup done"),
        ),
    ]
