# Generated by Django 5.0.8 on 2025-07-10 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("issue", "0005_codesectionissue_sectionissue_issue_code_sections"),
        ("issue", "0005_issue_markup_done"),
    ]

    operations = []
