# Generated by Django 4.1.8 on 2023-05-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("issue", "0005_alter_issuetitle_options_remove_issue_issue_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issuetitle",
            name="language",
        ),
        migrations.RemoveField(
            model_name="issuetitle",
            name="plain_text",
        ),
        migrations.RemoveField(
            model_name="issuetitle",
            name="rich_text",
        ),
        migrations.AddField(
            model_name="issuetitle",
            name="title",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Issue Title"
            ),
        ),
    ]
