# Generated by Django 5.2.3 on 2025-08-01 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("issue", "0006_merge_20250710_1752"),
        ("issue", "0006_merge_20250711_1707"),
    ]

    operations = []
