# Generated by Django 4.1.8 on 2023-06-01 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0006_alter_license_options_rename_license_license_url_and_more"),
        ("issue", "0007_issuetitle_language_bibliographicstrip"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bibliographicstrip",
            name="subtitle",
        ),
        migrations.AddField(
            model_name="bibliographicstrip",
            name="text",
            field=models.TextField(blank=True, null=True, verbose_name="Texto"),
        ),
        migrations.AlterField(
            model_name="bibliographicstrip",
            name="language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.language",
                verbose_name="Idioma",
            ),
        ),
        migrations.CreateModel(
            name="TocSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "rich_text",
                    wagtail.fields.RichTextField(
                        blank=True, null=True, verbose_name="Rich Text"
                    ),
                ),
                (
                    "plain_text",
                    models.TextField(blank=True, null=True, verbose_name="Plain Text"),
                ),
                (
                    "text",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="For JATs is subject.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.language",
                        verbose_name="Idioma",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
            options={
                "verbose_name": "TocSection",
                "verbose_name_plural": "TocSections",
            },
        ),
        migrations.AlterField(
            model_name="issue",
            name="sections",
            field=models.ManyToManyField(blank=True, to="issue.tocsection"),
        ),
    ]
