# Generated by Django 5.2.3 on 2025-08-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issue", "0007_issueexport"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="issue_pid_suffix",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="issue",
            name="order",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="This number controls the order issues appear for a specific year on the website grid",
                null=True,
            ),
        ),
    ]
