# Generated by Django 5.2.3 on 2025-09-25 19:22

import django.db.models.deletion
import modelcluster.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "collection",
            "0006_alter_collection_options_alter_collection_acron2_and_more",
        ),
        ("core", "0008_exportdestination"),
        ("issue", "0010_alter_bibliographicstrip_created_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IssueExporter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "pid",
                    models.CharField(db_index=True, max_length=24, verbose_name="PID"),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DONE", "done"),
                            ("PENDING", "pending"),
                            ("TODO", "to do"),
                            ("DELETED", "deleted"),
                            ("WIP", "in progress"),
                        ],
                        default="TODO",
                        max_length=15,
                        null=True,
                        verbose_name="Status",
                    ),
                ),
                ("detail", models.JSONField(blank=True, null=True)),
                (
                    "version",
                    models.CharField(
                        blank=True, max_length=26, null=True, verbose_name="Version"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="IssueExport",
        ),

        migrations.RemoveIndex(
            model_name="issue",
            name="issue_issue_month_a53df7_idx",
        ),
        migrations.AddField(
            model_name="issueexporter",
            name="collection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="collection.collection",
                verbose_name="Collection",
            ),
        ),
        migrations.AddField(
            model_name="issueexporter",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AddField(
            model_name="issueexporter",
            name="destination",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.exportdestination",
                verbose_name="Destination",
            ),
        ),
        migrations.AddField(
            model_name="issueexporter",
            name="parent",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exporter",
                to="issue.issue",
                verbose_name="Issue",
            ),
        ),
        migrations.AddField(
            model_name="issueexporter",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updater",
            ),
        ),
        migrations.AddIndex(
            model_name="issueexporter",
            index=models.Index(
                fields=["pid", "destination", "collection"],
                name="issue_issue_pid_13b507_idx",
            ),
        ),
    ]
