# Generated by Django 5.2.3 on 2025-09-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issue", "0012_amissue"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="legacy_issue",
            field=models.ManyToManyField(blank=True, to="issue.amissue"),
        ),
    ]
