# Generated by Django 5.2.3 on 2025-09-25 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("issue", "0013_issue_legacy_issue"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="amissue",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="amissue",
            name="issue_amiss_pid_99d89c_idx",
        ),
    ]
