# Generated by Django 5.2.3 on 2025-10-07 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "collection",
            "0006_alter_collection_options_alter_collection_acron2_and_more",
        ),
        ("issue", "0014_alter_amissue_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="amissue",
            name="processing_date",
            field=models.CharField(
                blank=True,
                help_text="Date in YYYY-MM-DD format",
                max_length=10,
                null=True,
                verbose_name="Processing Date",
            ),
        ),
        migrations.AddField(
            model_name="amissue",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("pending", "Pending"), ("todo", "To Do"), ("done", "Done")],
                default="todo",
                max_length=10,
                null=True,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="amissue",
            name="collection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="collection.collection",
                verbose_name="Collection",
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="year",
            field=models.CharField(
                blank=True, max_length=4, null=True, verbose_name="Issue year"
            ),
        ),
    ]
