# Generated by Django 5.2.3 on 2025-10-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issue", "0015_amissue_processing_date_amissue_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="amissue",
            name="url",
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
