# Generated by Django 5.2.3 on 2025-10-23 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issue", "0016_amissue_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issue",
            name="legacy_issue",
        ),
        migrations.AddField(
            model_name="amissue",
            name="new_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="legacy_issue",
                to="issue.issue",
            ),
        ),
    ]
