# Generated by Django 5.2.3 on 2025-10-26 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("issue", "0017_amissue_new_record"),
        ("issue", "0017_remove_issue_legacy_issue_amissue_new_record"),
    ]

    operations = []
