# Generated by Django 5.2.3 on 2025-11-05 21:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0007_collection_platform_status"),
        ("issue", "0017_remove_issue_legacy_issue_amissue_new_record"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="amissue",
            options={
                "verbose_name": "Legacy issue",
                "verbose_name_plural": "Legacy issues",
            },
        ),
        migrations.AddIndex(
            model_name="amissue",
            index=models.Index(fields=["pid"], name="issue_amiss_pid_99d89c_idx"),
        ),
    ]
