# Generated by Django 5.2.3 on 2025-11-05 22:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_exportdestination"),
        ("issue", "0018_alter_amissue_options_and_more"),
        ("journal", "0053_alter_scielojournal_journal_acron"),
        ("location", "0003_alter_city_options_alter_country_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["markup_done"], name="issue_issue_markup__3bbf4a_idx"
            ),
        ),
    ]
