# Generated by Django 5.2.7 on 2025-11-15 16:00

import django.db.models.deletion
import modelcluster.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_exportdestination"),
        ("issue", "0019_issue_issue_issue_markup__3bbf4a_idx"),
        ("journal", "0053_alter_scielojournal_journal_acron"),
        ("location", "0003_alter_city_options_alter_country_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TableOfContents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
            ],
            options={
                "verbose_name": "Table of Contents",
                "verbose_name_plural": "Table of Contents",
            },
        ),
        migrations.RemoveField(
            model_name="issue",
            name="code_sections",
        ),
        migrations.AlterUniqueTogether(
            name="tocsection",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="tocsection",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="tocsection",
            name="language",
        ),
        migrations.RemoveField(
            model_name="tocsection",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="issue",
            name="sections",
        ),
        migrations.AlterModelOptions(
            name="bibliographicstrip",
            options={
                "verbose_name": "Bibliographic Strip",
                "verbose_name_plural": "Bibliographic Strips",
            },
        ),
        migrations.AlterModelOptions(
            name="issuetitle",
            options={"verbose_name": "Title", "verbose_name_plural": "Titles"},
        ),
        migrations.RemoveIndex(
            model_name="issue",
            name="issue_issue_number_780a64_idx",
        ),
        migrations.RemoveIndex(
            model_name="issue",
            name="issue_issue_volume_71bce1_idx",
        ),
        migrations.RemoveIndex(
            model_name="issue",
            name="issue_issue_year_7b3c42_idx",
        ),
        migrations.RemoveIndex(
            model_name="issue",
            name="issue_issue_supplem_bd88be_idx",
        ),
        migrations.RemoveIndex(
            model_name="issue",
            name="issue_issue_markup__3bbf4a_idx",
        ),
        migrations.AlterUniqueTogether(
            name="bibliographicstrip",
            unique_together={("issue", "language")},
        ),
        migrations.AlterUniqueTogether(
            name="issuetitle",
            unique_together={("issue", "language")},
        ),
        migrations.AddField(
            model_name="issue",
            name="issue_folder",
            field=models.CharField(
                blank=True,
                help_text="Format: vXnYsZ (e.g., v10n2s1)",
                max_length=20,
                null=True,
                verbose_name="Issue folder",
            ),
        ),
        migrations.AlterField(
            model_name="bibliographicstrip",
            name="text",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Text"
            ),
        ),
        migrations.AlterField(
            model_name="issuetitle",
            name="title",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Issue Title"
            ),
        ),
        migrations.AddIndex(
            model_name="bibliographicstrip",
            index=models.Index(
                fields=["issue", "language"], name="issue_bibli_issue_i_38faa8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["journal", "year", "volume", "number", "supplement"],
                name="issue_journal_identification",
            ),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["journal", "markup_done"], name="issue_journal_markup_status"
            ),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["journal", "issue_folder"], name="issue_journal_folder_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issuetitle",
            index=models.Index(
                fields=["issue", "language"], name="issue_issue_issue_i_f1aa32_idx"
            ),
        ),
        migrations.AddField(
            model_name="tableofcontents",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AddField(
            model_name="tableofcontents",
            name="issue",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="table_of_contents",
                to="issue.issue",
                verbose_name="Issue",
            ),
        ),
    ]
