# Generated by Django 5.2.7 on 2025-11-15 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0040_article_sections"),
        ("issue", "0020_tableofcontents_remove_codesectionissue_creator_and_more"),
        ("journal", "0054_journaltableofcontents"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tableofcontents",
            name="journal_toc",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="journal.journaltableofcontents",
                verbose_name="Table of Contents Section",
            ),
        ),
        migrations.AddField(
            model_name="tableofcontents",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updater",
            ),
        ),
        migrations.DeleteModel(
            name="CodeSectionIssue",
        ),
        migrations.DeleteModel(
            name="SectionIssue",
        ),
        migrations.DeleteModel(
            name="TocSection",
        ),
        migrations.RemoveField(
            model_name="bibliographicstrip",
            name="sort_order",
        ),
        migrations.RemoveField(
            model_name="issuetitle",
            name="sort_order",
        ),
        migrations.AlterUniqueTogether(
            name="tableofcontents",
            unique_together={("issue", "journal_toc")},
        ),
    ]
