# Generated by Django 4.2.7 on 2023-12-20 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LicenseStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                ("url", models.CharField(blank=True, max_length=255, null=True)),
                ("license_p", wagtail.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "License",
                "verbose_name_plural": "Licenses",
            },
        ),
        migrations.RemoveIndex(
            model_name="license",
            name="core_licens_url_e7d241_idx",
        ),
        migrations.AlterUniqueTogether(
            name="license",
            unique_together={("license_type",)},
        ),
        migrations.AddField(
            model_name="licensestatement",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AddField(
            model_name="licensestatement",
            name="language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.language",
            ),
        ),
        migrations.AddField(
            model_name="licensestatement",
            name="license",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.license",
            ),
        ),
        migrations.AddField(
            model_name="licensestatement",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updater",
            ),
        ),
        migrations.RemoveField(
            model_name="license",
            name="language",
        ),
        migrations.RemoveField(
            model_name="license",
            name="license_p",
        ),
        migrations.RemoveField(
            model_name="license",
            name="url",
        ),
        migrations.AddIndex(
            model_name="licensestatement",
            index=models.Index(fields=["url"], name="core_licens_url_ec8078_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="licensestatement",
            unique_together={("url",)},
        ),
    ]
