# Generated by Django 4.2.7 on 2023-12-11 04:31


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="gender",
            unique_together={("code", "gender")},
        ),
    ]
