# Generated by Django 4.1.10 on 2023-09-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="license",
            index=models.Index(fields=["url"], name="core_licens_url_e7d241_idx"),
        ),
        migrations.AddIndex(
            model_name="license",
            index=models.Index(
                fields=["license_type"], name="core_licens_license_5d1905_idx"
            ),
        ),
    ]
