# Generated by Django 4.1.6 on 2023-03-08 15:29

from django.db import migrations, models
import wagtail.search.index


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gender", models.CharField(max_length=50, verbose_name="Sex")),
            ],
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
