# Generated by Django 4.1.6 on 2023-03-08 16:22

from django.db import migrations, models
import wagtail.search.index


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenderIdentificationStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identification_status",
                    models.CharField(
                        max_length=256, verbose_name="identification_status"
                    ),
                ),
            ],
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
