# Generated by Django 5.0.8 on 2025-07-18 04:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_language_options_alter_license_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="language",
            index=models.Index(fields=["name"], name="core_langua_name_4f83d7_idx"),
        ),
    ]
