# Generated by Django 4.1.8 on 2023-06-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("researcher", "0007_alter_researcher_gender_identification_status_and_more"),
        ("core", "0006_alter_license_options_rename_license_license_url_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GenderIdentificationStatus",
        ),
        migrations.AddField(
            model_name="gender",
            name="code",
            field=models.CharField(
                blank=True, max_length=5, null=True, verbose_name="Código"
            ),
        ),
        migrations.AlterField(
            model_name="gender",
            name="gender",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Sex"
            ),
        ),
    ]
