# Generated by Django 5.2.7 on 2026-01-20 17:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_exportdestination"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="licensestatement",
            options={
                "verbose_name": "License Statement",
                "verbose_name_plural": "License Statements",
            },
        ),
        migrations.AlterUniqueTogether(
            name="license",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="licensestatement",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="license",
            name="version",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="license",
            name="license_type",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="license",
            unique_together={("license_type", "version")},
        ),
        migrations.AddIndex(
            model_name="license",
            index=models.Index(
                fields=["version"], name="core_licens_version_ba68e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="licensestatement",
            index=models.Index(
                fields=["license", "language"], name="core_licens_license_a87bdd_idx"
            ),
        ),
    ]
