from django.utils.translation import gettext_lazy as _

ENDPOINTS = (("fix-pid-v2", "fix-pid-v2"),)

XMLURL_STATUS_SUCCESS = "success"
XMLURL_STATUS_UNEXPECTED_FAILURE = "unexpected_failure"
XMLURL_STATUS_XML_FETCH_FAILED = "xml_fetch_failed"
XMLURL_STATUS_PID_PROVIDER_XML_FAILED = "pid_provider_xml_failed"
XMLURL_STATUS = (
    (XMLURL_STATUS_SUCCESS, _("Success")),
    (XMLURL_STATUS_UNEXPECTED_FAILURE, _("Unexpected failure")),
    (XMLURL_STATUS_XML_FETCH_FAILED, _("XML fetch failed")),
    (XMLURL_STATUS_PID_PROVIDER_XML_FAILED, _("PID provider XML failed")),
)

PPXML_STATUS_WAIT = "WAIT"
PPXML_STATUS_IGNORED = "IGNORE"
PPXML_STATUS_TODO = "TODO"
PPXML_STATUS_DONE = "DONE"
PPXML_STATUS_UNDEF = "UNDEF"
PPXML_STATUS_INVALID = "NVALID"
PPXML_STATUS_UNMATCHED_JOURNAL_OR_ISSUE = "UNMATCH"

PPXML_STATUS_DUPLICATED = "DUP"
PPXML_STATUS_DEDUPLICATED = "DEDUP"
PPXML_STATUS = (
    (PPXML_STATUS_TODO, _("To do")),
    (PPXML_STATUS_DONE, _("Done")),
    (PPXML_STATUS_WAIT, _("waiting")),
    (PPXML_STATUS_IGNORED, _("ignore")),
    (PPXML_STATUS_UNDEF, _("undefined")),
    (PPXML_STATUS_INVALID, _("invalid")),
    (PPXML_STATUS_DUPLICATED, _("duplicated")),
    (PPXML_STATUS_DEDUPLICATED, _("deduplicated")),
    (PPXML_STATUS_UNMATCHED_JOURNAL_OR_ISSUE, _("unmatched journal or issue")),
)
