class APIPidProviderPostError(Exception): ...


class ForbiddenPidProviderXMLRegistrationError(Exception): ...


class GetAPITokenError(Exception): ...


class NotEnoughParametersToGetPidProviderXMLError(Exception): ...


class RequiredISSNErrorToGetPidProviderXMLError(Exception): ...


class RequiredPublicationYearErrorToGetPidProviderXMLError(Exception): ...


class RequiredAuthorErrorToGetPidProviderXMLError(Exception): ...


class QueryDocumentMultipleObjectsReturnedError(Exception): ...


class PidProviderXMLCreateError(Exception): ...


class PidProviderXMLUpdateError(Exception): ...


class PidProviderXMLWithPreError(Exception): ...


class APIPidProviderConfigError(Exception): ...


class InvalidPidError(Exception): ...


class PidProviderXMLFixPidV2Error(Exception): ...


class APIPidProviderFixPidV2Error(Exception): ...
