# Generated by Django 5.0.3 on 2024-04-09 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "xml_validation",
            "0002_alter_validationconfiguration_options_versionsps_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="versionsps",
            options={
                "verbose_name": "Version SPS",
                "verbose_name_plural": "Version SPS",
            },
        ),
    ]
