# Generated by Django 5.0.8 on 2025-05-26 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("xml_validation", "0003_alter_versionsps_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="validationconfiguration",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Data de criação"
            ),
        ),
        migrations.AlterField(
            model_name="validationconfiguration",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criador",
            ),
        ),
        migrations.AlterField(
            model_name="validationconfiguration",
            name="updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Data da última atualização"
            ),
        ),
        migrations.AlterField(
            model_name="validationconfiguration",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Atualizador",
            ),
        ),
        migrations.AlterField(
            model_name="versionsps",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Data de criação"
            ),
        ),
        migrations.AlterField(
            model_name="versionsps",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criador",
            ),
        ),
        migrations.AlterField(
            model_name="versionsps",
            name="updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Data da última atualização"
            ),
        ),
        migrations.AlterField(
            model_name="versionsps",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Atualizador",
            ),
        ),
    ]
