from django.utils.translation import gettext as _

translates = {
    "journal_title": _("Periódico"),
    "publication_year": _("Ano de publicação"),
    "type": _("Tipo de Literatura"),
    "collection": _("Coleções"),
    "year_cluster": _("Ano"),
    "la": _("Idioma"),
    "in": _("Coleções"),
    "arg": _("Argentina"),
    "scl": _("Brasil"),
    "bol": _("Bolívia"),
    "chl": _("Chile"),
    "col": _("Colômbia"),
    "cri": _("Costa Rica"),
    "cub": _("Cuba"),
    "esp": _("Espanha"),
    "mex": _("México"),
    "prt": _("Portugal"),
    "ven": _("Venezuela"),
    "spa": _("Saúde Pública"),
    "sss": _("Social Sciences"),
    "sza": _("África do Sul"),
    "per": _("Peru"),
    "ury": _("Uruguai"),
    "ecu": _("Ecuador"),
    "pry": _("Paraguai"),
    "wid": _("Índias Ocidentais"),
    "pt": _("Português"),
    "es": _("Espanhol"),
    "en": _("Inglês"),
    "af": _("Africaner"),
    "fr": _("Francês"),
    "it": _("Italiano"),
    "de": _("Alemão"),
    "ar": _("Árabe"),
    "ko": _("Coreano"),
    "ja": _("Japonês"),
    "bg": _("Búlgaro"),
    "bos": _("Bósnio"),
    "cat": _("Catalão"),
    "ca": _("Catalão"),
    "ru": _("Russo"),
    "rum": _("Romeno"),
    "uk": _("Ucraniano"),
    "tr": _("Turco"),
    "sv": _("Sueco"),
    "srp": _("Sérvio"),
    "slo": _("Eslovaco"),
    "sl": _("Esloveno"),
    "pl": _("Polonês"),
    "nl": _("Holandês"),
    "dut": _("Holandês"),
    "lav": _("Letão"),
    "lit": _("Lituano"),
    "ice": _("Islandês"),
    "hu": _("Húngaro"),
    "hrv": _("Croata"),
    "he": _("Hebraico"),
    "fin": _("Finlandês"),
    "ch": _("Chinês"),
    "research article": _("Artigo"),
    "editorial": _("Editorial"),
    "book review": _("Resenha de livro"),
    "case report": _("Relato de caso"),
    "rapid communication": _("Comunicação rápida"),
    "review article": _("Artigo de revisão"),
    "brief report": _("Relato breve"),
    "letter": _("Carta"),
    "article commentary": _("Artigo de comentário"),
    "undefined": _("Outros"),
    "other": _("Outros"),
    "abstract": _("Resumo"),
    "addendum": _("Addendum"),
    "press-release": _("Comunicado de imprensa"),
    "news": _("Notícia"),
    "correction": _("Correção"),
    "discussion": _("Discussão"),
    "obituary": _("Obituário"),
    "in brief": _("Em resumo"),
}



