# Generated by Django 4.2.7 on 2024-01-31 11:46

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("collection", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collection",
            name="name",
        ),
        migrations.AddField(
            model_name="collectionname",
            name="collection",
            field=modelcluster.fields.ParentalKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="collection_name",
                to="collection.collection",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="collection_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("journals", "Journals"),
                    ("preprints", "Preprints"),
                    ("repositories", "Repositories"),
                    ("books", "Books"),
                    ("data", "Data repository"),
                ],
                max_length=32,
                null=True,
                verbose_name="Collection Type",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("certified", "Certified"),
                    ("development", "Development"),
                    ("diffusion", "Diffusion"),
                    ("independent", "Independent"),
                ],
                max_length=32,
                null=True,
                verbose_name="Status",
            ),
        ),
    ]
