# Generated by Django 4.2.7 on 2024-02-01 19:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("collection", "0002_alter_collection_collection_type_and_more"),
        (
            "collection",
            "0002_remove_collection_name_collectionname_collection_and_more",
        ),
    ]

    operations = []
