# Generated by Django 4.1.7 on 2023-02-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collection", "0002_alter_collection_creator_alter_collection_updated_by"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="collection",
            name="collection__type_4165bc_idx",
        ),
        migrations.RemoveField(
            model_name="collection",
            name="type",
        ),
        migrations.AddField(
            model_name="collection",
            name="type_field",
            field=models.TextField(
                blank=True,
                choices=[
                    ("journals", "Journals"),
                    ("preprints", "Preprints"),
                    ("repositories", "Repositories"),
                    ("books", "Books"),
                    ("data", "Data repository"),
                ],
                null=True,
                verbose_name="Tipo",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="main_name",
            field=models.TextField(blank=True, null=True, verbose_name="Main name"),
        ),
        migrations.AlterField(
            model_name="collection",
            name="name",
            field=models.ManyToManyField(
                blank=True,
                to="collection.collectionname",
                verbose_name="Collection Name",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="status",
            field=models.TextField(
                blank=True,
                choices=[
                    ("certified", "Certified"),
                    ("development", "Development"),
                    ("diffusion", "Diffusion"),
                    ("independent", "Independent"),
                ],
                null=True,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="collectionname",
            name="text",
            field=models.TextField(blank=True, null=True, verbose_name="Texto"),
        ),
        migrations.AddIndex(
            model_name="collection",
            index=models.Index(
                fields=["type_field"], name="collection__type_fi_ccf430_idx"
            ),
        ),
    ]
