# Generated by Django 5.0.8 on 2025-05-26 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0003_merge_20240201_1921"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="acron2",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Acrônimo com 2 caracteres",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="acron3",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Acrônimo com 3 caracteres",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="collection_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("journals", "Periódicos"),
                    ("preprints", "Preprints"),
                    ("repositories", "Repositórios"),
                    ("books", "Livros"),
                    ("data", "Repositório de dados"),
                ],
                max_length=20,
                null=True,
                verbose_name="Tipo de Coleção",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Data de criação"
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criador",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="domain",
            field=models.URLField(blank=True, null=True, verbose_name="Domínio"),
        ),
        migrations.AlterField(
            model_name="collection",
            name="foundation_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Dados da fundação"
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="has_analytics",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Possui análise"
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="is_active",
            field=models.BooleanField(blank=True, null=True, verbose_name="Está ativo"),
        ),
        migrations.AlterField(
            model_name="collection",
            name="main_name",
            field=models.TextField(
                blank=True, null=True, verbose_name="Nome principal"
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("certified", "Certificado"),
                    ("development", "Desenvolvimento"),
                    ("diffusion", "Difusão"),
                    ("independent", "Independente"),
                ],
                max_length=20,
                null=True,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Data da última atualização"
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Atualizador",
            ),
        ),
    ]
