# Generated by Django 4.1.7 on 2023-03-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collection", "0003_remove_collection_collection__type_4165bc_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="collection",
            name="collection__type_fi_ccf430_idx",
        ),
        migrations.RemoveField(
            model_name="collection",
            name="type_field",
        ),
        migrations.AddField(
            model_name="collection",
            name="collection_type",
            field=models.TextField(
                blank=True,
                choices=[
                    ("journals", "Journals"),
                    ("preprints", "Preprints"),
                    ("repositories", "Repositories"),
                    ("books", "Books"),
                    ("data", "Data repository"),
                ],
                null=True,
                verbose_name="Collection Type",
            ),
        ),
        migrations.AddIndex(
            model_name="collection",
            index=models.Index(
                fields=["collection_type"], name="collection__collect_a99863_idx"
            ),
        ),
    ]
