# Generated by Django 5.2.3 on 2025-08-04 04:10

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0004_alter_collection_acron2_alter_collection_acron3_and_more"),
        ("core", "0006_language_core_langua_name_4f83d7_idx"),
        (
            "organization",
            "0008_remove_organization_organizatio_is_offi_538fd2_idx_and_more",
        ),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionExecutingOrganization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "initial_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Inicial"
                    ),
                ),
                (
                    "final_date",
                    models.DateField(blank=True, null=True, verbose_name="Data Final"),
                ),
                (
                    "collection",
                    modelcluster.fields.ParentalKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="executing_organization",
                        to="collection.collection",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Select the standardized organization data",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="organization.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Executing Organization",
                "verbose_name_plural": "Executing Organizations",
            },
        ),
        migrations.CreateModel(
            name="CollectionSocialNetwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("facebook", "Facebook"),
                            ("twitter", "Twitter"),
                            ("mastodon", "Mastodon"),
                            ("bsky", "Discover Blue Sky"),
                            ("youtube", "Youtube"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Nome",
                    ),
                ),
                ("url", models.URLField(blank=True, null=True, verbose_name="URL")),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="social_network",
                        to="collection.collection",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CollectionSupportingOrganization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "initial_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Inicial"
                    ),
                ),
                (
                    "final_date",
                    models.DateField(blank=True, null=True, verbose_name="Data Final"),
                ),
                (
                    "collection",
                    modelcluster.fields.ParentalKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supporting_organization",
                        to="collection.collection",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Select the standardized organization data",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="organization.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supporting Organization",
                "verbose_name_plural": "Supporting Organizations",
            },
        ),
        migrations.CreateModel(
            name="CollectionLogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("thumbnail", "Thumbnail (150x150)"),
                            ("small", "Small (300x300)"),
                            ("medium", "Medium (600x600)"),
                            ("large", "Large (1200x1200)"),
                            ("original", "Original"),
                        ],
                        default="medium",
                        help_text="Select the size/purpose of this logo",
                        max_length=20,
                        verbose_name="Logo Size",
                    ),
                ),
                (
                    "collection",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logos",
                        to="collection.collection",
                        verbose_name="Coleção",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        help_text="Language version of this logo",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.language",
                        verbose_name="Logo language",
                    ),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Logo Image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Collection Logo",
                "verbose_name_plural": "Collection Logos",
                "ordering": ["sort_order", "language", "size"],
                "unique_together": {("collection", "size", "language")},
            },
        ),
    ]
