# Generated by Django 5.2.3 on 2025-09-01 17:24

import django.db.models.deletion
import modelcluster.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0005_collectionexecutingorganization_and_more"),
        ("core", "0007_alter_language_options_alter_license_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collection",
            options={
                "verbose_name": "Collection",
                "verbose_name_plural": "Collections",
            },
        ),
        migrations.AlterField(
            model_name="collection",
            name="acron2",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Acronym with 2 chars",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="acron3",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Acronym with 3 chars",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="code",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Code"
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="collection_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("journals", "Journals"),
                    ("preprints", "Preprints"),
                    ("repositories", "Repositories"),
                    ("books", "Books"),
                    ("data", "Data repository"),
                ],
                max_length=20,
                null=True,
                verbose_name="Collection Type",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creation date"),
        ),
        migrations.AlterField(
            model_name="collection",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="domain",
            field=models.URLField(blank=True, null=True, verbose_name="Domain"),
        ),
        migrations.AlterField(
            model_name="collection",
            name="foundation_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Foundation data"
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="has_analytics",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Has analytics"
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="is_active",
            field=models.BooleanField(blank=True, null=True, verbose_name="Is active"),
        ),
        migrations.AlterField(
            model_name="collection",
            name="main_name",
            field=models.TextField(blank=True, null=True, verbose_name="Main name"),
        ),
        migrations.AlterField(
            model_name="collection",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("certified", "Certified"),
                    ("development", "Development"),
                    ("diffusion", "Diffusion"),
                    ("independent", "Independent"),
                ],
                max_length=20,
                null=True,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Last update date"),
        ),
        migrations.AlterField(
            model_name="collection",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updater",
            ),
        ),
        migrations.AlterField(
            model_name="collectionexecutingorganization",
            name="final_date",
            field=models.DateField(blank=True, null=True, verbose_name="Final Date"),
        ),
        migrations.AlterField(
            model_name="collectionexecutingorganization",
            name="initial_date",
            field=models.DateField(blank=True, null=True, verbose_name="Initial Date"),
        ),
        migrations.AlterField(
            model_name="collectionlogo",
            name="collection",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logos",
                to="collection.collection",
                verbose_name="Collection",
            ),
        ),
        migrations.AlterField(
            model_name="collectionname",
            name="language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.language",
                verbose_name="Language",
            ),
        ),
        migrations.AlterField(
            model_name="collectionname",
            name="text",
            field=models.TextField(blank=True, null=True, verbose_name="Text"),
        ),
        migrations.AlterField(
            model_name="collectionsocialnetwork",
            name="name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("facebook", "Facebook"),
                    ("twitter", "Twitter"),
                    ("mastodon", "Mastodon"),
                    ("bsky", "Discover Blue Sky"),
                    ("youtube", "Youtube"),
                ],
                max_length=20,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="collectionsupportingorganization",
            name="final_date",
            field=models.DateField(blank=True, null=True, verbose_name="Final Date"),
        ),
        migrations.AlterField(
            model_name="collectionsupportingorganization",
            name="initial_date",
            field=models.DateField(blank=True, null=True, verbose_name="Initial Date"),
        ),
    ]
