# Generated by Django 5.2.3 on 2025-09-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "collection",
            "0006_alter_collection_options_alter_collection_acron2_and_more",
        ),
        ("core", "0007_alter_language_options_alter_license_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collectionexecutingorganization",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "Executing Organization",
                "verbose_name_plural": "Executing Organizations",
            },
        ),
        migrations.AlterModelOptions(
            name="collectionlogo",
            options={
                "ordering": ["sort_order", "language"],
                "verbose_name": "Collection Logo",
                "verbose_name_plural": "Collection Logos",
            },
        ),
        migrations.AlterModelOptions(
            name="collectionsupportingorganization",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "Supporting Organization",
                "verbose_name_plural": "Supporting Organizations",
            },
        ),
        migrations.AlterUniqueTogether(
            name="collectionlogo",
            unique_together={("collection", "language", "purpose")},
        ),
        migrations.AddField(
            model_name="collectionlogo",
            name="purpose",
            field=models.CharField(
                blank=True,
                choices=[
                    ("homepage", "Homepage"),
                    ("header", "Header"),
                    ("logo_drop_menu", "Logo drop menu"),
                    ("footer", "Footer"),
                    ("menu", "Menu"),
                ],
                help_text="Select the purpose of this logo",
                max_length=20,
            ),
        ),
        migrations.RemoveField(
            model_name="collectionlogo",
            name="size",
        ),
    ]
