# Generated by Django 5.2.3 on 2025-10-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "collection",
            "0006_alter_collection_options_alter_collection_acron2_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="platform_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("classic", "Classic"),
                    ("new", "New"),
                    ("migrating", "Migrating"),
                ],
                max_length=20,
                null=True,
                verbose_name="Platform Status",
            ),
        ),
    ]
