# Generated by Django 5.2.7 on 2026-01-31 21:41

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0007_collection_platform_status"),
        ("organization", "0011_organizationallevel_raworganization_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionOrganization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "initial_date",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Initial Date",
                    ),
                ),
                (
                    "final_date",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Final Date"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("coordinator", "Coordinator"),
                            ("owner", "Owner"),
                            ("publisher", "Publisher"),
                            ("sponsor", "Sponsor"),
                            ("copyright_holder", "Copyright Holder"),
                            ("partner", "Partner"),
                            ("funder", "Funder"),
                            ("host", "Host"),
                            ("provider", "Provider"),
                            ("company", "Company"),
                        ],
                        max_length=50,
                        verbose_name="Role",
                    ),
                ),
                (
                    "collection",
                    modelcluster.fields.ParentalKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organizations",
                        to="collection.collection",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Select the standardized organization data",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="organization.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Collection Organization",
                "verbose_name_plural": "Collection Organizations",
                "unique_together": {
                    ("collection", "organization", "role", "initial_date", "final_date")
                },
            },
        ),
    ]
