# Generated by Django 5.2.7 on 2026-09-23 14:06

import collection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0007_collection_platform_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="network_classification",
            field=collection.models.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("scielonetwork", "SciELO Network"),
                        ("thematic", "Thematic"),
                        ("independent", "Independent"),
                    ],
                    max_length=20,
                ),
                blank=True,
                null=True,
                size=None,
                verbose_name="Network classification",
            ),
        ),
    ]
