# Generated by Django 5.2.3 on 2025-10-28 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0007_alter_collectionexecutingorganization_options_and_more"),
        ("collection", "0007_collection_platform_status"),
    ]

    operations = []
