# Generated by Django 4.1.10 on 2023-08-29 18:08

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0002_remove_journal_name_remove_journal_url_and_more"),
        ("journal_and_collection", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="occurrence_date",
        ),
        migrations.RemoveField(
            model_name="journalandcollection",
            name="journal",
        ),
        migrations.AddField(
            model_name="event",
            name="occurrence_date_day",
            field=models.CharField(
                blank=True, max_length=2, null=True, verbose_name="Occurrence date day"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="occurrence_date_month",
            field=models.CharField(
                blank=True,
                choices=[
                    (1, "January"),
                    (2, "February"),
                    (3, "March"),
                    (4, "April"),
                    (5, "May"),
                    (6, "June"),
                    (7, "July"),
                    (8, "August"),
                    (9, "September"),
                    (10, "October"),
                    (11, "November"),
                    (12, "December"),
                ],
                max_length=2,
                null=True,
                verbose_name="Occurrence date month",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="occurrence_date_year",
            field=models.CharField(
                default="2023", max_length=4, verbose_name="Occurrence date year"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="journalandcollection",
            name="scielo",
            field=modelcluster.fields.ParentalKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="journal_history",
                to="journal.scielojournal",
                verbose_name="Journal",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="occurrence_type",
            field=models.TextField(
                blank=True, null=True, verbose_name="Occurrence type"
            ),
        ),
    ]
