permission_collection_team = [
    {"app": "article", "model": "article", "codename": "view_article"},
    {"app": "article", "model": "articleformat", "codename": "view_articleformat"},
    {"app": "article", "model": "articlefunding", "codename": "view_articlefunding"},
    {"app": "book", "model": "book", "codename": "view_book"},
    {"app": "collection", "model": "collection", "codename": "view_collection"},
    {"app": "core", "model": "gender", "codename": "add_gender"},
    {"app": "core", "model": "gender", "codename": "change_gender"},
    {"app": "core", "model": "gender", "codename": "view_gender"},
    {
        "app": "editorialboard",
        "model": "editorialboard",
        "codename": "add_editorialboard",
    },
    {
        "app": "editorialboard",
        "model": "editorialboard",
        "codename": "change_editorialboard",
    },
    {
        "app": "editorialboard",
        "model": "editorialboard",
        "codename": "view_editorialboard",
    },
    {
        "app": "editorialboard",
        "model": "editorialboardmember",
        "codename": "add_editorialboardmember",
    },
    {
        "app": "editorialboard",
        "model": "editorialboardmember",
        "codename": "change_editorialboardmember",
    },
    {
        "app": "editorialboard",
        "model": "editorialboardmember",
        "codename": "view_editorialboardmember",
    },
    {
        "app": "editorialboard",
        "model": "editorialboardmemberfile",
        "codename": "add_editorialboardmemberfile",
    },
    {
        "app": "editorialboard",
        "model": "editorialboardmemberfile",
        "codename": "change_editorialboardmemberfile",
    },
    {
        "app": "editorialboard",
        "model": "editorialboardmemberfile",
        "codename": "delete_editorialboardmemberfile",
    },
    {
        "app": "editorialboard",
        "model": "editorialboardmemberfile",
        "codename": "view_editorialboardmemberfile",
    },
    {"app": "editorialboard", "model": "rolemodel", "codename": "add_rolemodel"},
    {"app": "editorialboard", "model": "rolemodel", "codename": "change_rolemodel"},
    {"app": "editorialboard", "model": "rolemodel", "codename": "view_rolemodel"},
    {"app": "institution", "model": "institution", "codename": "add_institution"},
    {"app": "institution", "model": "institution", "codename": "change_institution"},
    {"app": "institution", "model": "institution", "codename": "view_institution"},
    {"app": "institution", "model": "sponsor", "codename": "view_sponsor"},
    {"app": "issue", "model": "issue", "codename": "add_issue"},
    {"app": "issue", "model": "issue", "codename": "change_issue"},
    {"app": "issue", "model": "issue", "codename": "view_issue"},
    {
        "app": "journal",
        "model": "articlesubmissionformatchecklist",
        "codename": "add_articlesubmissionformatchecklist",
    },
    {
        "app": "journal",
        "model": "articlesubmissionformatchecklist",
        "codename": "change_articlesubmissionformatchecklist",
    },
    {
        "app": "journal",
        "model": "articlesubmissionformatchecklist",
        "codename": "view_articlesubmissionformatchecklist",
    },
    {"app": "journal", "model": "journal", "codename": "add_journal"},
    {"app": "journal", "model": "journal", "codename": "change_journal"},
    {"app": "journal", "model": "journal", "codename": "view_journal"},
    {"app": "journal", "model": "officialjournal", "codename": "add_officialjournal"},
    {
        "app": "journal",
        "model": "officialjournal",
        "codename": "change_officialjournal",
    },
    {"app": "journal", "model": "officialjournal", "codename": "view_officialjournal"},
    {"app": "journal", "model": "scielojournal", "codename": "add_scielojournal"},
    {"app": "journal", "model": "scielojournal", "codename": "change_scielojournal"},
    {"app": "journal", "model": "scielojournal", "codename": "view_scielojournal"},
    {"app": "journal", "model": "subject", "codename": "view_subject"},
    {"app": "journal", "model": "webofknowledge", "codename": "view_webofknowledge"},
    {
        "app": "journal",
        "model": "webofknowledgesubjectcategory",
        "codename": "view_webofknowledgesubjectcategory",
    },
    {"app": "location", "model": "city", "codename": "add_city"},
    {"app": "location", "model": "city", "codename": "change_city"},
    {"app": "location", "model": "city", "codename": "view_city"},
    {"app": "location", "model": "country", "codename": "add_country"},
    {"app": "location", "model": "country", "codename": "change_country"},
    {"app": "location", "model": "country", "codename": "view_country"},
    {"app": "location", "model": "location", "codename": "add_location"},
    {"app": "location", "model": "location", "codename": "change_location"},
    {"app": "location", "model": "location", "codename": "view_location"},
    {"app": "location", "model": "state", "codename": "add_state"},
    {"app": "location", "model": "state", "codename": "change_state"},
    {"app": "location", "model": "state", "codename": "view_state"},
    {"app": "report", "model": "reportcsv", "codename": "view_reportcsv"},
    {"app": "researcher", "model": "affiliation", "codename": "view_affiliation"},
    {"app": "researcher", "model": "personname", "codename": "view_personname"},
    {"app": "researcher", "model": "researcher", "codename": "view_researcher"},
    {
        "app": "researcher",
        "model": "researcheridentifier",
        "codename": "view_researcheridentifier",
    },
    {"app": "thematic_areas", "model": "thematicarea", "codename": "add_thematicarea"},
    {
        "app": "thematic_areas",
        "model": "thematicarea",
        "codename": "change_thematicarea",
    },
    {"app": "thematic_areas", "model": "thematicarea", "codename": "view_thematicarea"},
    {
        "app": "thematic_areas",
        "model": "thematicareafile",
        "codename": "add_thematicareafile",
    },
    {
        "app": "thematic_areas",
        "model": "thematicareafile",
        "codename": "change_thematicareafile",
    },
    {
        "app": "thematic_areas",
        "model": "thematicareafile",
        "codename": "view_thematicareafile",
    },
    {"app": "vocabulary", "model": "keyword", "codename": "view_keyword"},
    {"app": "vocabulary", "model": "vocabulary", "codename": "view_vocabulary"},
]