# Generated by Django 3.2.12 on 2022-11-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("altmetric", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawaltmetric",
            name="extraction_date",
            field=models.CharField(max_length=26, verbose_name="Extraction Date"),
        ),
    ]
