# Generated by Django 5.0.8 on 2025-05-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("altmetric", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawaltmetric",
            name="extraction_date",
            field=models.CharField(max_length=26, verbose_name="Data de Extração"),
        ),
        migrations.AlterField(
            model_name="rawaltmetric",
            name="json",
            field=models.JSONField(blank=True, null=True, verbose_name="Arquivo JSON"),
        ),
        migrations.AlterField(
            model_name="rawaltmetric",
            name="resource_type",
            field=models.CharField(
                choices=[("article", "Artigo"), ("journal", "Periódico")],
                max_length=10,
                verbose_name="Tipo de Recurso",
            ),
        ),
    ]
