# Generated by Django 5.2.3 on 2025-09-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("altmetric", "0002_alter_rawaltmetric_extraction_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawaltmetric",
            name="extraction_date",
            field=models.CharField(max_length=26, verbose_name="Extraction Date"),
        ),
        migrations.AlterField(
            model_name="rawaltmetric",
            name="json",
            field=models.JSONField(blank=True, null=True, verbose_name="JSON File"),
        ),
        migrations.AlterField(
            model_name="rawaltmetric",
            name="resource_type",
            field=models.CharField(
                choices=[("article", "Article"), ("journal", "Journal")],
                max_length=10,
                verbose_name="Resource Type",
            ),
        ),
    ]
