# Generated by Django 3.2.12 on 2022-11-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altmetric', '0002_alter_rawaltmetric_extraction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawaltmetric',
            name='resource_type',
            field=models.CharField(choices=[('a', 'Article'), ('j', 'Journal')], max_length=10, verbose_name='Resource Type'),
        ),
    ]
