# Generated by Django 4.2.7 on 2024-02-26 01:37

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0017_remove_journal_other_titles"),
        ("reference", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="journaltitle",
            name="journal",
            field=modelcluster.fields.ParentalKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="other_titles",
                to="journal.journal",
            ),
        ),
    ]
