# Generated by Django 4.2.7 on 2024-02-26 01:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reference", "0002_journaltitle_journal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journaltitle",
            name="title",
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
