# Generated by Django 3.2.12 on 2023-01-31 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institution', '0003_alter_institution_is_official'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleFunding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('award_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Award ID')),
                ('creator', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articlefunding_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('funding_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.sponsor')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articlefunding_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('pid_v2', models.CharField(blank=True, max_length=23, null=True, verbose_name='PID V2')),
                ('creator', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('fundings', models.ManyToManyField(blank=True, to='article.ArticleFunding', verbose_name='Fundings')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
            ],
        ),
        migrations.AddIndex(
            model_name='articlefunding',
            index=models.Index(fields=['award_id'], name='article_art_award_i_c81815_idx'),
        ),
        migrations.AddIndex(
            model_name='articlefunding',
            index=models.Index(fields=['funding_source'], name='article_art_funding_180f9e_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['pid_v2'], name='article_art_pid_v2_fa7897_idx'),
        ),
    ]
