# Generated by Django 4.1.7 on 2023-02-28 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_language"),
        ("article", "0002_alter_abstract_creator_alter_abstract_updated_by_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="articlecount",
            new_name="article_art_languag_1293e9_idx",
            old_name="article_art_languag_5b1006_idx",
        ),
        migrations.AlterField(
            model_name="articlecount",
            name="language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.language",
                verbose_name="Idioma",
            ),
        ),
    ]
