# Generated by Django 4.1.10 on 2023-09-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0003_alter_article_first_page_alter_article_last_page"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["pid_v3"], name="article_art_pid_v3_2370cc_idx"),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["pub_date_year"], name="article_art_pub_dat_9c64b4_idx"
            ),
        ),
    ]
