# Generated by Django 4.2.6 on 2023-11-09 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("article", "0003_initial"),
        ("core", "0001_initial"),
        ("institution", "0001_initial"),
        ("journal", "0001_initial"),
        ("vocabulary", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="journal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="journal.journal",
                verbose_name="Journal",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="keywords",
            field=models.ManyToManyField(blank=True, to="vocabulary.keyword"),
        ),
        migrations.AddField(
            model_name="article",
            name="languages",
            field=models.ManyToManyField(blank=True, to="core.language"),
        ),
        migrations.AddField(
            model_name="article",
            name="license",
            field=models.ManyToManyField(blank=True, to="core.license"),
        ),
        migrations.AddField(
            model_name="article",
            name="publisher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="institution.institution",
                verbose_name="Publisher",
            ),
        ),
    ]
