# Generated by Django 4.1.7 on 2023-03-29 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("vocabulary", "0003_alter_keyword_text_alter_vocabulary_name"),
        ("core", "0005_license"),
        ("researcher", "0006_alter_researcher_gender_identification_status"),
        (
            "article",
            "0003_rename_article_art_languag_5b1006_idx_article_art_languag_1293e9_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleId",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("article_id", models.CharField(blank=True, max_length=255, null=True)),
                ("pub_id_type", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "specific_use",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
            options={
                "verbose_name": "ArticleId",
                "verbose_name_plural": "ArticleIds",
            },
        ),
        migrations.CreateModel(
            name="ArticleType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(blank=True, null=True, verbose_name="Texto")),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="For JATs is subject.",
                        max_length=50,
                        null=True,
                        verbose_name="Nome",
                    ),
                ),
                (
                    "type_category",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categorys",
            },
        ),
        migrations.CreateModel(
            name="Title",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.TextField(blank=True, null=True, verbose_name="Título"),
                ),
                (
                    "title_html",
                    models.TextField(blank=True, null=True, verbose_name="Title HTML"),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="Idioma"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="article",
            name="first_page",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="issue",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="languages",
            field=models.ManyToManyField(blank=True, to="core.language"),
        ),
        migrations.AddField(
            model_name="article",
            name="last_page",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="license",
            field=models.ManyToManyField(blank=True, to="core.license"),
        ),
        migrations.AddField(
            model_name="article",
            name="researchers",
            field=models.ManyToManyField(blank=True, to="researcher.researcher"),
        ),
        migrations.AddField(
            model_name="article",
            name="volume",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="SubArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="article.article",
                    ),
                ),
                (
                    "article_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="article.articletype",
                    ),
                ),
                ("title", models.ManyToManyField(blank=True, to="article.title")),
            ],
            options={
                "verbose_name": "SubArticle",
                "verbose_name_plural": "SubArticles",
            },
        ),
        migrations.CreateModel(
            name="AbstractModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(blank=True, null=True, verbose_name="Texto")),
                ("keywords", models.ManyToManyField(to="vocabulary.keyword")),
            ],
        ),
        migrations.AddField(
            model_name="article",
            name="abstract_field",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="article.abstractmodel",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="article_ids",
            field=models.ManyToManyField(blank=True, to="article.articleid"),
        ),
        migrations.AddField(
            model_name="article",
            name="article_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="article.articletype",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="categories",
            field=models.ManyToManyField(blank=True, to="article.category"),
        ),
        migrations.AddField(
            model_name="article",
            name="titles",
            field=models.ManyToManyField(blank=True, to="article.title"),
        ),
    ]
