# Generated by Django 4.1.10 on 2023-09-18 02:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0003_alter_article_first_page_alter_article_last_page"),
        ("article", "0003_article_article_art_pid_v3_2370cc_idx_and_more"),
    ]

    operations = []
