# Generated by Django 4.2.7 on 2023-12-29 18:38

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_licensestatement_unique_together"),
        ("article", "0004_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="abstracts",
        ),
        migrations.AddField(
            model_name="documentabstract",
            name="article",
            field=modelcluster.fields.ParentalKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="abstracts",
                to="article.article",
            ),
        ),
        migrations.AddField(
            model_name="documentabstract",
            name="sort_order",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="documentabstract",
            unique_together={("article", "language")},
        ),
        migrations.AddIndex(
            model_name="documentabstract",
            index=models.Index(
                fields=["language"], name="article_doc_languag_256f1e_idx"
            ),
        ),
    ]
