# Generated by Django 4.1.8 on 2023-05-02 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_license_options_rename_license_license_url_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("doi", "0002_alter_doi_creator_alter_doi_updated_by_and_more"),
        (
            "journal",
            "0004_rename_journal_mis_languag_bfebee_idx_journal_mis_languag_a94f2f_idx_and_more",
        ),
        ("vocabulary", "0003_alter_keyword_text_alter_vocabulary_name"),
        ("article", "0004_articleid_articletype_category_title_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentAbstract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "rich_text",
                    wagtail.fields.RichTextField(
                        blank=True, null=True, verbose_name="Rich Text"
                    ),
                ),
                (
                    "plain_text",
                    models.TextField(blank=True, null=True, verbose_name="Plain Text"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.language",
                        verbose_name="Idioma",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="abstractmodel",
            name="keywords",
        ),
        migrations.AlterModelOptions(
            name="tocsection",
            options={
                "verbose_name": "TocSection",
                "verbose_name_plural": "TocSections",
            },
        ),
        migrations.RemoveField(
            model_name="article",
            name="abstract_field",
        ),
        migrations.RemoveField(
            model_name="article",
            name="article_ids",
        ),
        migrations.RemoveField(
            model_name="article",
            name="categories",
        ),
        migrations.RemoveField(
            model_name="documenttitle",
            name="text",
        ),
        migrations.RemoveField(
            model_name="subarticle",
            name="title",
        ),
        migrations.AddField(
            model_name="article",
            name="doi",
            field=models.ManyToManyField(blank=True, to="doi.doi"),
        ),
        migrations.AddField(
            model_name="article",
            name="elocation_id",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="journal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="journal.scielojournal",
                verbose_name="Journal",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="keywords",
            field=models.ManyToManyField(blank=True, to="vocabulary.keyword"),
        ),
        migrations.AddField(
            model_name="article",
            name="pid_v3",
            field=models.CharField(
                blank=True, max_length=23, null=True, verbose_name="PID V3"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="pub_date_collection",
            field=models.CharField(
                blank=True,
                help_text="Data do fascículo.",
                max_length=10,
                null=True,
                verbose_name="collection pub date",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="pub_date_collection_season",
            field=models.CharField(
                blank=True, help_text="Ex: Jan-Abr", max_length=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="pub_date_collection_year",
            field=models.CharField(
                blank=True, help_text="Ano do fascículo", max_length=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="pub_date_pub",
            field=models.CharField(
                blank=True,
                help_text="Data de publicação no site.",
                max_length=10,
                null=True,
                verbose_name="pub date",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="pub_date_pub_year",
            field=models.CharField(
                blank=True,
                help_text="Ano de publicação no site.",
                max_length=4,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="toc_sections",
            field=models.ManyToManyField(blank=True, to="article.tocsection"),
        ),
        migrations.AddField(
            model_name="documenttitle",
            name="plain_text",
            field=models.TextField(blank=True, null=True, verbose_name="Plain Text"),
        ),
        migrations.AddField(
            model_name="documenttitle",
            name="rich_text",
            field=wagtail.fields.RichTextField(
                blank=True, null=True, verbose_name="Rich Text"
            ),
        ),
        migrations.AddField(
            model_name="subarticle",
            name="titles",
            field=models.ManyToManyField(blank=True, to="article.documenttitle"),
        ),
        migrations.AddField(
            model_name="tocsection",
            name="plain_text",
            field=models.TextField(blank=True, null=True, verbose_name="Plain Text"),
        ),
        migrations.AddField(
            model_name="tocsection",
            name="rich_text",
            field=wagtail.fields.RichTextField(
                blank=True, null=True, verbose_name="Rich Text"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="issue",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="titles",
            field=models.ManyToManyField(blank=True, to="article.documenttitle"),
        ),
        migrations.AlterField(
            model_name="article",
            name="volume",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="documenttitle",
            name="language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.language",
                verbose_name="Idioma",
            ),
        ),
        migrations.AlterField(
            model_name="tocsection",
            name="language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.language",
                verbose_name="Idioma",
            ),
        ),
        migrations.AlterField(
            model_name="tocsection",
            name="text",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="For JATs is subject.", max_length=100, null=True
            ),
        ),
        migrations.DeleteModel(
            name="Abstract",
        ),
        migrations.DeleteModel(
            name="AbstractModel",
        ),
        migrations.DeleteModel(
            name="ArticleId",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Title",
        ),
        migrations.AddField(
            model_name="article",
            name="abstracts",
            field=models.ManyToManyField(blank=True, to="article.documentabstract"),
        ),
    ]
