# Generated by Django 4.2.7 on 2023-12-20 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_licensestatement_and_more"),
        ("article", "0004_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="license_statements",
            field=models.ManyToManyField(blank=True, to="core.licensestatement"),
        ),
        migrations.RemoveField(
            model_name="article",
            name="license",
        ),
        migrations.AddField(
            model_name="article",
            name="license",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.license",
            ),
        ),
    ]
