# Generated by Django 4.2.7 on 2024-01-16 23:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0005_remove_article_abstracts_documentabstract_article_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="article_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="first_page",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="last_page",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
