# Generated by Django 4.1.8 on 2023-05-23 17:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0006_rename_pub_date_pub_year_article_pub_date_year_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="volume",
        ),
    ]
