# Generated by Django 4.1.8 on 2023-05-23 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("institution", "0003_alter_institution_acronym_and_more"),
        ("article", "0007_remove_article_volume"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="publisher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="institution.institution",
                verbose_name="Publisher",
            ),
        ),
    ]
