# Generated by Django 4.2.7 on 2024-01-19 23:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0007_article_validate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="elocation_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
