# Generated by Django 4.2.7 on 2024-02-08 16:54

import article.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("article", "0008_alter_article_elocation_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleFormat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "format_name",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Article Format",
                    ),
                ),
                ("version", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=article.models.article_directory_path,
                        verbose_name="Arquivo",
                    ),
                ),
                ("report", models.JSONField(blank=True, null=True)),
                ("valid", models.BooleanField(blank=True, default=None, null=True)),
                (
                    "finger_print",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
            ],
            options={
                "verbose_name": "Article Format",
                "verbose_name_plural": "Article Formats",
            },
        ),
        migrations.RemoveField(
            model_name="subarticle",
            name="article",
        ),
        migrations.RemoveField(
            model_name="subarticle",
            name="article_type",
        ),
        migrations.RemoveField(
            model_name="subarticle",
            name="titles",
        ),
        migrations.AddField(
            model_name="article",
            name="sps_pkg_name",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Package name"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["sps_pkg_name"], name="article_art_sps_pkg_537909_idx"
            ),
        ),
        migrations.DeleteModel(
            name="SubArticle",
        ),
        migrations.AddField(
            model_name="articleformat",
            name="article",
            field=modelcluster.fields.ParentalKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="format",
                to="article.article",
            ),
        ),
        migrations.AddField(
            model_name="articleformat",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AddField(
            model_name="articleformat",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updater",
            ),
        ),
        migrations.AddIndex(
            model_name="articleformat",
            index=models.Index(
                fields=["article"], name="article_art_article_4746f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="articleformat",
            index=models.Index(
                fields=["format_name"], name="article_art_format__4f53da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="articleformat",
            index=models.Index(
                fields=["version"], name="article_art_version_677e28_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="articleformat",
            unique_together={("article", "format_name", "version")},
        ),
    ]
