# Generated by Django 4.1.8 on 2023-06-01 13:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0008_article_publisher"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tocsection",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="tocsection",
            name="language",
        ),
        migrations.RemoveField(
            model_name="tocsection",
            name="updated_by",
        ),
    ]
