# Generated by Django 4.1.8 on 2023-06-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "article",
            "0009_remove_tocsection_creator_remove_tocsection_language_and_more",
        ),
        ("issue", "0008_remove_bibliographicstrip_subtitle_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="toc_sections",
            field=models.ManyToManyField(blank=True, to="issue.tocsection"),
        ),
        migrations.DeleteModel(
            name="TocSection",
        ),
    ]
