# Generated by Django 4.2.7 on 2024-02-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("researcher", "0002_institutionalauthor"),
        ("article", "0009_articleformat_remove_subarticle_article_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="collab",
            field=models.ManyToManyField(
                blank=True, to="researcher.institutionalauthor"
            ),
        ),
    ]
