# Generated by Django 4.2.7 on 2024-03-17 22:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0010_article_collab"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ["-updated", "-created", "sps_pkg_name"]},
        ),
    ]
