# Generated by Django 5.0.3 on 2024-04-19 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0011_alter_article_options"),
        ("institution", "0005_institution_institution_type_scielo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="publisher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="institution.publisher",
                verbose_name="Publisher",
            ),
        ),
    ]
