# Generated by Django 5.0.3 on 2024-05-28 18:09

from django.db import migrations, models

def transfer_license_statements_fk_to_article_license(apps, schema_editor):
    Article = apps.get_model('article', 'Article')

    articles_to_update = []
    for instance in Article.objects.all():

        new_license = None
        if instance.license_statements.exists() and instance.license_statements.first().url:
            new_license = instance.license_statements.first().url
        elif instance.license and instance.license.license_type:
            new_license = instance.license.license_type
        
        if new_license:
            instance.article_license = new_license
            articles_to_update.append(instance)

    if articles_to_update:
        Article.objects.bulk_update(articles_to_update, ['article_license'])


def reverse_transfer_license_statements_fk_to_article_license(apps, schema_editor):
    Article = apps.get_model('article', 'Article')

    articles_to_update = []
    for instance in Article.objects.all():
        instance.article_license = None
        articles_to_update.append(instance)

    if articles_to_update:
        Article.objects.bulk_update(articles_to_update, ['article_license'])

class Migration(migrations.Migration):

    dependencies = [
        ("article", "0012_alter_article_publisher"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="article_license",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(
            transfer_license_statements_fk_to_article_license,
            reverse_transfer_license_statements_fk_to_article_license,
            ),
    ]
