# Generated by Django 5.0.3 on 2024-07-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0012_alter_article_publisher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="pid_v3",
            field=models.CharField(
                blank=True, max_length=23, null=True, unique=True, verbose_name="PID V3"
            ),
        ),
    ]
