# Generated by Django 5.0.3 on 2024-05-31 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0012_alter_article_publisher"),
        ("researcher", "0005_identifier_rawresearcher"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="article_researchers",
            field=models.ManyToManyField(
                blank=True, related_name="raw_researcher", to="researcher.rawresearcher"
            ),
        ),
    ]
