# Generated by Django 5.0.3 on 2024-10-08 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0013_alter_article_pid_v3"),
        ("article", "0013_article_article_license"),
    ]

    operations = []
