# Generated by Django 5.0.3 on 2024-08-23 18:12

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0013_article_article_license"),
    ]

    operations = [
        migrations.AddField(
            model_name="articleformat",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("E", "Error occurred during export format creation"),
                    ("S", "Export format created successfully"),
                    ("A", "Export format available on external site"),
                ],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="articleformat",
            name="article",
            field=modelcluster.fields.ParentalKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="article_format",
                to="article.article",
            ),
        ),
        migrations.AlterField(
            model_name="articleformat",
            name="format_name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("crossref", "Crossref"),
                    ("pubmed", "PubMed"),
                    ("pmc", "PubMed PMC"),
                    ("doaj", "DOAJ"),
                ],
                max_length=20,
                null=True,
                verbose_name="Article Format",
            ),
        ),
    ]
