# Generated by Django 5.0.8 on 2024-12-09 18:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0014_merge_20241008_0012"),
        ("core", "0004_language_core_langua_code2_4f7261_idx"),
        ("doi", "0001_initial"),
        ("institution", "0005_institution_institution_type_scielo_and_more"),
        ("issue", "0003_alter_tocsection_unique_together"),
        ("journal", "0028_journaltocsection_tocitem"),
        ("researcher", "0004_alter_institutionalauthor_unique_together"),
        ("vocabulary", "0003_keyword_html_text"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["id"], name="article_art_id_49c380_idx"),
        ),
    ]
