# Generated by Django 5.0.8 on 2025-01-29 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0015_article_article_art_id_49c380_idx"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="article_license",
        ),
    ]
