# Generated by Django 5.0.8 on 2025-07-02 02:43

import article.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0018_remove_article_article_art_pid_v2_fa7897_idx_and_more"),
        ("core", "0005_alter_language_options_alter_license_options_and_more"),
        ("journal", "0039_journalproxyeditor"),
        ("pid_provider", "0006_pidproviderxml_proc_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="articleformat",
            options={
                "verbose_name": "Article Format",
                "verbose_name_plural": "Article Formats",
            },
        ),
        migrations.AlterField(
            model_name="article",
            name="fundings",
            field=models.ManyToManyField(
                blank=True, to="article.articlefunding", verbose_name="Fundings"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="journal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="journal.journal",
                verbose_name="Journal",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="pub_date_day",
            field=models.CharField(
                blank=True,
                help_text="Dia de publicação no site.",
                max_length=10,
                null=True,
                verbose_name="pub date day",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="pub_date_month",
            field=models.CharField(
                blank=True,
                help_text="Mês de publicação no site.",
                max_length=10,
                null=True,
                verbose_name="pub date month",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="sps_pkg_name",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Package name"
            ),
        ),
        migrations.AlterField(
            model_name="articlecount",
            name="count",
            field=models.IntegerField(blank=True, null=True, verbose_name="Count"),
        ),
        migrations.AlterField(
            model_name="articlecount",
            name="language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.language",
                verbose_name="Language",
            ),
        ),
        migrations.AlterField(
            model_name="articlecounttype",
            name="code",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Code"
            ),
        ),
        migrations.AlterField(
            model_name="articleeventtype",
            name="code",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Code"
            ),
        ),
        migrations.AlterField(
            model_name="articleformat",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=article.models.article_directory_path,
                verbose_name="File",
            ),
        ),
        migrations.AlterField(
            model_name="articleformat",
            name="format_name",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Article Format"
            ),
        ),
        migrations.AlterField(
            model_name="articlefunding",
            name="award_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Award ID"
            ),
        ),
        migrations.AlterField(
            model_name="articletype",
            name="text",
            field=models.TextField(blank=True, null=True, verbose_name="Text"),
        ),
        migrations.CreateModel(
            name="ArticleSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de criação"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data da última atualização"
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="Article URL",
                        null=True,
                        verbose_name="Article URL",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Upload article file",
                        null=True,
                        upload_to=article.models.article_source_path,
                        verbose_name="Article file",
                    ),
                ),
                (
                    "source_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date of data collection or original data date",
                        null=True,
                        verbose_name="Source date",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("error", "Error"),
                            ("reprocess", "Reprocess"),
                        ],
                        default="pending",
                        help_text="Processing status of the article source",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("detail", models.JSONField(blank=True, default=None, null=True)),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related Article instance",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="article.article",
                        verbose_name="Article",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criador",
                    ),
                ),
                (
                    "pid_provider_xml",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related PID Provider XML instance",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pid_provider.pidproviderxml",
                        verbose_name="PID Provider XML",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article Source",
                "verbose_name_plural": "Article Sources",
                "indexes": [
                    models.Index(fields=["url"], name="article_art_url_04bc74_idx"),
                    models.Index(
                        fields=["source_date"], name="article_art_source__ae9570_idx"
                    ),
                    models.Index(
                        fields=["status"], name="article_art_status_15bb5c_idx"
                    ),
                    models.Index(
                        fields=["status", "updated"],
                        name="article_art_status_ede641_idx",
                    ),
                    models.Index(
                        fields=["pid_provider_xml"],
                        name="article_art_pid_pro_c8b36a_idx",
                    ),
                    models.Index(
                        fields=["article"], name="article_art_article_7fee37_idx"
                    ),
                ],
            },
        ),
    ]
