# Generated by Django 5.0.8 on 2025-07-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0019_alter_articleformat_options_alter_article_fundings_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="errors",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
