# Generated by Django 5.0.8 on 2025-07-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0020_article_errors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlesource",
            name="source_date",
            field=models.CharField(
                blank=True,
                help_text="Date of data collection or original data date",
                max_length=10,
                null=True,
                verbose_name="Source date",
            ),
        ),
    ]
