# Generated by Django 5.0.8 on 2025-07-18 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0021_alter_articlesource_source_date"),
        ("collection", "0004_alter_collection_acron2_alter_collection_acron3_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de criação"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data da última atualização"
                    ),
                ),
                (
                    "export_type",
                    models.CharField(
                        choices=[
                            ("articlemeta", "ArticleMeta"),
                            ("crossref", "CrossRef"),
                            ("pubmed", "PubMed"),
                        ],
                        max_length=50,
                        verbose_name="Export Type",
                    ),
                ),
                ("exported_at", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exports",
                        to="article.article",
                        verbose_name="Article",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="collection.collection",
                        verbose_name="Collection",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criador",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizador",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["article", "export_type"],
                        name="article_art_article_241c2b_idx",
                    ),
                    models.Index(
                        fields=["exported_at"], name="article_art_exporte_f9c830_idx"
                    ),
                ],
                "unique_together": {("article", "export_type", "collection")},
            },
        ),
    ]
