# Generated by Django 5.2.3 on 2025-09-25 12:55

import django.db.models.deletion
import modelcluster.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0023_alter_article_created_alter_article_creator_and_more"),
        (
            "collection",
            "0006_alter_collection_options_alter_collection_acron2_and_more",
        ),
        ("core", "0008_exportdestination"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AMArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "data",
                    models.JSONField(blank=True, null=True, verbose_name="JSON File"),
                ),
                (
                    "pid",
                    models.CharField(
                        blank=True, max_length=23, null=True, verbose_name="PID"
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="collection.collection",
                        verbose_name="Collection",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
            options={
                "verbose_name": "Legacy article",
                "verbose_name_plural": "Legacy articles",
            },
        ),
        migrations.AddField(
            model_name="article",
            name="legacy_article",
            field=models.ManyToManyField(to="article.amarticle"),
        ),
        migrations.CreateModel(
            name="ArticleAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                ("url", models.URLField(max_length=500, unique=True)),
                ("available", models.BooleanField(default=False)),
                (
                    "fmt",
                    models.CharField(
                        blank=True, max_length=4, null=True, verbose_name="Format"
                    ),
                ),
                (
                    "article",
                    modelcluster.fields.ParentalKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="article_availability",
                        to="article.article",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ArticleEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                ("detail", models.JSONField(blank=True, null=True)),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                (
                    "article",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="article.article",
                        verbose_name="Article",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article Event",
                "verbose_name_plural": "Article Events",
                "ordering": ["-created", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ArticleExporter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "pid",
                    models.CharField(db_index=True, max_length=24, verbose_name="PID"),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DONE", "done"),
                            ("PENDING", "pending"),
                            ("TODO", "to do"),
                            ("DELETED", "deleted"),
                            ("WIP", "in progress"),
                        ],
                        default="TODO",
                        max_length=15,
                        null=True,
                        verbose_name="Status",
                    ),
                ),
                ("detail", models.JSONField(blank=True, null=True)),
                (
                    "version",
                    models.CharField(
                        blank=True, max_length=26, null=True, verbose_name="Version"
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="collection.collection",
                        verbose_name="Collection",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.exportdestination",
                        verbose_name="Destination",
                    ),
                ),
                (
                    "parent",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exporter",
                        to="article.article",
                        verbose_name="Article",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="ArticleExport",
        ),
        migrations.AddIndex(
            model_name="amarticle",
            index=models.Index(fields=["pid"], name="article_ama_pid_afffac_idx"),
        ),
        migrations.AddIndex(
            model_name="articleevent",
            index=models.Index(
                fields=["article", "-created"], name="article_art_article_712b5c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="articleevent",
            index=models.Index(fields=["name"], name="article_art_name_059f3e_idx"),
        ),
        migrations.AddIndex(
            model_name="articleevent",
            index=models.Index(
                fields=["created"], name="article_art_created_9dd64b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="articleexporter",
            index=models.Index(
                fields=["pid", "destination", "collection"],
                name="article_art_pid_ceef3f_idx",
            ),
        ),
    ]
