# Generated by Django 5.2.3 on 2025-09-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "article",
            "0024_amarticle_article_legacy_article_articleavailability_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="data_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PUBLIC", "public"),
                    ("PENDING", "pending"),
                    ("MOVED", "moved"),
                    ("DELETED", "deleted"),
                    ("UNDEF", "undefined"),
                    ("NVALID", "invalid"),
                ],
                default="UNDEF",
                max_length=15,
                null=True,
                verbose_name="Data status",
            ),
        ),
    ]
