# Generated by Django 5.2.3 on 2025-09-29 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0026_articleavailability_collection_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="articleavailability",
            old_name="language",
            new_name="lang",
        ),
    ]
