# Generated by Django 5.2.3 on 2025-10-02 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0027_rename_language_articleavailability_lang"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="articlesource",
            name="article_art_article_7fee37_idx",
        ),
        migrations.RemoveField(
            model_name="articlesource",
            name="article",
        ),
        migrations.AddField(
            model_name="articlesource",
            name="am_article",
            field=models.ForeignKey(
                blank=True,
                help_text="Related Legacy Article instance",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="article.amarticle",
                verbose_name="Legacy Article",
            ),
        ),
    ]
