# Generated by Django 5.2.3 on 2025-10-07 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "article",
            "0028_remove_articlesource_article_art_article_7fee37_idx_and_more",
        ),
        (
            "collection",
            "0006_alter_collection_options_alter_collection_acron2_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="amarticle",
            name="processing_date",
            field=models.CharField(
                blank=True,
                help_text="Date in YYYY-MM-DD format",
                max_length=10,
                null=True,
                verbose_name="Processing Date",
            ),
        ),
        migrations.AddField(
            model_name="amarticle",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("pending", "Pending"), ("todo", "To Do"), ("done", "Done")],
                default="todo",
                max_length=10,
                null=True,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="amarticle",
            name="collection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="collection.collection",
                verbose_name="Collection",
            ),
        ),
    ]
