# Generated by Django 5.2.3 on 2025-10-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0029_amarticle_processing_date_amarticle_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="amarticle",
            name="url",
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
