# Generated by Django 5.2.3 on 2025-10-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0031_alter_article_data_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="is_public",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
