# Generated by Django 5.2.3 on 2025-10-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0032_article_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="articleavailability",
            name="error",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
