# Generated by Django 5.2.3 on 2025-10-19 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0033_articleavailability_error"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="data_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PUBLIC", "public"),
                    ("PENDING", "pending"),
                    ("MOVED", "moved"),
                    ("DELETED", "deleted"),
                    ("UNDEF", "undefined"),
                    ("NVALID", "invalid"),
                    ("COMPLET", "completed"),
                    ("DUP", "duplicated"),
                    ("DEDUP", "deduplicated"),
                ],
                default="UNDEF",
                max_length=15,
                null=True,
                verbose_name="Data status",
            ),
        ),
    ]
