# Generated by Django 5.2.3 on 2025-10-23 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0034_alter_article_data_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="legacy_article",
        ),
        migrations.AddField(
            model_name="amarticle",
            name="new_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="legacy_article",
                to="article.article",
            ),
        ),
    ]
