# Generated by Django 5.2.3 on 2025-10-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0035_remove_article_legacy_article_amarticle_new_record"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="is_classic_public",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="is_new_public",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
