# Generated by Django 5.2.3 on 2025-11-05 21:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0036_article_is_classic_public_article_is_new_public"),
        ("collection", "0007_collection_platform_status"),
        ("core", "0008_exportdestination"),
        ("doi", "0003_alter_doi_created_alter_doi_creator_and_more"),
        ("issue", "0017_remove_issue_legacy_issue_amissue_new_record"),
        ("journal", "0053_alter_scielojournal_journal_acron"),
        (
            "pid_provider",
            "0014_remove_xmlversion_pid_provide_pid_pro_91cb7b_idx_and_more",
        ),
        (
            "researcher",
            "0009_alter_affiliation_created_alter_affiliation_creator_and_more",
        ),
        ("vocabulary", "0005_alter_keyword_created_alter_keyword_creator_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["pid_v2"], name="article_art_pid_v2_fa7897_idx"),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["is_classic_public"], name="article_art_is_clas_a2af3c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["pp_xml"], name="article_art_pp_xml__baab3c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="articleavailability",
            index=models.Index(
                fields=["article", "available"], name="article_art_article_2a0b89_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="articleavailability",
            index=models.Index(
                fields=["article", "collection", "fmt"],
                name="article_art_article_9a77ea_idx",
            ),
        ),
    ]
