# Generated by Django 5.2.7 on 2025-11-13 10:43

import django.db.models.deletion
import modelcluster.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0037_article_article_art_pid_v2_fa7897_idx_and_more"),
        ("core", "0008_exportdestination"),
        ("doi", "0003_alter_doi_created_alter_doi_creator_and_more"),
        ("issue", "0019_issue_issue_issue_markup__3bbf4a_idx"),
        ("journal", "0053_alter_scielojournal_journal_acron"),
        (
            "pid_provider",
            "0014_remove_xmlversion_pid_provide_pid_pro_91cb7b_idx_and_more",
        ),
        (
            "researcher",
            "0009_alter_affiliation_created_alter_affiliation_creator_and_more",
        ),
        ("vocabulary", "0005_alter_keyword_created_alter_keyword_creator_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataAvailabilityStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Text"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="ArticleType",
        ),
        migrations.AddField(
            model_name="article",
            name="data_availability_status",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "data-available",
                        "Os dados de pesquisa estão disponíveis em repositório.",
                    ),
                    (
                        "data-available-upon-request",
                        "Os dados de pesquisa só estão disponíveis mediante solicitação.",
                    ),
                    (
                        "data-in-article",
                        "Os dados de pesquisa estão disponíveis no corpo do documento.",
                    ),
                    (
                        "data-not-available",
                        "Os dados de pesquisa não estão disponíveis.",
                    ),
                    (
                        "uninformed",
                        "Uso de dados não informado; nenhum dado de pesquisa gerado ou utilizado.",
                    ),
                    ("absent", "Informação ausente no XML"),
                    ("not-processed", "XML não processado"),
                ],
                default="not-processed",
                max_length=30,
                null=True,
                verbose_name="Data Availability Status",
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["data_availability_status"],
                name="article_art_data_av_aa24c2_idx",
            ),
        ),
        migrations.AddField(
            model_name="dataavailabilitystatement",
            name="article",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data_availability_statements",
                to="article.article",
            ),
        ),
        migrations.AddField(
            model_name="dataavailabilitystatement",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AddField(
            model_name="dataavailabilitystatement",
            name="language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.language",
                verbose_name="Language",
            ),
        ),
        migrations.AddField(
            model_name="dataavailabilitystatement",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updater",
            ),
        ),
    ]
