# Generated by Django 5.2.7 on 2025-11-15 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0038_dataavailabilitystatement_delete_articletype_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="toc_sections",
        ),
    ]
