# Generated by Django 5.2.7 on 2025-11-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0039_remove_article_toc_sections"),
        ("issue", "0020_tableofcontents_remove_codesectionissue_creator_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="sections",
            field=models.ManyToManyField(blank=True, to="issue.tableofcontents"),
        ),
    ]
