# Generated by Django 5.2.7 on 2025-11-15 22:34

import django.db.models.deletion
import modelcluster.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0040_article_sections"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RelatedArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "href",
                    models.CharField(
                        help_text="Digital Object Identifier of the related article.",
                        max_length=255,
                        verbose_name="DOI",
                    ),
                ),
                (
                    "ext_link_type",
                    models.CharField(
                        help_text="Type of external link.",
                        max_length=3,
                        verbose_name="Link Type",
                    ),
                ),
                (
                    "related_type",
                    models.CharField(
                        choices=[
                            ("corrected-article", "Errata"),
                            ("correction-forward", "Documento corrigido pela errata"),
                            ("retracted-article", "Retratação total"),
                            ("retraction-forward", "Documento retratado totalmente"),
                            ("partial-retraction", "Retratação parcial"),
                            (
                                "partial-retraction-forward",
                                "Documento retratado parcialmente",
                            ),
                            ("addended-article", "Adendo"),
                            ("addendum", "Documento objeto do adendo"),
                            ("expression-of-concern", "Manifestação de preocupação"),
                            (
                                "object-of-concern",
                                "Documento objeto de manifestação de preocupação",
                            ),
                            ("commentary-article", "Comentário"),
                            ("commentary", "Documento comentado"),
                            ("reply-to-commentary", "Resposta para um comentário"),
                            (
                                "commentary-reply-object",
                                "Comentário objeto da resposta",
                            ),
                            ("letter", "Carta"),
                            ("letter-object", "Documento a que se refere a carta"),
                            ("reply-to-letter", "Resposta para uma carta"),
                            ("letter-reply-object", "Carta objeto da resposta"),
                            ("reviewed-article", "Parecer (revisão por pares)"),
                            (
                                "reviewer-report",
                                "Documento com parecer (revisão por pares)",
                            ),
                            (
                                "preprint",
                                "Manuscrito disponibilizado em acesso aberto em servidor de preprints",
                            ),
                            (
                                "published-article",
                                "Artigo publicado baseado no preprint",
                            ),
                        ],
                        help_text="Type of relationship between articles.",
                        max_length=50,
                        verbose_name="Related Article Type",
                    ),
                ),
                (
                    "article",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_articles",
                        to="article.article",
                        verbose_name="Article",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "related_article",
                    models.ForeignKey(
                        blank=True,
                        help_text="The related article instance, if available in the system.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="target_relations",
                        to="article.article",
                        verbose_name="Related Article",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
            options={
                "verbose_name": "Related Article",
                "verbose_name_plural": "Related Articles",
                "indexes": [
                    models.Index(
                        fields=["article", "href", "related_type"],
                        name="article_rel_article_09c615_idx",
                    ),
                    models.Index(fields=["href"], name="article_rel_href_fa6f6f_idx"),
                ],
                "unique_together": {("article", "href", "related_type")},
            },
        ),
    ]
