# Generated by Django 5.2.7 on 2025-11-18 01:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0041_relatedarticle"),
        ("core", "0008_exportdestination"),
        ("doi", "0003_alter_doi_created_alter_doi_creator_and_more"),
        ("issue", "0021_tableofcontents_journal_toc_and_more"),
        ("journal", "0054_journaltableofcontents"),
        (
            "pid_provider",
            "0014_remove_xmlversion_pid_provide_pid_pro_91cb7b_idx_and_more",
        ),
        (
            "researcher",
            "0009_alter_affiliation_created_alter_affiliation_creator_and_more",
        ),
        ("vocabulary", "0005_alter_keyword_created_alter_keyword_creator_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticlePeerReviewStats",
            fields=[],
            options={
                "verbose_name": "Peer Review Stats",
                "verbose_name_plural": "Peer Review Stats",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("article.article",),
        ),
        migrations.AddField(
            model_name="article",
            name="accepted_dateiso",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="days_accepted_to_published",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="days_accepted_to_published_estimated",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="days_preprint_to_published",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="days_preprint_to_published_estimated",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="days_preprint_to_received",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="days_preprint_to_received_estimated",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="days_receive_to_published",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="days_receive_to_published_estimated",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="days_received_to_accepted",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="days_received_to_accepted_estimated",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="peer_review_stats",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Todas as datas e intervalos do processo de revisão por pares",
                verbose_name="Peer review statistics",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="preprint_dateiso",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="received_dateiso",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["article_type"], name="article_art_article_6e1e55_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["days_preprint_to_received"],
                name="article_art_days_pr_6211e7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["days_received_to_accepted"],
                name="article_art_days_re_a672fb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["days_accepted_to_published"],
                name="article_art_days_ac_75464d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["days_preprint_to_published"],
                name="article_art_days_pr_cc0d64_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["days_receive_to_published"],
                name="article_art_days_re_c96316_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["days_preprint_to_received_estimated"],
                name="article_art_days_pr_ac8340_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["days_received_to_accepted_estimated"],
                name="article_art_days_re_46895c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["days_accepted_to_published_estimated"],
                name="article_art_days_ac_158637_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["days_preprint_to_published_estimated"],
                name="article_art_days_pr_18a699_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["days_receive_to_published_estimated"],
                name="article_art_days_re_85fc4a_idx",
            ),
        ),
    ]
