# Generated by Django 5.2.7 on 2025-11-18 11:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0042_articlepeerreviewstats_article_accepted_dateiso_and_more"),
        ("core", "0008_exportdestination"),
        ("doi", "0003_alter_doi_created_alter_doi_creator_and_more"),
        ("issue", "0021_tableofcontents_journal_toc_and_more"),
        ("journal", "0054_journaltableofcontents"),
        (
            "pid_provider",
            "0014_remove_xmlversion_pid_provide_pid_pro_91cb7b_idx_and_more",
        ),
        (
            "researcher",
            "0009_alter_affiliation_created_alter_affiliation_creator_and_more",
        ),
        ("vocabulary", "0005_alter_keyword_created_alter_keyword_creator_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="article",
            name="article_art_days_pr_ac8340_idx",
        ),
        migrations.RemoveIndex(
            model_name="article",
            name="article_art_days_re_46895c_idx",
        ),
        migrations.RemoveIndex(
            model_name="article",
            name="article_art_days_ac_158637_idx",
        ),
        migrations.RemoveIndex(
            model_name="article",
            name="article_art_days_pr_18a699_idx",
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["is_new_public"], name="article_art_is_new__90659e_idx"
            ),
        ),
    ]
