# Generated by Django 5.2.7 on 2025-11-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0043_remove_article_article_art_days_pr_ac8340_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="accepted_dateiso",
            field=models.CharField(
                blank=True,
                help_text="Date the article was accepted, in ISO format (YYYY-MM-DD)",
                max_length=10,
                null=True,
                verbose_name="Accepted Date (ISO)",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="preprint_dateiso",
            field=models.CharField(
                blank=True,
                help_text="Preprint publication date in ISO format (YYYY-MM-DD)",
                max_length=10,
                null=True,
                verbose_name="Preprint Date (ISO)",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="received_dateiso",
            field=models.CharField(
                blank=True,
                help_text="Date the article was received, in ISO format (YYYY-MM-DD)",
                max_length=10,
                null=True,
                verbose_name="Received Date (ISO)",
            ),
        ),
    ]
