# Generated by Django 5.2.7 on 2026-01-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0044_alter_article_accepted_dateiso_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="invalid_data_availability_status",
            field=models.CharField(
                blank=True,
                help_text="Armazena valores inválidos recebidos do XML",
                max_length=255,
                null=True,
                verbose_name="Invalid data availability status from XML",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="data_availability_status",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "data-available",
                        "Os dados de pesquisa estão disponíveis em repositório.",
                    ),
                    (
                        "data-available-upon-request",
                        "Os dados de pesquisa só estão disponíveis mediante solicitação.",
                    ),
                    (
                        "data-in-article",
                        "Os dados de pesquisa estão disponíveis no corpo do documento.",
                    ),
                    (
                        "data-not-available",
                        "Os dados de pesquisa não estão disponíveis.",
                    ),
                    (
                        "uninformed",
                        "Uso de dados não informado; nenhum dado de pesquisa gerado ou utilizado.",
                    ),
                    ("absent", "Informação ausente no XML"),
                    ("not-processed", "XML não processado"),
                    ("invalid", "Valor inválido recebido do XML"),
                ],
                default="not-processed",
                max_length=30,
                null=True,
                verbose_name="Data Availability Status",
            ),
        ),
    ]
