# Generated by Django 5.2.7 on 2026-02-24 23:02

import django.db.models.deletion
import modelcluster.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0045_article_invalid_data_availability_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContribCollab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "collab",
                    models.CharField(
                        blank=True,
                        help_text="Name of the research group, consortium, or collaborative initiative",
                        max_length=255,
                        null=True,
                        verbose_name="Collaboration",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContribPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "given_names",
                    models.CharField(
                        max_length=128, null=True, verbose_name="Given names"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=64, null=True, verbose_name="Last name"
                    ),
                ),
                (
                    "suffix",
                    models.CharField(
                        blank=True, max_length=16, null=True, verbose_name="Suffix"
                    ),
                ),
                (
                    "fullname",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Full Name"
                    ),
                ),
                (
                    "declared_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Declared Name",
                    ),
                ),
                (
                    "orcid",
                    models.CharField(
                        blank=True,
                        help_text="ORCID identifier (e.g., 0000-0002-1825-0097)",
                        max_length=19,
                        null=True,
                        verbose_name="ORCID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="article",
            name="collab",
        ),
        migrations.RemoveField(
            model_name="article",
            name="researchers",
        ),
        migrations.CreateModel(
            name="ArticleAffiliation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "raw_text",
                    models.TextField(
                        blank=True,
                        help_text="Free text, unstructured organization data",
                        null=True,
                        verbose_name="Raw Text",
                    ),
                ),
                (
                    "raw_institution_name",
                    models.CharField(
                        blank=True,
                        help_text="Raw institution name as provided",
                        max_length=510,
                        null=True,
                        verbose_name="Raw Institution Name",
                    ),
                ),
                (
                    "raw_country_name",
                    models.CharField(
                        blank=True,
                        help_text="Raw country name as provided",
                        max_length=255,
                        null=True,
                        verbose_name="Raw Country Name",
                    ),
                ),
                (
                    "raw_country_code",
                    models.CharField(
                        blank=True,
                        help_text="Raw country code (ISO) as provided",
                        max_length=3,
                        null=True,
                        verbose_name="Raw Country Code",
                    ),
                ),
                (
                    "raw_state_name",
                    models.CharField(
                        blank=True,
                        help_text="Raw state name as provided",
                        max_length=255,
                        null=True,
                        verbose_name="Raw State Name",
                    ),
                ),
                (
                    "raw_state_acron",
                    models.CharField(
                        blank=True,
                        help_text="Raw state acronym as provided",
                        max_length=10,
                        null=True,
                        verbose_name="Raw State Acronym",
                    ),
                ),
                (
                    "raw_city_name",
                    models.CharField(
                        blank=True,
                        help_text="Raw city name as provided",
                        max_length=255,
                        null=True,
                        verbose_name="Raw City Name",
                    ),
                ),
                (
                    "raw_level_1",
                    models.CharField(
                        blank=True,
                        help_text="Raw first level of organization division",
                        max_length=255,
                        null=True,
                        verbose_name="Raw Level 1",
                    ),
                ),
                (
                    "raw_level_2",
                    models.CharField(
                        blank=True,
                        help_text="Raw second level of organization division",
                        max_length=255,
                        null=True,
                        verbose_name="Raw Level 2",
                    ),
                ),
                (
                    "raw_level_3",
                    models.CharField(
                        blank=True,
                        help_text="Raw third level of organization division",
                        max_length=255,
                        null=True,
                        verbose_name="Raw Level 3",
                    ),
                ),
                (
                    "article",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affiliations",
                        to="article.article",
                        verbose_name="Article",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
            ],
        ),
    ]
