# Generated by Django 5.2.7 on 2026-02-24 23:02

import django.db.models.deletion
import modelcluster.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0046_contribcollab_contribperson_remove_article_collab_and_more"),
        ("organization", "0011_normaffiliation_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="articleaffiliation",
            name="normalized",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to normalized affiliation data",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="organization.normaffiliation",
                verbose_name="Normalized Affiliation",
            ),
        ),
        migrations.AddField(
            model_name="articleaffiliation",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Structured organization reference",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="organization.organization",
                verbose_name="Organization",
            ),
        ),
        migrations.AddField(
            model_name="articleaffiliation",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updater",
            ),
        ),
        migrations.AddField(
            model_name="contribcollab",
            name="affiliation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contrib_collabs",
                to="article.articleaffiliation",
                verbose_name="Affiliation",
            ),
        ),
        migrations.AddField(
            model_name="contribcollab",
            name="article",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contrib_collabs",
                to="article.article",
                verbose_name="Article",
            ),
        ),
        migrations.AddField(
            model_name="contribcollab",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AddField(
            model_name="contribcollab",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updater",
            ),
        ),
        migrations.AddField(
            model_name="contribperson",
            name="affiliation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contrib_persons",
                to="article.articleaffiliation",
                verbose_name="Affiliation",
            ),
        ),
        migrations.AddField(
            model_name="contribperson",
            name="article",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contrib_persons",
                to="article.article",
                verbose_name="Article",
            ),
        ),
        migrations.AddField(
            model_name="contribperson",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AddField(
            model_name="contribperson",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updater",
            ),
        ),
        migrations.AddIndex(
            model_name="articleaffiliation",
            index=models.Index(
                fields=["article"], name="article_art_article_53413a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="articleaffiliation",
            index=models.Index(
                fields=["organization"], name="article_art_organiz_8a7a33_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="articleaffiliation",
            index=models.Index(
                fields=["normalized"], name="article_art_normali_b14bcd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="articleaffiliation",
            index=models.Index(
                fields=["article", "organization"],
                name="article_art_article_b6ca44_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contribcollab",
            index=models.Index(
                fields=["article"], name="article_con_article_fc26bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contribcollab",
            index=models.Index(
                fields=["affiliation"], name="article_con_affilia_6c81a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contribperson",
            index=models.Index(
                fields=["article"], name="article_con_article_c9f2d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contribperson",
            index=models.Index(
                fields=["affiliation"], name="article_con_affilia_d26c03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contribperson",
            index=models.Index(fields=["orcid"], name="article_con_orcid_53f6c7_idx"),
        ),
    ]
