# Generated by Django 5.2.7 on 2026-03-10 19:57

import django.db.models.deletion
import modelcluster.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0047_articleaffiliation_normalized_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleEditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('name', models.CharField(blank=True, help_text="Editor's name (may be unstructured)", max_length=255, null=True, verbose_name='Name')),
                ('orcid', models.CharField(blank=True, help_text='ORCID identifier (e.g., 0000-0002-1825-0097)', max_length=19, null=True, verbose_name='ORCID')),
                ('role', models.CharField(blank=True, help_text="Editor's role (e.g., editor, academic-editor, section-editor)", max_length=255, null=True, verbose_name='Role')),
                ('institution', models.CharField(blank=True, help_text="Editor's institution (semi-structured)", max_length=510, null=True, verbose_name='Institution')),
                ('article', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='editors', to='article.article', verbose_name='Article')),
                ('creator', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
            ],
            options={
                'indexes': [models.Index(fields=['article'], name='article_art_article_c307ab_idx'), models.Index(fields=['orcid'], name='article_art_orcid_b168f1_idx')],
            },
        ),
    ]
