# Generated by Django 5.2.7 on 2026-03-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0047_articleaffiliation_normalized_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlesource",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("error", "Error"),
                    ("reprocess", "Reprocess"),
                    ("url_error", "URL Error"),
                    ("xml_error", "XML Error"),
                ],
                default="pending",
                help_text="Processing status of the article source",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
