# Generated by Django 5.2.7 on 2026-07-27 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0049_alter_articlesource_status"),
        ("collection", "0007_collection_platform_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articlesource",
            name="am_article",
        ),
        migrations.AddField(
            model_name="articlesource",
            name="collection",
            field=models.ForeignKey(
                blank=True,
                help_text="Related Collection instance",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="collection.collection",
                verbose_name="Collection",
            ),
        ),
        migrations.AddField(
            model_name="articlesource",
            name="pid",
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
