# Generated by Django 4.1.10 on 2023-09-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("researcher", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="researcher",
            index=models.Index(
                fields=["given_names"], name="researcher__given_n_f2aee1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="researcher",
            index=models.Index(
                fields=["last_name"], name="researcher__last_na_a59bdf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="researcher",
            index=models.Index(fields=["orcid"], name="researcher__orcid_80fdd3_idx"),
        ),
        migrations.AddIndex(
            model_name="researcher",
            index=models.Index(fields=["lattes"], name="researcher__lattes_bcc84d_idx"),
        ),
    ]
