# Generated by Django 3.2.12 on 2023-01-23 15:45

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
        ('researcher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldAffiliation',
            fields=[
                ('institutionhistory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='institution.institutionhistory')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=('institution.institutionhistory', models.Model),
        ),
        migrations.CreateModel(
            name='FieldEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('email', models.EmailField(blank=True, max_length=128, null=True, verbose_name='Email')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='affiliations',
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='email',
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='surname',
        ),
        migrations.AddField(
            model_name='researcher',
            name='gender',
            field=models.CharField(choices=[('F', 'Mujer'), ('M', 'Hombre')], default='F', max_length=255, verbose_name='Gender'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researcher',
            name='gender_identification_status',
            field=models.CharField(choices=[('DECLARED', 'Declarado por el investigador'), ('AUTOMATIC', 'Identificado automáticamente por programa de computador'), ('MANUAL', 'Identificado por algun usuario')], default='AUTOMATIC', max_length=255, verbose_name='Gender identification status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researcher',
            name='last_name',
            field=models.CharField(default='', max_length=128, verbose_name='Last name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researcher',
            name='lattes',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Lattes'),
        ),
        migrations.DeleteModel(
            name='ResearcherAffiliation',
        ),
        migrations.AddField(
            model_name='fieldemail',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_email', to='researcher.researcher'),
        ),
        migrations.AddField(
            model_name='fieldaffiliation',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliation', to='researcher.researcher'),
        ),
    ]
