# Generated by Django 4.2.6 on 2023-11-13 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("institution", "0002_initial"),
        ("researcher", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Affiliation",
            fields=[
                (
                    "institution_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="institution.institution",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("institution.institution",),
        ),
        migrations.CreateModel(
            name="AffiliationHistoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "initial_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Initial Date"
                    ),
                ),
                (
                    "final_date",
                    models.DateField(blank=True, null=True, verbose_name="Final Date"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrcidModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "orcid",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="ORCID"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PersonName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "declared_name",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Declared Name",
                    ),
                ),
                (
                    "given_names",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Given names",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="Last name"
                    ),
                ),
                (
                    "suffix",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="Suffix"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResearcherEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=128, null=True, verbose_name="Email"
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="fieldaffiliation",
            name="institutionhistory_ptr",
        ),
        migrations.RemoveField(
            model_name="fieldaffiliation",
            name="page",
        ),
        migrations.RemoveField(
            model_name="fieldemail",
            name="page",
        ),
        migrations.RemoveIndex(
            model_name="researcher",
            name="researcher__given_n_f2aee1_idx",
        ),
        migrations.RemoveIndex(
            model_name="researcher",
            name="researcher__last_na_a59bdf_idx",
        ),
        migrations.RemoveIndex(
            model_name="researcher",
            name="researcher__orcid_80fdd3_idx",
        ),
        migrations.RemoveField(
            model_name="researcher",
            name="declared_name",
        ),
        migrations.RemoveField(
            model_name="researcher",
            name="given_names",
        ),
        migrations.RemoveField(
            model_name="researcher",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="researcher",
            name="suffix",
        ),
        migrations.AlterField(
            model_name="researcher",
            name="gender_identification_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DECLARED", "Declarado por el investigador"),
                    (
                        "AUTOMATIC",
                        "Identificado automáticamente por programa de computador",
                    ),
                    ("MANUAL", "Identificado por algun usuario"),
                ],
                max_length=16,
                null=True,
                verbose_name="Gender identification status",
            ),
        ),
        migrations.AlterField(
            model_name="researcher",
            name="lattes",
            field=models.URLField(
                blank=True, max_length=256, null=True, verbose_name="Lattes"
            ),
        ),
        migrations.CreateModel(
            name="AffiliationHistory",
            fields=[
                (
                    "affiliationhistoryitem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="researcher.affiliationhistoryitem",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
            bases=("researcher.affiliationhistoryitem", models.Model),
        ),
        migrations.DeleteModel(
            name="FieldAffiliation",
        ),
        migrations.DeleteModel(
            name="FieldEmail",
        ),
        migrations.AddField(
            model_name="researcheremail",
            name="researcher",
            field=modelcluster.fields.ParentalKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="researcher_email",
                to="researcher.researcher",
            ),
        ),
        migrations.AddField(
            model_name="personname",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AddField(
            model_name="personname",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updater",
            ),
        ),
        migrations.AddField(
            model_name="orcidmodel",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AddField(
            model_name="orcidmodel",
            name="person_names",
            field=models.ManyToManyField(to="researcher.personname"),
        ),
        migrations.AddField(
            model_name="orcidmodel",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updater",
            ),
        ),
        migrations.AddField(
            model_name="affiliationhistoryitem",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AddField(
            model_name="affiliationhistoryitem",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="researcher.affiliation",
            ),
        ),
        migrations.AddField(
            model_name="affiliationhistoryitem",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updater",
            ),
        ),
        migrations.AddField(
            model_name="researcher",
            name="person_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="researcher.personname",
            ),
        ),
        migrations.AlterField(
            model_name="researcher",
            name="orcid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="researcher.orcidmodel",
            ),
        ),
        migrations.AddIndex(
            model_name="personname",
            index=models.Index(
                fields=["given_names"], name="researcher__given_n_f26a37_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="personname",
            index=models.Index(
                fields=["last_name"], name="researcher__last_na_4ba2b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="personname",
            index=models.Index(
                fields=["declared_name"], name="researcher__declare_95a8e7_idx"
            ),
        ),
        migrations.AddField(
            model_name="affiliationhistory",
            name="researcher",
            field=modelcluster.fields.ParentalKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="researcher_affiliation",
                to="researcher.researcher",
            ),
        ),
    ]
