# Generated by Django 4.2.7 on 2023-12-20 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("researcher", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="researcher",
            name="researcher__year_b9902c_idx",
        ),
        migrations.AlterUniqueTogether(
            name="researcher",
            unique_together={("person_name", "affiliation")},
        ),
        migrations.AddIndex(
            model_name="researcher",
            index=models.Index(
                fields=["person_name"], name="researcher__person__17eac0_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="researcher",
            name="year",
        ),
    ]
