# Generated by Django 4.2.7 on 2024-03-01 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("researcher", "0002_institutionalauthor"),
    ]

    operations = [
        migrations.AddField(
            model_name="institutionalauthor",
            name="affiliation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="researcher.affiliation",
            ),
        ),
    ]
