# Generated by Django 4.2.7 on 2023-12-08 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("institution", "0003_institutionidentification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("researcher", "0002_researcheridentifier_personname"),
    ]

    operations = [
        migrations.CreateModel(
            name="Affiliation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResearcherAKA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="fieldaffiliation",
            name="institutionhistory_ptr",
        ),
        migrations.RemoveField(
            model_name="fieldaffiliation",
            name="page",
        ),
        migrations.RemoveField(
            model_name="fieldemail",
            name="page",
        ),
        migrations.RemoveIndex(
            model_name="researcher",
            name="researcher__given_n_f2aee1_idx",
        ),
        migrations.RemoveIndex(
            model_name="researcher",
            name="researcher__last_na_a59bdf_idx",
        ),
        migrations.RemoveIndex(
            model_name="researcher",
            name="researcher__orcid_80fdd3_idx",
        ),
        migrations.RemoveIndex(
            model_name="researcher",
            name="researcher__lattes_bcc84d_idx",
        ),
        migrations.AlterUniqueTogether(
            name="personname",
            unique_together={("fullname", "last_name", "given_names", "suffix")},
        ),
        migrations.AddField(
            model_name="personname",
            name="declared_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Declared Name"
            ),
        ),
        migrations.AddField(
            model_name="personname",
            name="gender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.gender",
            ),
        ),
        migrations.AddField(
            model_name="personname",
            name="gender_identification_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DECLARED", "Declarado por el investigador"),
                    (
                        "AUTOMATIC",
                        "Identificado automáticamente por programa de computador",
                    ),
                    ("MANUAL", "Identificado por algun usuario"),
                ],
                max_length=255,
                null=True,
                verbose_name="Gender identification status",
            ),
        ),
        migrations.AddField(
            model_name="researcher",
            name="person_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="researcher.personname",
            ),
        ),
        migrations.AddField(
            model_name="researcher",
            name="year",
            field=models.CharField(
                blank=True, max_length=4, null=True, verbose_name="Year"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="personname",
            unique_together={
                ("fullname", "last_name", "given_names", "suffix"),
                ("declared_name",),
            },
        ),
        migrations.AddIndex(
            model_name="personname",
            index=models.Index(
                fields=["declared_name"], name="researcher__declare_95a8e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="researcher",
            index=models.Index(fields=["year"], name="researcher__year_b9902c_idx"),
        ),
        migrations.DeleteModel(
            name="FieldAffiliation",
        ),
        migrations.DeleteModel(
            name="FieldEmail",
        ),
        migrations.AddField(
            model_name="researcheraka",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AddField(
            model_name="researcheraka",
            name="researcher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="researcher.researcher",
            ),
        ),
        migrations.AddField(
            model_name="researcheraka",
            name="researcher_identifier",
            field=modelcluster.fields.ParentalKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="researcher_also_known_as",
                to="researcher.researcheridentifier",
            ),
        ),
        migrations.AddField(
            model_name="researcheraka",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updater",
            ),
        ),
        migrations.AddField(
            model_name="affiliation",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AddField(
            model_name="affiliation",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="institution.institution",
            ),
        ),
        migrations.AddField(
            model_name="affiliation",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updater",
            ),
        ),
        migrations.AddField(
            model_name="researcher",
            name="affiliation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="researcher.affiliation",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="researcher",
            unique_together={("person_name", "year", "affiliation")},
        ),
        migrations.AlterUniqueTogether(
            name="affiliation",
            unique_together={("institution",)},
        ),
        migrations.RemoveField(
            model_name="researcher",
            name="declared_name",
        ),
        migrations.RemoveField(
            model_name="researcher",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="researcher",
            name="gender_identification_status",
        ),
        migrations.RemoveField(
            model_name="researcher",
            name="given_names",
        ),
        migrations.RemoveField(
            model_name="researcher",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="researcher",
            name="lattes",
        ),
        migrations.RemoveField(
            model_name="researcher",
            name="orcid",
        ),
        migrations.RemoveField(
            model_name="researcher",
            name="suffix",
        ),
    ]
