# Generated by Django 4.2.7 on 2024-03-01 01:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("researcher", "0003_institutionalauthor_affiliation"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="institutionalauthor",
            unique_together={("collab", "affiliation")},
        ),
    ]
