# Generated by Django 4.1.6 on 2023-03-08 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_gender"),
        ("researcher", "0004_alter_researcher_creator_alter_researcher_updated_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="researcher",
            name="gender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.gender",
            ),
        ),
    ]
