# Generated by Django 4.1.6 on 2023-03-08 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_genderidentificationstatus"),
        ("researcher", "0005_alter_researcher_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="researcher",
            name="gender_identification_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.genderidentificationstatus",
            ),
        ),
    ]
