# Generated by Django 5.0.3 on 2024-05-31 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researcher", "0005_identifier_rawresearcher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawresearcher",
            name="orcid",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name="Identifier",
        ),
    ]
