# Generated by Django 5.0.8 on 2025-05-19 17:44

import django.db.models.deletion
import modelcluster.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0003_alter_organization_acronym_and_more"),
        ("researcher", "0005_newresearcher_researcherids_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="newresearcher",
            name="affiliation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="organization.organization",
            ),
        ),
        migrations.AlterField(
            model_name="newresearcher",
            name="fullname",
            field=models.TextField(null=True, verbose_name="Full Name"),
        ),
        migrations.AlterField(
            model_name="newresearcher",
            name="given_names",
            field=models.CharField(
                max_length=128, null=True, verbose_name="Given names"
            ),
        ),
        migrations.AlterField(
            model_name="newresearcher",
            name="last_name",
            field=models.CharField(max_length=64, null=True, verbose_name="Last name"),
        ),
        migrations.AlterField(
            model_name="researcherids",
            name="source_name",
            field=models.CharField(
                blank=True,
                choices=[("LATTES", "LATTES"), ("EMAIL", "Email")],
                max_length=64,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ResearcherOrcid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                ("orcid", models.CharField(max_length=64, null=True, unique=True)),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="newresearcher",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="newresearcher",
            name="orcid",
            field=modelcluster.fields.ParentalKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="researcher_orcid",
                to="researcher.researcherorcid",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="newresearcher",
            unique_together={
                ("fullname", "last_name", "given_names", "suffix", "affiliation"),
                (
                    "orcid",
                    "fullname",
                    "last_name",
                    "given_names",
                    "suffix",
                    "affiliation",
                ),
            },
        ),
        migrations.AddIndex(
            model_name="researcherorcid",
            index=models.Index(fields=["orcid"], name="researcher__orcid_581791_idx"),
        ),
    ]
