# Generated by Django 4.1.8 on 2023-06-23 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtaildocs", "0012_uploadeddocument"),
        ("journal", "0006_scielojournal_open_access_scielojournal_url_oa"),
        ("researcher", "0006_alter_researcher_gender_identification_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="researcher",
            name="gender_identification_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DECLARED", "Declarado por el investigador"),
                    (
                        "AUTOMATIC",
                        "Identificado automáticamente por programa de computador",
                    ),
                    ("MANUAL", "Identificado por algun usuario"),
                ],
                max_length=255,
                null=True,
                verbose_name="Gender identification status",
            ),
        ),
        migrations.CreateModel(
            name="EditorialBoardMemberFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_valid",
                    models.BooleanField(
                        blank=True, default=False, null=True, verbose_name="Is valid?"
                    ),
                ),
                (
                    "line_count",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="Number of lines"
                    ),
                ),
                (
                    "attachment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtaildocs.document",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EditorialBoardMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Editor-Chefe", "Editor-Chefe"),
                            ("Editor(es) Executivo", "Editor(es) Executivo"),
                            (
                                "Editor(es) Associados ou de Seção",
                                "Editor(es) Associados ou de Seção",
                            ),
                            ("Equipe Técnica", "Equipe Técnica"),
                        ],
                        max_length=255,
                        verbose_name="Role",
                    ),
                ),
                ("initial_year", models.IntegerField(blank=True, null=True)),
                (
                    "initial_month",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "January"),
                            (2, "February"),
                            (3, "March"),
                            (4, "April"),
                            (5, "May"),
                            (6, "June"),
                            (7, "July"),
                            (8, "August"),
                            (9, "September"),
                            (10, "October"),
                            (11, "November"),
                            (12, "December"),
                        ],
                        null=True,
                    ),
                ),
                ("final_year", models.IntegerField(blank=True, null=True)),
                (
                    "final_month",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "January"),
                            (2, "February"),
                            (3, "March"),
                            (4, "April"),
                            (5, "May"),
                            (6, "June"),
                            (7, "July"),
                            (8, "August"),
                            (9, "September"),
                            (10, "October"),
                            (11, "November"),
                            (12, "December"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="journal.scielojournal",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="researcher.researcher",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="editorialboardmember",
            index=models.Index(
                fields=["journal"], name="researcher__journal_39ac8d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="editorialboardmember",
            index=models.Index(
                fields=["member"], name="researcher__member__7e5769_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="editorialboardmember",
            index=models.Index(fields=["role"], name="researcher__role_2b2f96_idx"),
        ),
    ]
