# Generated by Django 4.1.8 on 2023-07-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("researcher", "0007_alter_researcher_gender_identification_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="researcher",
            name="declared_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Declared Name"
            ),
        ),
        migrations.AlterField(
            model_name="researcher",
            name="given_names",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Given names"
            ),
        ),
        migrations.AlterField(
            model_name="researcher",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Last name"
            ),
        ),
    ]
