# Generated by Django 5.0.8 on 2025-07-18 04:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_language_core_langua_name_4f83d7_idx"),
        ("organization", "0007_alter_organization_acronym"),
        (
            "researcher",
            "0007_alter_affiliation_created_alter_affiliation_creator_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="newresearcher",
            index=models.Index(fields=["orcid"], name="researcher__orcid_i_e9c7ca_idx"),
        ),
    ]
