# Generated by Django 4.1.8 on 2023-07-24 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0007_journal_and_more"),
        ("researcher", "0007_alter_researcher_gender_identification_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="editorialboardmember",
            name="journal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="journal.journal",
            ),
        ),
    ]
