# Generated by Django 4.1.8 on 2023-07-29 22:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("researcher", "0008_alter_editorialboardmember_journal"),
        ("researcher", "0008_researcher_declared_name"),
    ]

    operations = []
