# Generated by Django 5.2.7 on 2026-02-24 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "researcher",
            "0009_alter_affiliation_created_alter_affiliation_creator_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="newresearcher",
            name="declared_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Declared Name"
            ),
        ),
        migrations.AlterField(
            model_name="institutionalauthor",
            name="collab",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Collab"
            ),
        ),
        migrations.AlterField(
            model_name="newresearcher",
            name="fullname",
            field=models.CharField(max_length=255, null=True, verbose_name="Full Name"),
        ),
        migrations.AlterField(
            model_name="newresearcher",
            name="gender_identification_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DECLARED", "Declarado por el investigador"),
                    (
                        "AUTOMATIC",
                        "Identificado automáticamente por programa de computador",
                    ),
                    ("MANUAL", "Identificado por algun usuario"),
                ],
                max_length=255,
                null=True,
                verbose_name="Gender identification status",
            ),
        ),
        migrations.AlterField(
            model_name="personname",
            name="fullname",
            field=models.CharField(max_length=255, null=True, verbose_name="Full Name"),
        ),
        migrations.AlterField(
            model_name="personname",
            name="given_names",
            field=models.CharField(
                max_length=128, null=True, verbose_name="Given names"
            ),
        ),
        migrations.AlterField(
            model_name="personname",
            name="last_name",
            field=models.CharField(max_length=64, null=True, verbose_name="Last name"),
        ),
    ]
