# Generated by Django 5.0.3 on 2024-04-19 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_gender_created_gender_creator_gender_updated_and_more"),
        ("toc", "0002_issuetoc"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="journalsection",
            name="section",
        ),
        migrations.AddField(
            model_name="journalsection",
            name="language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.language",
                verbose_name="Idioma",
            ),
        ),
        migrations.AddField(
            model_name="journalsection",
            name="text",
            field=models.TextField(blank=True, null=True, verbose_name="Texto"),
        ),
    ]
