# Generated by Django 4.2.7 on 2023-12-09 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("researcher", "0003_affiliation_researcheraka_and_more"),
        ("wagtaildocs", "0012_uploadeddocument"),
        ("journal", "0003_ethics_digitalpreservation"),
    ]

    operations = [
        migrations.CreateModel(
            name="EditorialBoard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                ("initial_year", models.CharField(blank=True, max_length=4, null=True)),
                ("final_year", models.CharField(blank=True, max_length=4, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="journal.journal",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EditorialBoardMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="journal.journal",
                    ),
                ),
                (
                    "researcher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="researcher.researcher",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "std_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("editor-in-chief", "Editor-in-chief"),
                            ("executive editor", "Editor"),
                            ("associate editor", "Associate editor"),
                            ("technical team", "Technical team"),
                        ],
                        max_length=16,
                        null=True,
                        verbose_name="Role",
                    ),
                ),
                (
                    "declared_role",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Declared Role",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EditorialBoardRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "editorial_board",
                    modelcluster.fields.ParentalKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="editorial_board_role",
                        to="editorialboard.editorialboard",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(to="editorialboard.editorialboardmember"),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="editorialboard.rolemodel",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EditorialBoardMemberFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_valid",
                    models.BooleanField(
                        blank=True, default=False, null=True, verbose_name="Is valid?"
                    ),
                ),
                (
                    "line_count",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="Number of lines"
                    ),
                ),
                (
                    "attachment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtaildocs.document",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EditorialBoardMemberActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("editor-in-chief", "Editor-in-chief"),
                            ("executive editor", "Editor"),
                            ("associate editor", "Associate editor"),
                            ("technical team", "Technical team"),
                        ],
                        max_length=255,
                        verbose_name="Role",
                    ),
                ),
                ("initial_year", models.CharField(blank=True, max_length=4, null=True)),
                (
                    "initial_month",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("01", "January"),
                            ("02", "February"),
                            ("03", "March"),
                            ("04", "April"),
                            ("05", "May"),
                            ("06", "June"),
                            ("07", "July"),
                            ("08", "August"),
                            ("09", "September"),
                            ("10", "October"),
                            ("11", "November"),
                            ("12", "December"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                ("final_year", models.CharField(blank=True, max_length=4, null=True)),
                (
                    "final_month",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("01", "January"),
                            ("02", "February"),
                            ("03", "March"),
                            ("04", "April"),
                            ("05", "May"),
                            ("06", "June"),
                            ("07", "July"),
                            ("08", "August"),
                            ("09", "September"),
                            ("10", "October"),
                            ("11", "November"),
                            ("12", "December"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "member",
                    modelcluster.fields.ParentalKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="editorial_board_member_activity",
                        to="editorialboard.editorialboardmember",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="rolemodel",
            index=models.Index(
                fields=["declared_role"], name="editorialbo_declare_bd3ba2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rolemodel",
            index=models.Index(
                fields=["std_role"], name="editorialbo_std_rol_b91ae3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rolemodel",
            unique_together={("declared_role", "std_role")},
        ),
        migrations.AddIndex(
            model_name="editorialboardrole",
            index=models.Index(
                fields=["editorial_board"], name="editorialbo_editori_a8aa20_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="editorialboardrole",
            index=models.Index(fields=["role"], name="editorialbo_role_id_5cde0a_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="editorialboardrole",
            unique_together={("editorial_board", "role")},
        ),
        migrations.AddIndex(
            model_name="editorialboardmemberactivity",
            index=models.Index(
                fields=["initial_year"], name="editorialbo_initial_cbf18f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="editorialboardmemberactivity",
            index=models.Index(
                fields=["initial_month"], name="editorialbo_initial_b36ed3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="editorialboardmemberactivity",
            index=models.Index(fields=["role"], name="editorialbo_role_a65961_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="editorialboardmember",
            unique_together={("researcher", "journal")},
        ),
        migrations.AddIndex(
            model_name="editorialboard",
            index=models.Index(
                fields=["initial_year"], name="editorialbo_initial_011435_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="editorialboard",
            index=models.Index(
                fields=["final_year"], name="editorialbo_final_y_cb55bc_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="editorialboard",
            unique_together={("journal", "initial_year", "final_year")},
        ),
    ]
