# Generated by Django 4.2.7 on 2023-12-10 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("editorialboard", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="editorialboardmemberactivity",
            new_name="editorialbo_role_id_59ae78_idx",
            old_name="editorialbo_role_a65961_idx",
        ),
        migrations.AlterField(
            model_name="editorialboardmemberactivity",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="editorialboard.rolemodel",
            ),
        ),
    ]
