# Generated by Django 4.2.7 on 2023-12-13 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "editorialboard",
            "0002_rename_editorialbo_role_a65961_idx_editorialbo_role_id_59ae78_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="editorialboardrole",
            name="members",
        ),
        migrations.AddField(
            model_name="editorialboardrole",
            name="member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="editorialboard.editorialboardmember",
            ),
        ),
    ]
