# Generated by Django 4.2.7 on 2023-12-13 00:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "editorialboard",
            "0002_rename_editorialbo_role_a65961_idx_editorialbo_role_id_59ae78_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="editorialboardrole",
            name="sort_order",
        ),
    ]
