# Generated by Django 4.2.7 on 2023-12-13 00:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("editorialboard", "0003_remove_editorialboardrole_sort_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="editorialboardrole",
            name="sort_order",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
