# Generated by Django 4.2.7 on 2023-12-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("editorialboard", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="editorialboardmember",
            name="area",
            field=models.TextField(blank=True, null=True),
        ),
    ]
