# Generated by Django 4.2.7 on 2024-03-15 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("editorialboard", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="editorialboardmember",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                help_text="Upload a profile photo of the editorial board member.",
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
