# Generated by Django 4.2.7 on 2023-12-13 00:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("editorialboard", "0004_editorialboardrole_sort_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="editorialboardrole",
            options={"ordering": ["sort_order"]},
        ),
        migrations.RemoveIndex(
            model_name="editorialboardrole",
            name="editorialbo_editori_a8aa20_idx",
        ),
        migrations.RemoveIndex(
            model_name="editorialboardrole",
            name="editorialbo_role_id_5cde0a_idx",
        ),
        migrations.AlterUniqueTogether(
            name="editorialboardrole",
            unique_together=set(),
        ),
    ]
