# Generated by Django 4.2.7 on 2023-12-13 00:53

from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("editorialboard", "0006_remove_editorialboardrole_members_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="editorialboardrole",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="editorialboardrole",
            unique_together={("editorial_board", "role")},
        ),
        migrations.AddIndex(
            model_name="editorialboardrole",
            index=models.Index(
                fields=["editorial_board"], name="editorialbo_editori_a8aa20_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="editorialboardrole",
            index=models.Index(fields=["role"], name="editorialbo_role_id_5cde0a_idx"),
        ),
        migrations.RemoveField(
            model_name="editorialboardrole",
            name="members",
        ),
        migrations.AddField(
            model_name="editorialboardrole",
            name="members",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to="editorialboard.editorialboardmember"
            ),
        ),
    ]
