# Generated by Django 5.0.8 on 2025-07-18 04:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editorialboard", "0008_alter_editorialboardmember_created_and_more"),
        (
            "researcher",
            "0007_alter_affiliation_created_alter_affiliation_creator_and_more",
        ),
        ("wagtailimages", "0026_delete_uploadedimage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="editorialboardmember",
            index=models.Index(
                fields=["researcher"], name="editorialbo_researc_effbf8_idx"
            ),
        ),
    ]
