# Generated by Django 4.1.8 on 2023-04-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="chapter",
            index=models.Index(fields=["book"], name="book_chapte_book_id_1b9202_idx"),
        ),
    ]
