# Generated by Django 4.1.6 on 2023-02-22 13:56

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0002_chapter_chapter_book_chapte_title_5891b0_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="journal",
            field=modelcluster.fields.ParentalKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="book",
                to="book.book",
            ),
            preserve_default=False,
        ),
    ]
