# Generated by Django 4.1.10 on 2023-10-17 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("location", "0001_initial"),
        ("book", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="location.location",
                verbose_name="Localization",
            ),
        ),
    ]
