# Generated by Django 4.1.8 on 2023-07-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0002_alter_book_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="identifier",
            field=models.URLField(blank=True, null=True),
        ),
    ]
