# Generated by Django 4.1.10 on 2023-08-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0002_book_researchers_book_updated_by_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="book",
            index=models.Index(fields=["eisbn"], name="book_book_eisbn_019598_idx"),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(fields=["year"], name="book_book_year_62fef9_idx"),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(
                fields=["identifier"], name="book_book_identif_c4b36a_idx"
            ),
        ),
    ]
