# Generated by Django 4.2.7 on 2023-12-07 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("institution", "0003_institutionidentification"),
        ("book", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="institution",
        ),
        migrations.AddField(
            model_name="book",
            name="publisher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="institution.publisher",
                verbose_name="Publisher",
            ),
        ),
    ]
