# Generated by Django 4.1.6 on 2023-02-22 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0003_chapter_journal"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chapter",
            old_name="journal",
            new_name="book",
        ),
    ]
