# Generated by Django 5.2.3 on 2025-09-01 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0003_alter_book_options_alter_chapter_options_and_more"),
        ("core", "0007_alter_language_options_alter_license_options_and_more"),
        ("institution", "0007_alter_copyrightholder_created_and_more"),
        ("location", "0003_alter_city_options_alter_country_options_and_more"),
        (
            "researcher",
            "0009_alter_affiliation_created_alter_affiliation_creator_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={
                "verbose_name": "SciELO Book",
                "verbose_name_plural": "SciELO Books",
            },
        ),
        migrations.AlterModelOptions(
            name="chapter",
            options={"verbose_name": "Chapter", "verbose_name_plural": "Chapters"},
        ),
        migrations.AlterField(
            model_name="book",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creation date"),
        ),
        migrations.AlterField(
            model_name="book",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="eisbn",
            field=models.CharField(
                blank=True, max_length=13, null=True, verbose_name="Electronic ISBN"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.language",
                verbose_name="Language",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="location.location",
                verbose_name="Localization",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="publisher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="institution.publisher",
                verbose_name="Publisher",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="researchers",
            field=models.ManyToManyField(
                blank=True, to="researcher.researcher", verbose_name="Authors"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="synopsis",
            field=models.TextField(blank=True, null=True, verbose_name="Synopsis"),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.TextField(blank=True, null=True, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="book",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Last update date"),
        ),
        migrations.AlterField(
            model_name="book",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updater",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="year",
            field=models.IntegerField(blank=True, null=True, verbose_name="Year"),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creation date"),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.language",
                verbose_name="Language",
            ),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="title",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Last update date"),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updater",
            ),
        ),
        migrations.AlterField(
            model_name="recraw",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creation date"),
        ),
        migrations.AlterField(
            model_name="recraw",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AlterField(
            model_name="recraw",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Last update date"),
        ),
        migrations.AlterField(
            model_name="recraw",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updater",
            ),
        ),
    ]
