# Generated by Django 4.1.6 on 2023-02-22 13:58

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0004_rename_journal_chapter_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter",
            name="book",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chapter",
                to="book.book",
            ),
        ),
    ]
