# Generated by Django 4.1.6 on 2023-02-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0005_alter_chapter_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="doi",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="DOI"
            ),
        ),
    ]
