from django.utils.translation import gettext as _


thematic_level0 = (
    ('', ''),
    ('ALL', _('ALL')),
    ('UNDEFINED', _('UNDEFINED')),
    ('NOT_APPLICABLE', _('NOT APPLICABLE')),
    ('Ciências da Vida', _('Ciências da Vida')),
    ('Ciências Exatas, Tecnológicas e Multidisciplinar', _('Ciências Exatas, Tecnológicas e Multidisciplinar')),
    ('Humanidades', _('Humanidades')),
)

thematic_level1 = (
    ('', ''),
    ('ALL', _('ALL')),
    ('UNDEFINED', _('UNDEFINED')),
    ('NOT_APPLICABLE', _('NOT APPLICABLE')),
    ('Ciências Agrárias', _('Ciências Agrárias')),
    ('Ciências Biológicas', _('Ciências Biológicas')),
    ('Ciências da Saúde', _('Ciências da Saúde')),
    ('Ciências Exatas e da Terra', _('Ciências Exatas e da Terra')),
    ('Ciências Humanas', _('Ciências Humanas')),
    ('Ciências Sociais Aplicadas', _('Ciências Sociais Aplicadas')),
    ('Engenharias', _('Engenharias')),
    ('Linguística, Letras e Artes', _('Linguística, Letras e Artes')),
    ('Multidisciplinar', _('Multidisciplina')),
)

thematic_level2 = (
    ('', ''),
    ('ALL', _('ALL')),
    ('UNDEFINED', _('UNDEFINED')),
    ('NOT_APPLICABLE', _('NOT APPLICABLE')),
    ('Administração Pública e de Empresas, Ciências Contábeis e Turismo', _('Administração Pública e de Empresas, Ciências Contábeis e Turismo')),
    ('Antropologia / Arqueologia', _('Antropologia / Arqueologia')),
    ('Arquitetura, Urbanismo e Design', _('Arquitetura, Urbanismo e Design')),
    ('Artes', _('Artes')),
    ('Astronomia / Física', _('Astronomia / Física')),
    ('Biodiversidade', _('Biodiversidade')),
    ('Biotecnologia', _('Biotecnologia')),
    ('Ciência da Computação', _('Ciência da Computação')),
    ('Ciência de Alimentos', _('Ciência de Alimentos')),
    ('Ciência Política e Relações Internacionais', _('Ciência Política e Relações Internacionais')),
    ('Ciências Agrárias I', _('Ciências Agrárias I')),
    ('Ciências Ambientais', _('Ciências Ambientais')),
    ('Ciências Biológicas I', _('Ciências Biológicas I')),
    ('Ciências Biológicas II', _('Ciências Biológicas II')),
    ('Ciências Biológicas III', _('Ciências Biológicas III')),
    ('Ciências da Religião e Teologia', _('Ciências da Religião e Teologia')),
    ('Comunicação e Informação', _('Comunicação e Informação')),
    ('Direito', _('Direito')),
    ('Economia', _('Economia')),
    ('Educação', _('Educação')),
    ('Educação Física', _('Educação Física')),
    ('Enfermagem', _('Enfermagem')),
    ('Engenharias I', _('Engenharias I')),
    ('Engenharias II', _('Engenharias II')),
    ('Engenharias III', _('Engenharias III')),
    ('Engenharias IV', _('Engenharias IV')),
    ('Ensino', _('Ensino')),
    ('Farmácia', _('Farmácia')),
    ('Filosofia', _('Filosofia')),
    ('Geociências', _('Geociências')),
    ('Geografia', _('Geografia')),
    ('História', _('História')),
    ('Interdisciplinar', _('Interdisciplinar')),
    ('Linguística e Literatura', _('Linguística e Literatura')),
    ('Matemática / Probabilidade e Estatística', _('Matemática / Probabilidade e Estatística')),
    ('Materiais', _('Materiais')),
    ('Medicina I', _('Medicina I')),
    ('Medicina II', _('Medicina II')),
    ('Medicina III', _('Medicina III')),
    ('Medicina Veterinária', _('Medicina Veterinária')),
    ('Nutrição', _('Nutrição')),
    ('Odontologia', _('Odontologia')),
    ('Planejamento Urbano e Regional / Demografia', _('Planejamento Urbano e Regional / Demografia')),
    ('Psicologia', _('Psicologia')),
    ('Química', _('Química')),
    ('Saúde Coletiva', _('Saúde Coletiva')),
    ('Serviço Social', _('Serviço Social')),
    ('Sociologia', _('Sociologia')),
    ('Zootecnia / Recursos Pesqueiros', _('Zootecnia / Recursos Pesqueiros')),
)
