from django.utils.translation import gettext as _


thematic_level0 = (
    ("", ""),
    ("ALL", _("ALL")),
    ("UNDEFINED", _("UNDEFINED")),
    ("NOT_APPLICABLE", _("NOT APPLICABLE")),
    ("Ciências Agrárias", _("Ciências Agrárias")),
    ("Ciências Biológicas", _("Ciências Biológicas")),
    ("Ciências da Saúde", _("Ciências da Saúde")),
    ("Ciências Exatas e da Terra", _("Ciências Exatas e da Terra")),
    ("Ciências Humanas", _("Ciências Humanas")),
    ("Ciências Sociais Aplicadas", _("Ciências Sociais Aplicadas")),
    ("Engenharias", _("Engenharias")),
    ("Linguística, Letras e Artes", _("Linguística, Letras e Artes")),
    ("Multidisciplinar", _("Multidisciplinar")),
)

thematic_level1 = (
    ("", ""),
    ("ALL", _("ALL")),
    ("UNDEFINED", _("UNDEFINED")),
    ("NOT_APPLICABLE", _("NOT APPLICABLE")),
    ("Administração", _("Administração")),
    ("Agronomia", _("Agronomia")),
    ("Antropologia", _("Antropologia")),
    ("Arqueologia", _("Arqueologia")),
    ("Arquitetura e urbanismo", _("Arquitetura e urbanismo")),
    ("Artes", _("Artes")),
    ("Astronomia", _("Astronomia")),
    ("Biofísica", _("Biofísica")),
    ("Biologia geral", _("Biologia geral")),
    ("Bioquímica", _("Bioquímica")),
    ("Biotecnologia", _("Biotecnologia")),
    ("Botânica", _("Botânica")),
    ("Ciência da computação", _("Ciência da computação")),
    ("Ciência da informação", _("Ciência da informação")),
    ("Ciência e tecnologia de alimentos", _("Ciência e tecnologia de alimentos")),
    ("Ciência política", _("Ciência política")),
    ("Ciências Ambientais", _("Ciências Ambientais")),
    ("Comunicação", _("Comunicação")),
    ("Demografia", _("Demografia")),
    ("Desenho industrial", _("Desenho industrial")),
    ("Direito", _("Direito")),
    ("Ecologia", _("Ecologia")),
    ("Economia", _("Economia")),
    ("Economia doméstica", _("Economia doméstica")),
    ("Educação", _("Educação")),
    ("Educação física", _("Educação física")),
    ("Enfermagem", _("Enfermagem")),
    ("Engenharia aeroespacial", _("Engenharia aeroespacial")),
    ("Engenharia agrícola", _("Engenharia agrícola")),
    ("Engenharia biomédica", _("Engenharia biomédica")),
    ("Engenharia civil", _("Engenharia civil")),
    (
        "Engenharia de materiais e metalúrgica",
        _("Engenharia de materiais e metalúrgica"),
    ),
    ("Engenharia de minas", _("Engenharia de minas")),
    ("Engenharia de produção", _("Engenharia de produção")),
    ("Engenharia de transportes", _("Engenharia de transportes")),
    ("Engenharia elétrica", _("Engenharia elétrica")),
    ("Engenharia mecânica", _("Engenharia mecânica")),
    ("Engenharia naval e oceânica", _("Engenharia naval e oceânica")),
    ("Engenharia nuclear", _("Engenharia nuclear")),
    ("Engenharia química", _("Engenharia química")),
    ("Engenharia sanitária", _("Engenharia sanitária")),
    ("Ensino", _("Ensino")),
    ("Farmácia", _("Farmácia")),
    ("Farmacologia", _("Farmacologia")),
    ("Filosofia", _("Filosofia")),
    ("Física", _("Física")),
    ("Fisiologia", _("Fisiologia")),
    ("Fisioterapia e terapia ocupacional", _("Fisioterapia e terapia ocupacional")),
    ("Fonoaudiologia", _("Fonoaudiologia")),
    ("Genética", _("Genética")),
    ("Geociências", _("Geociências")),
    ("Geografia", _("Geografia")),
    ("História", _("História")),
    ("Imunologia", _("Imunologia")),
    ("Interdisciplinar", _("Interdisciplinar")),
    ("Letras", _("Letras")),
    ("Linguística", _("Linguística")),
    ("Matemática", _("Matemática")),
    ("Materiais ", _("Materiais ")),
    ("Medicina", _("Medicina")),
    ("Medicina veterinária", _("Medicina veterinária")),
    ("Microbiologia", _("Microbiologia")),
    ("Morfologia", _("Morfologia")),
    ("Museologia", _("Museologia")),
    ("Nutrição", _("Nutrição")),
    ("Oceanografia", _("Oceanografia")),
    ("Odontologia", _("Odontologia")),
    ("Parasitologia", _("Parasitologia")),
    ("Planejamento urbano e regional", _("Planejamento urbano e regional")),
    ("Probabilidade e estatística", _("Probabilidade e estatística")),
    ("Psicologia", _("Psicologia")),
    ("Química", _("Química")),
    (
        "Recursos florestais e engenharia florestal",
        _("Recursos florestais e engenharia florestal"),
    ),
    (
        "Recursos pesqueiros e engenharia de pesca",
        _("Recursos pesqueiros e engenharia de pesca"),
    ),
    ("Saúde coletiva", _("Saúde coletiva")),
    ("Serviço social", _("Serviço social")),
    ("Sociologia", _("Sociologia")),
    ("Teologia", _("Teologia")),
    ("Turismo", _("Turismo")),
    ("Zoologia", _("Zoologia")),
    ("Zootecnia", _("Zootecnia")),
)

thematic_level2 = (
    ("", ""),
    ("ALL", _("ALL")),
    ("UNDEFINED", _("UNDEFINED")),
    ("NOT_APPLICABLE", _("NOT APPLICABLE")),
    ("Administraçao de Empresas", _("Administraçao de Empresas")),
    ("Administração de Setores Específicos", _("Administração de Setores Específicos")),
    ("Administração Educacional", _("Administração Educacional")),
    ("Administração Pública", _("Administração Pública")),
    ("Aerodinâmica", _("Aerodinâmica")),
    ("Agrometeorologia", _("Agrometeorologia")),
    ("Álgebra", _("Álgebra")),
    ("Análise", _("Análise")),
    ("Análise e Controle de Medicamentos", _("Análise e Controle de Medicamentos")),
    ("Análise Nutricional de População", _("Análise Nutricional de População")),
    ("Análise Toxicológica", _("Análise Toxicológica")),
    ("Anatomia", _("Anatomia")),
    (
        "Anatomia Patológica e Patologia Clínica",
        _("Anatomia Patológica e Patologia Clínica"),
    ),
    (
        "Antropologia das Populações Afro-Brasileiras",
        _("Antropologia das Populações Afro-Brasileiras"),
    ),
    ("Antropologia Rural", _("Antropologia Rural")),
    ("Antropologia Urbana", _("Antropologia Urbana")),
    ("Aplicações de Radioisótopos", _("Aplicações de Radioisótopos")),
    ("Aquicultura", _("Aquicultura")),
    (
        "Áreas Clássicas de Fenomenologia e suas Aplicações",
        _("Áreas Clássicas de Fenomenologia e suas Aplicações"),
    ),
    ("Arqueologia Histórica", _("Arqueologia Histórica")),
    ("Arqueologia Pré-Histórica", _("Arqueologia Pré-Histórica")),
    ("Arquivologia", _("Arquivologia")),
    ("Artes do Vídeo", _("Artes do Vídeo")),
    ("Artes Plásticas", _("Artes Plásticas")),
    ("Astrofísica do Meio Interestelar", _("Astrofísica do Meio Interestelar")),
    ("Astrofísica do Sistema Solar", _("Astrofísica do Sistema Solar")),
    ("Astrofísica Estelar", _("Astrofísica Estelar")),
    ("Astrofísica Extragaláctica", _("Astrofísica Extragaláctica")),
    (
        "Astronomia de Posição e Mecânica Celeste",
        _("Astronomia de Posição e Mecânica Celeste"),
    ),
    ("Biblioteconomia", _("Biblioteconomia")),
    ("Bioengenharia", _("Bioengenharia")),
    ("Biofísica Celular", _("Biofísica Celular")),
    ("Biofísica de Processos e Sistemas", _("Biofísica de Processos e Sistemas")),
    ("Biofísica Molecular", _("Biofísica Molecular")),
    (
        "Biologia e Fisiologia dos Mircroorganismos",
        _("Biologia e Fisiologia dos Mircroorganismos"),
    ),
    ("Biologia Molecular", _("Biologia Molecular")),
    ("Bioquímica da Nutrição", _("Bioquímica da Nutrição")),
    ("Bioquímica de Microorganismos", _("Bioquímica de Microorganismos")),
    ("Botânica Aplicada", _("Botânica Aplicada")),
    ("Bromatologia", _("Bromatologia")),
    ("Ciência de Alimentos", _("Ciência de Alimentos")),
    ("Ciência do Solo", _("Ciência do Solo")),
    ("Ciências Contábeis", _("Ciências Contábeis")),
    ("Cinema", _("Cinema")),
    (
        "Circuitos Elétricos, Magnéticos e Eletrônicos",
        _("Circuitos Elétricos, Magnéticos e Eletrônicos"),
    ),
    ("Cirurgia", _("Cirurgia")),
    ("Cirurgia Buco-Maxilo-Facial", _("Cirurgia Buco-Maxilo-Facial")),
    ("Citologia e Biologia Celular", _("Citologia e Biologia Celular")),
    ("Clínica e Cirurgia Animal", _("Clínica e Cirurgia Animal")),
    ("Clínica Médica", _("Clínica Médica")),
    ("Clínica Odontológica", _("Clínica Odontológica")),
    ("Combustível Nuclear", _("Combustível Nuclear")),
    ("Componentes da Dinâmica Demográfica", _("Componentes da Dinâmica Demográfica")),
    ("Comportamento Animal", _("Comportamento Animal")),
    ("Comportamento Político", _("Comportamento Político")),
    ("Comunicação Visual", _("Comunicação Visual")),
    ("Conservação da Natureza", _("Conservação da Natureza")),
    ("Construção Civil", _("Construção Civil")),
    ("Construções Rurais e Ambiência", _("Construções Rurais e Ambiência")),
    (
        "Crescimento, Flutuações e Planejamento Econômico",
        _("Crescimento, Flutuações e Planejamento Econômico"),
    ),
    ("Currículo", _("Currículo")),
    ("Dança", _("Dança")),
    ("Demografia Histórica", _("Demografia Histórica")),
    ("Desenho de Produto", _("Desenho de Produto")),
    (
        "Desnutrição e Desenvolvimento Fisiológico",
        _("Desnutrição e Desenvolvimento Fisiológico"),
    ),
    ("Dietética", _("Dietética")),
    ("Dinâmica de Vôo", _("Dinâmica de Vôo")),
    ("Direito Privado", _("Direito Privado")),
    ("Direito Público", _("Direito Público")),
    ("Direitos Especiais", _("Direitos Especiais")),
    ("Ecologia Aplicada", _("Ecologia Aplicada")),
    ("Ecologia de Ecossistemas", _("Ecologia de Ecossistemas")),
    (
        "Ecologia dos Animais Domésticos e Etologia",
        _("Ecologia dos Animais Domésticos e Etologia"),
    ),
    ("Ecologia Teórica", _("Ecologia Teórica")),
    (
        "Economia Agrária e dos Recursos Naturais",
        _("Economia Agrária e dos Recursos Naturais"),
    ),
    ("Economia de Recursos Humanos", _("Economia de Recursos Humanos")),
    ("Economia do Bem-Estar Social", _("Economia do Bem-Estar Social")),
    ("Economia Industrial", _("Economia Industrial")),
    ("Economia Internacional", _("Economia Internacional")),
    ("Economia Monetária e Fiscal", _("Economia Monetária e Fiscal")),
    ("Economia Regional e Urbana", _("Economia Regional e Urbana")),
    ("Educação Artística", _("Educação Artística")),
    (
        "Eletrônica Industrial, Sistemas e Controles Eletrônicos",
        _("Eletrônica Industrial, Sistemas e Controles Eletrônicos"),
    ),
    ("Embriologia", _("Embriologia")),
    ("Endodontia", _("Endodontia")),
    ("Energia de Biomassa Florestal", _("Energia de Biomassa Florestal")),
    ("Energização Rural", _("Energização Rural")),
    ("Enfermagem de Doenças Contagiosas", _("Enfermagem de Doenças Contagiosas")),
    ("Enfermagem de Saúde Pública", _("Enfermagem de Saúde Pública")),
    ("Enfermagem Médico-Cirúrgica", _("Enfermagem Médico-Cirúrgica")),
    ("Enfermagem Obstétrica", _("Enfermagem Obstétrica")),
    ("Enfermagem Pediátrica", _("Enfermagem Pediátrica")),
    ("Enfermagem Psiquiátrica", _("Enfermagem Psiquiátrica")),
    ("Engenharia de Água e Solo", _("Engenharia de Água e Solo")),
    ("Engenharia de Alimentos", _("Engenharia de Alimentos")),
    ("Engenharia de Pesca", _("Engenharia de Pesca")),
    (
        "Engenharia de Processamento de Produtos Agrícolas",
        _("Engenharia de Processamento de Produtos Agrícolas"),
    ),
    ("Engenharia do Produto", _("Engenharia do Produto")),
    ("Engenharia Econômica", _("Engenharia Econômica")),
    ("Engenharia Hidráulica", _("Engenharia Hidráulica")),
    ("Engenharia Médica", _("Engenharia Médica")),
    ("Engenharia Térmica", _("Engenharia Térmica")),
    ("Ensino-Aprendizagem", _("Ensino-Aprendizagem")),
    (
        "Entomologia e Malacologia de Parasitos e Vetores",
        _("Entomologia e Malacologia de Parasitos e Vetores"),
    ),
    ("Enzimologia", _("Enzimologia")),
    ("Epidemiologia", _("Epidemiologia")),
    ("Epistemologia", _("Epistemologia")),
    ("Estado e Governo", _("Estado e Governo")),
    ("Estatística", _("Estatística")),
    ("Estruturas", _("Estruturas")),
    ("Estruturas Aeroespaciais", _("Estruturas Aeroespaciais")),
    ("Estruturas Navais e Oceânicas", _("Estruturas Navais e Oceânicas")),
    ("Ética", _("Ética")),
    ("Etnofarmacologia", _("Etnofarmacologia")),
    ("Etnologia Indígena", _("Etnologia Indígena")),
    ("Extensão Rural", _("Extensão Rural")),
    ("Farmacognosia", _("Farmacognosia")),
    ("Farmacologia Autonômica", _("Farmacologia Autonômica")),
    ("Farmacologia Bioquímica e Molecular", _("Farmacologia Bioquímica e Molecular")),
    ("Farmacologia Cardiorenal", _("Farmacologia Cardiorenal")),
    ("Farmacologia Clínica", _("Farmacologia Clínica")),
    ("Farmacologia Geral", _("Farmacologia Geral")),
    ("Farmacotecnia", _("Farmacotecnia")),
    ("Fenômenos de Transporte", _("Fenômenos de Transporte")),
    ("Filosofia Brasileira", _("Filosofia Brasileira")),
    ("Filosofia da Linguagem", _("Filosofia da Linguagem")),
    ("Física Atômica e Molecular", _("Física Atômica e Molecular")),
    ("Física da Matéria Condensada", _("Física da Matéria Condensada")),
    (
        "Física das Partículas Elementares e Campos",
        _("Física das Partículas Elementares e Campos"),
    ),
    (
        "Física dos Fluídos, Física de Plasmas e Descargas Elétricas",
        _("Física dos Fluídos, Física de Plasmas e Descargas Elétricas"),
    ),
    ("Física Geral", _("Física Geral")),
    ("Física Nuclear", _("Física Nuclear")),
    ("Físico-Química", _("Físico-Química")),
    ("Fisiologia Comparada", _("Fisiologia Comparada")),
    ("Fisiologia de Orgãos e Sistemas", _("Fisiologia de Orgãos e Sistemas")),
    ("Fisiologia do Esforço", _("Fisiologia do Esforço")),
    ("Fisiologia dos Grupos Recentes", _("Fisiologia dos Grupos Recentes")),
    ("Fisiologia Geral", _("Fisiologia Geral")),
    ("Fisiologia Vegetal", _("Fisiologia Vegetal")),
    ("Fitogeografia", _("Fitogeografia")),
    ("Fitossanidade", _("Fitossanidade")),
    ("Fitotecnia", _("Fitotecnia")),
    ("Floricultura, Parques e Jardins", _("Floricultura, Parques e Jardins")),
    ("Fontes de Dados Demográficos", _("Fontes de Dados Demográficos")),
    ("Fotografia", _("Fotografia")),
    ("Fundamentos da Educação", _("Fundamentos da Educação")),
    ("Fundamentos da Sociologia", _("Fundamentos da Sociologia")),
    (
        "Fundamentos de Arquitetura e Urbanismo",
        _("Fundamentos de Arquitetura e Urbanismo"),
    ),
    (
        "Fundamentos do Planejamento Urbano e Regional",
        _("Fundamentos do Planejamento Urbano e Regional"),
    ),
    ("Fundamentos do Serviço Social", _("Fundamentos do Serviço Social")),
    ("Fundamentos e Críticas das Artes", _("Fundamentos e Críticas das Artes")),
    ("Fundamentos e Medidas da Psicologia", _("Fundamentos e Medidas da Psicologia")),
    ("Fusão Controlada", _("Fusão Controlada")),
    ("Genética Animal", _("Genética Animal")),
    (
        "Genética e Melhoramento dos Animais Domésticos",
        _("Genética e Melhoramento dos Animais Domésticos"),
    ),
    ("Genética Humana e Médica", _("Genética Humana e Médica")),
    (
        "Genética Molecular e de Microorganismos",
        _("Genética Molecular e de Microorganismos"),
    ),
    ("Genética Quantitativa", _("Genética Quantitativa")),
    ("Genética Vegetal", _("Genética Vegetal")),
    ("Geodésia", _("Geodésia")),
    ("Geofísica", _("Geofísica")),
    ("Geografia Física", _("Geografia Física")),
    ("Geografia Humana", _("Geografia Humana")),
    ("Geografia Regional", _("Geografia Regional")),
    ("Geologia", _("Geologia")),
    ("Geometria e Topologia", _("Geometria e Topologia")),
    ("Geotécnica", _("Geotécnica")),
    ("Gerência de Produção", _("Gerência de Produção")),
    ("Helmintologia de Parasitos", _("Helmintologia de Parasitos")),
    (
        "Hidrodinâmica de Navios e Sistemas Oceânicos",
        _("Hidrodinâmica de Navios e Sistemas Oceânicos"),
    ),
    ("Histologia", _("Histologia")),
    ("História Antiga e Medieval", _("História Antiga e Medieval")),
    ("História da América", _("História da América")),
    ("História da Filosofia", _("História da Filosofia")),
    ("História da Teologia", _("História da Teologia")),
    ("História das Ciências", _("História das Ciências")),
    ("História do Brasil", _("História do Brasil")),
    ("História Moderna e Contemporânea", _("História Moderna e Contemporânea")),
    ("Imunogenética", _("Imunogenética")),
    ("Imunologia Aplicada", _("Imunologia Aplicada")),
    ("Imunologia Celular", _("Imunologia Celular")),
    ("Imunoquímica", _("Imunoquímica")),
    ("Infra-Estrutura de Transportes", _("Infra-Estrutura de Transportes")),
    (
        "Inspeção de Produtos de Origem Animal",
        _("Inspeção de Produtos de Origem Animal"),
    ),
    (
        "Instalações e Equipamentos Metalúrgicos",
        _("Instalações e Equipamentos Metalúrgicos"),
    ),
    ("Instrumentação Astronômica", _("Instrumentação Astronômica")),
    ("Jornalismo e Editoração", _("Jornalismo e Editoração")),
    ("Lavra", _("Lavra")),
    ("Língua Portuguesa", _("Língua Portuguesa")),
    ("Línguas Clássicas", _("Línguas Clássicas")),
    ("Línguas Estrangeiras Modernas", _("Línguas Estrangeiras Modernas")),
    ("Línguas Indígenas", _("Línguas Indígenas")),
    ("Linguística Aplicada", _("Linguística Aplicada")),
    ("Linguística Histórica", _("Linguística Histórica")),
    ("Literatura Brasileira", _("Literatura Brasileira")),
    ("Literatura Comparada", _("Literatura Comparada")),
    ("Literaturas Clássicas", _("Literaturas Clássicas")),
    ("Literaturas Estrangeiras Modernas", _("Literaturas Estrangeiras Modernas")),
    ("Lógica", _("Lógica")),
    ("Manejo Florestal", _("Manejo Florestal")),
    ("Máquinas e Implementos Agrícolas", _("Máquinas e Implementos Agrícolas")),
    ("Máquinas Marítimas", _("Máquinas Marítimas")),
    ("Matemática Aplicada", _("Matemática Aplicada")),
    ("Matemática da Computação", _("Matemática da Computação")),
    (
        "Materiais e Processos para Engenharia Aeronáutica e Aeroespacial",
        _("Materiais e Processos para Engenharia Aeronáutica e Aeroespacial"),
    ),
    ("Materiais Elétricos", _("Materiais Elétricos")),
    ("Materiais não-Metálicos", _("Materiais não-Metálicos")),
    ("Materiais Odontológicos", _("Materiais Odontológicos")),
    ("Mecânica dos Sólidos", _("Mecânica dos Sólidos")),
    ("Medicina Legal e Deontologia", _("Medicina Legal e Deontologia")),
    ("Medicina Preventiva", _("Medicina Preventiva")),
    ("Medicina Veterinária Preventiva", _("Medicina Veterinária Preventiva")),
    (
        "Medidas Elétricas, Magnéticas e Eletrônicas; Instrumentação",
        _("Medidas Elétricas, Magnéticas e Eletrônicas; Instrumentação"),
    ),
    ("Metabolismo e Bioenergética", _("Metabolismo e Bioenergética")),
    ("Metafísica", _("Metafísica")),
    ("Metalurgia de Transformação", _("Metalurgia de Transformação")),
    ("Metalurgia Extrativa", _("Metalurgia Extrativa")),
    ("Metalurgia Física", _("Metalurgia Física")),
    ("Meteorologia", _("Meteorologia")),
    ("Metodologia e Técnicas da Computação", _("Metodologia e Técnicas da Computação")),
    (
        "Metodos e Técnicas do Planejamento Urbano e Regional",
        _("Metodos e Técnicas do Planejamento Urbano e Regional"),
    ),
    ("Métodos Quantitativos em Economia", _("Métodos Quantitativos em Economia")),
    ("Microbiologia Aplicada", _("Microbiologia Aplicada")),
    ("Morfologia dos Grupos Recentes", _("Morfologia dos Grupos Recentes")),
    ("Morfologia Vegetal", _("Morfologia Vegetal")),
    ("Música", _("Música")),
    ("Mutagênese", _("Mutagênese")),
    ("Neuropsicofarmacologia", _("Neuropsicofarmacologia")),
    ("Nupcialidade e Família", _("Nupcialidade e Família")),
    ("Nutrição e Alimentação Animal", _("Nutrição e Alimentação Animal")),
    ("Oceanografia Biológica", _("Oceanografia Biológica")),
    ("Oceanografia Física", _("Oceanografia Física")),
    ("Oceanografia Geológica", _("Oceanografia Geológica")),
    ("Oceanografia Química", _("Oceanografia Química")),
    ("Odontologia Social e Preventiva", _("Odontologia Social e Preventiva")),
    ("Odontopediatria", _("Odontopediatria")),
    ("Ópera", _("Ópera")),
    ("Operações de Transportes", _("Operações de Transportes")),
    (
        "Operações Industriais e Equipamentos para Engenharia Química",
        _("Operações Industriais e Equipamentos para Engenharia Química"),
    ),
    ("Orientação e Aconselhamento", _("Orientação e Aconselhamento")),
    ("Ortodontia", _("Ortodontia")),
    ("Outras Literaturas Vernáculas", _("Outras Literaturas Vernáculas")),
    ("Outras Sociologias Específicas", _("Outras Sociologias Específicas")),
    ("Paisagismo", _("Paisagismo")),
    ("Paleobotânica", _("Paleobotânica")),
    ("Paleozoologia", _("Paleozoologia")),
    ("Pastagem e Forragicultura", _("Pastagem e Forragicultura")),
    ("Patologia Animal", _("Patologia Animal")),
    ("Periodontia", _("Periodontia")),
    ("Pesquisa Mineral", _("Pesquisa Mineral")),
    ("Pesquisa Operacional", _("Pesquisa Operacional")),
    ("Planejamento de Transportes", _("Planejamento de Transportes")),
    ("Planejamento e Avaliação Educacional", _("Planejamento e Avaliação Educacional")),
    ("Política Internacional", _("Política Internacional")),
    ("Política Pública e População", _("Política Pública e População")),
    ("Políticas Públicas", _("Políticas Públicas")),
    ("Probabilidade", _("Probabilidade")),
    (
        "Probabilidade e Estatística Aplicadas",
        _("Probabilidade e Estatística Aplicadas"),
    ),
    ("Processos de Fabricação", _("Processos de Fabricação")),
    (
        "Processos Industriais de Engenharia Química",
        _("Processos Industriais de Engenharia Química"),
    ),
    ("Produção Animal", _("Produção Animal")),
    ("Programação Visual", _("Programação Visual")),
    ("Projetos de Arquitetura e Urbanismo", _("Projetos de Arquitetura e Urbanismo")),
    ("Projetos de Máquinas", _("Projetos de Máquinas")),
    (
        "Projetos de Navios e de Sistemas Oceânicos",
        _("Projetos de Navios e de Sistemas Oceânicos"),
    ),
    ("Propulsão Aeroespacial", _("Propulsão Aeroespacial")),
    ("Protozoologia de Parasitos", _("Protozoologia de Parasitos")),
    ("Psicolinguística", _("Psicolinguística")),
    ("Psicologia Cognitiva", _("Psicologia Cognitiva")),
    ("Psicologia Comparativa", _("Psicologia Comparativa")),
    ("Psicologia do Desenvolvimento Humano", _("Psicologia do Desenvolvimento Humano")),
    (
        "Psicologia do Ensino e da Aprendizagem",
        _("Psicologia do Ensino e da Aprendizagem"),
    ),
    (
        "Psicologia do Trabalho e Organizacional",
        _("Psicologia do Trabalho e Organizacional"),
    ),
    ("Psicologia Experimental", _("Psicologia Experimental")),
    ("Psicologia Fisiológica", _("Psicologia Fisiológica")),
    ("Psicologia Social", _("Psicologia Social")),
    ("Psiquiatria", _("Psiquiatria")),
    ("Química Analítica", _("Química Analítica")),
    ("Química de Macromoléculas", _("Química de Macromoléculas")),
    ("Química Inorgânica", _("Química Inorgânica")),
    ("Química Orgânica", _("Química Orgânica")),
    ("Rádio e Televisão", _("Rádio e Televisão")),
    ("Radiologia e Fotobiologia", _("Radiologia e Fotobiologia")),
    ("Radiologia Médica", _("Radiologia Médica")),
    ("Radiologia Odontológica", _("Radiologia Odontológica")),
    ("Recursos Hídricos", _("Recursos Hídricos")),
    (
        "Recursos Pesqueiros de Águas Interiores",
        _("Recursos Pesqueiros de Águas Interiores"),
    ),
    ("Recursos Pesqueiros Marinhos", _("Recursos Pesqueiros Marinhos")),
    ("Relações Públicas e Propaganda", _("Relações Públicas e Propaganda")),
    ("Reprodução Animal", _("Reprodução Animal")),
    ("Saneamento Ambiental", _("Saneamento Ambiental")),
    ("Saneamento Básico", _("Saneamento Básico")),
    ("Saúde Materno-Infantil", _("Saúde Materno-Infantil")),
    ("Saúde Pública", _("Saúde Pública")),
    ("Serviço Social Aplicado", _("Serviço Social Aplicado")),
    ("Serviços Urbanos e Regionais", _("Serviços Urbanos e Regionais")),
    ("Silvicultura", _("Silvicultura")),
    ("Sistemas Aeroespaciais", _("Sistemas Aeroespaciais")),
    ("Sistemas de Computação", _("Sistemas de Computação")),
    ("Sistemas Elétricos de Potência", _("Sistemas Elétricos de Potência")),
    ("Sociolinguística e Dialetologia", _("Sociolinguística e Dialetologia")),
    ("Sociologia da Saúde", _("Sociologia da Saúde")),
    ("Sociologia do Conhecimento", _("Sociologia do Conhecimento")),
    ("Sociologia do Desenvolvimento", _("Sociologia do Desenvolvimento")),
    ("Sociologia Rural", _("Sociologia Rural")),
    ("Sociologia Urbana", _("Sociologia Urbana")),
    ("Taxonomia dos Grupos Recentes", _("Taxonomia dos Grupos Recentes")),
    ("Taxonomia Vegetal", _("Taxonomia Vegetal")),
    ("Teatro", _("Teatro")),
    ("Técnicas e Operações Florestais", _("Técnicas e Operações Florestais")),
    ("Tecnologia de Alimentos", _("Tecnologia de Alimentos")),
    (
        "Tecnologia de Arquitetura e Urbanismo",
        _("Tecnologia de Arquitetura e Urbanismo"),
    ),
    (
        "Tecnologia de Construção Naval e de Sistemas Oceânicos",
        _("Tecnologia de Construção Naval e de Sistemas Oceânicos"),
    ),
    ("Tecnologia de Reatores", _("Tecnologia de Reatores")),
    (
        "Tecnologia e Utilização de Produtos Florestais",
        _("Tecnologia e Utilização de Produtos Florestais"),
    ),
    ("Tecnologia Química", _("Tecnologia Química")),
    ("Telecomunicações", _("Telecomunicações")),
    ("Teologia Moral", _("Teologia Moral")),
    ("Teologia Pastoral", _("Teologia Pastoral")),
    ("Teologia Sistemática", _("Teologia Sistemática")),
    ("Teoria Antropológica", _("Teoria Antropológica")),
    ("Teoria da Computação", _("Teoria da Computação")),
    ("Teoria da Comunicação", _("Teoria da Comunicação")),
    ("Teoria da Informação", _("Teoria da Informação")),
    ("Teoria do Direito", _("Teoria do Direito")),
    ("Teoria e Análise Linguística", _("Teoria e Análise Linguística")),
    ("Teoria e Filosofia da História", _("Teoria e Filosofia da História")),
    ("Teoria e Método em Arqueologia", _("Teoria e Método em Arqueologia")),
    ("Teoria Econômica", _("Teoria Econômica")),
    ("Teoria Literária", _("Teoria Literária")),
    ("Teoria Política", _("Teoria Política")),
    ("Tópicos Específicos de Educação", _("Tópicos Específicos de Educação")),
    ("Toxicologia", _("Toxicologia")),
    (
        "Tratamento de Águas de Abastecimento e Residuárias",
        _("Tratamento de Águas de Abastecimento e Residuárias"),
    ),
    ("Tratamento de Minérios", _("Tratamento de Minérios")),
    ("Tratamento e Prevenção Psicológica", _("Tratamento e Prevenção Psicológica")),
    ("Veículos e Equipamentos de Controle", _("Veículos e Equipamentos de Controle")),
    ("Zoologia Aplicada", _("Zoologia Aplicada")),
)

languages = (
    ("", ""),
    ("UNDEFINED", _("UNDEFINED")),
    ("de", _("Alemão")),
    ("ar", _("Árabe")),
    ("bn", _("Bengali")),
    ("zh", _("Chinês")),
    ("ko", _("Coreano")),
    ("da", _("Dinamarquês")),
    ("sk", _("Eslovaco")),
    ("sl", _("Esloveno")),
    ("es", _("Espanhol")),
    ("fi", _("Finlandês")),
    ("fr", _("Francês")),
    ("el", _("Grego")),
    ("nl", _("Holandês")),
    ("hu", _("Húngaro")),
    ("hi", _("Indiano")),
    ("id", _("Indonésio")),
    ("en", _("Inglês")),
    ("it", _("Italiano")),
    ("ja", _("Japonês")),
    ("no", _("Norueguês")),
    ("pl", _("Polonês")),
    ("pt", _("Português")),
    ("ro", _("Romeno")),
    ("ru", _("Russo")),
    ("sr", _("Sérvio")),
    ("sv", _("Sueco")),
    ("th", _("Tailandês")),
    ("cs", _("Tcheco")),
    ("tr", _("Turco")),
)

levels = (
    ("", ""),
    ("UNDEFINED", _("UNDEFINED")),
    ("0", _("Level 0")),
    ("1", _("Level 1")),
    ("2", _("Level 2")),
    ("3", _("Level 3")),
)
