# Generated by Django 5.0.8 on 2025-03-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thematic_areas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genericthematicarea",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", ""),
                    ("UNDEFINED", "UNDEFINED"),
                    ("0", "Level 0"),
                    ("1", "Level 1"),
                    ("2", "Level 2"),
                    ("3", "Level 3"),
                ],
                max_length=20,
                null=True,
                verbose_name="Level",
            ),
        ),
    ]
