# Generated by Django 5.0.8 on 2025-05-26 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thematic_areas", "0001_initial"),
        ("wagtaildocs", "0013_delete_uploadeddocument"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="genericthematicarea",
            options={
                "verbose_name": "Área Temática Genérica",
                "verbose_name_plural": "Áreas Temáticas Genéricas",
            },
        ),
        migrations.AlterModelOptions(
            name="genericthematicareafile",
            options={"verbose_name_plural": "Upload de Áreas Temáticas Genéricas"},
        ),
        migrations.AlterModelOptions(
            name="thematicarea",
            options={
                "verbose_name": "Área Temática",
                "verbose_name_plural": "Áreas Temáticas",
            },
        ),
        migrations.AlterModelOptions(
            name="thematicareafile",
            options={"verbose_name_plural": "Upload de Áreas Temáticas"},
        ),
        migrations.AlterField(
            model_name="genericthematicarea",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Data de criação"
            ),
        ),
        migrations.AlterField(
            model_name="genericthematicarea",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criador",
            ),
        ),
        migrations.AlterField(
            model_name="genericthematicarea",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", ""),
                    ("UNDEFINED", "NÃO_DEFINIDO"),
                    ("0", "Nível 0"),
                    ("1", "Nível 1"),
                    ("2", "Nível 2"),
                    ("3", "Nível 3"),
                ],
                max_length=20,
                null=True,
                verbose_name="Nível",
            ),
        ),
        migrations.AlterField(
            model_name="genericthematicarea",
            name="origin",
            field=models.TextField(
                blank=True, null=True, verbose_name="Base de Dados de Origem"
            ),
        ),
        migrations.AlterField(
            model_name="genericthematicarea",
            name="text",
            field=models.TextField(blank=True, null=True, verbose_name="Área Temática"),
        ),
        migrations.AlterField(
            model_name="genericthematicarea",
            name="updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Data da última atualização"
            ),
        ),
        migrations.AlterField(
            model_name="genericthematicarea",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Atualizador",
            ),
        ),
        migrations.AlterField(
            model_name="genericthematicareafile",
            name="attachment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtaildocs.document",
                verbose_name="Anexo",
            ),
        ),
        migrations.AlterField(
            model_name="genericthematicareafile",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Data de criação"
            ),
        ),
        migrations.AlterField(
            model_name="genericthematicareafile",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criador",
            ),
        ),
        migrations.AlterField(
            model_name="genericthematicareafile",
            name="is_valid",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="É válido?"
            ),
        ),
        migrations.AlterField(
            model_name="genericthematicareafile",
            name="line_count",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Número de linhas"
            ),
        ),
        migrations.AlterField(
            model_name="genericthematicareafile",
            name="updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Data da última atualização"
            ),
        ),
        migrations.AlterField(
            model_name="genericthematicareafile",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Atualizador",
            ),
        ),
        migrations.AlterField(
            model_name="thematicarea",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Data de criação"
            ),
        ),
        migrations.AlterField(
            model_name="thematicarea",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criador",
            ),
        ),
        migrations.AlterField(
            model_name="thematicarea",
            name="level0",
            field=models.TextField(
                blank=True,
                help_text="Aqui devem ser cadastradas as áreas temáticas da CAPES, mais sobre essas áreas acesse: https://www.gov.br/capes/pt-br/acesso-a-informacao/acoes-e-programas/avaliacao/sobre-a-avaliacao/areas-avaliacao/sobre-as-areas-de-avaliacao/sobre-as-areas-de-avaliacao",
                null=True,
                verbose_name="Nível 0",
            ),
        ),
        migrations.AlterField(
            model_name="thematicarea",
            name="level1",
            field=models.TextField(
                blank=True,
                help_text="Aqui devem ser cadastradas as áreas temáticas da CAPES, mais sobre essas áreas acesse: https://www.gov.br/capes/pt-br/acesso-a-informacao/acoes-e-programas/avaliacao/sobre-a-avaliacao/areas-avaliacao/sobre-as-areas-de-avaliacao/sobre-as-areas-de-avaliacao",
                null=True,
                verbose_name="Nível 1",
            ),
        ),
        migrations.AlterField(
            model_name="thematicarea",
            name="level2",
            field=models.TextField(
                blank=True,
                help_text="Aqui devem ser cadastradas as áreas temáticas da CAPES, mais sobre essas áreas acesse: https://www.gov.br/capes/pt-br/acesso-a-informacao/acoes-e-programas/avaliacao/sobre-a-avaliacao/areas-avaliacao/sobre-as-areas-de-avaliacao/sobre-as-areas-de-avaliacao",
                null=True,
                verbose_name="Nível 2",
            ),
        ),
        migrations.AlterField(
            model_name="thematicarea",
            name="updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Data da última atualização"
            ),
        ),
        migrations.AlterField(
            model_name="thematicarea",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Atualizador",
            ),
        ),
        migrations.AlterField(
            model_name="thematicareafile",
            name="attachment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtaildocs.document",
                verbose_name="Anexo",
            ),
        ),
        migrations.AlterField(
            model_name="thematicareafile",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Data de criação"
            ),
        ),
        migrations.AlterField(
            model_name="thematicareafile",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criador",
            ),
        ),
        migrations.AlterField(
            model_name="thematicareafile",
            name="is_valid",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="É válido?"
            ),
        ),
        migrations.AlterField(
            model_name="thematicareafile",
            name="line_count",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Número de linhas"
            ),
        ),
        migrations.AlterField(
            model_name="thematicareafile",
            name="updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Data da última atualização"
            ),
        ),
        migrations.AlterField(
            model_name="thematicareafile",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Atualizador",
            ),
        ),
    ]
