# Generated by Django 3.2.12 on 2022-10-16 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtaildocs', '0012_uploadeddocument'),
        ('thematic_areas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thematicarea',
            name='level0',
            field=models.CharField(blank=True, choices=[('', ''), ('ALL', 'ALL'), ('UNDEFINED', 'UNDEFINED'), ('NOT_APPLICABLE', 'NOT APPLICABLE'), ('Ciências da Vida', 'Ciências da Vida'), ('Ciências Exatas, Tecnológicas e Multidisciplinar', 'Ciências Exatas, Tecnológicas e Multidisciplinar'), ('Humanidades', 'Humanidades')], help_text='Here the thematic colleges of CAPES must be registered, more about these areas access: https://www.gov.br/capes/pt-br/acesso-a-informacao/acoes-e-programas/avaliacao/sobre-a-avaliacao/areas-avaliacao/sobre-as-areas-de-avaliacao/sobre-as-areas-de-avaliacao', max_length=255, null=True, verbose_name='Level 0'),
        ),
        migrations.AlterField(
            model_name='thematicarea',
            name='level1',
            field=models.CharField(blank=True, choices=[('', ''), ('ALL', 'ALL'), ('UNDEFINED', 'UNDEFINED'), ('NOT_APPLICABLE', 'NOT APPLICABLE'), ('Ciências Agrárias', 'Ciências Agrárias'), ('Ciências Biológicas', 'Ciências Biológicas'), ('Ciências da Saúde', 'Ciências da Saúde'), ('Ciências Exatas e da Terra', 'Ciências Exatas e da Terra'), ('Ciências Humanas', 'Ciências Humanas'), ('Ciências Sociais Aplicadas', 'Ciências Sociais Aplicadas'), ('Engenharias', 'Engenharias'), ('Linguística, Letras e Artes', 'Linguística, Letras e Artes'), ('Multidisciplinar', 'Multidisciplina')], help_text='Here the thematic colleges of CAPES must be registered, more about these areas access: https://www.gov.br/capes/pt-br/acesso-a-informacao/acoes-e-programas/avaliacao/sobre-a-avaliacao/areas-avaliacao/sobre-as-areas-de-avaliacao/sobre-as-areas-de-avaliacao', max_length=255, null=True, verbose_name='Level 1'),
        ),
        migrations.AlterField(
            model_name='thematicarea',
            name='level2',
            field=models.CharField(blank=True, choices=[('', ''), ('ALL', 'ALL'), ('UNDEFINED', 'UNDEFINED'), ('NOT_APPLICABLE', 'NOT APPLICABLE'), ('Administração Pública e de Empresas, Ciências Contábeis e Turismo', 'Administração Pública e de Empresas, Ciências Contábeis e Turismo'), ('Antropologia / Arqueologia', 'Antropologia / Arqueologia'), ('Arquitetura, Urbanismo e Design', 'Arquitetura, Urbanismo e Design'), ('Artes', 'Artes'), ('Astronomia / Física', 'Astronomia / Física'), ('Biodiversidade', 'Biodiversidade'), ('Biotecnologia', 'Biotecnologia'), ('Ciência da Computação', 'Ciência da Computação'), ('Ciência de Alimentos', 'Ciência de Alimentos'), ('Ciência Política e Relações Internacionais', 'Ciência Política e Relações Internacionais'), ('Ciências Agrárias I', 'Ciências Agrárias I'), ('Ciências Ambientais', 'Ciências Ambientais'), ('Ciências Biológicas I', 'Ciências Biológicas I'), ('Ciências Biológicas II', 'Ciências Biológicas II'), ('Ciências Biológicas III', 'Ciências Biológicas III'), ('Ciências da Religião e Teologia', 'Ciências da Religião e Teologia'), ('Comunicação e Informação', 'Comunicação e Informação'), ('Direito', 'Direito'), ('Economia', 'Economia'), ('Educação', 'Educação'), ('Educação Física', 'Educação Física'), ('Enfermagem', 'Enfermagem'), ('Engenharias I', 'Engenharias I'), ('Engenharias II', 'Engenharias II'), ('Engenharias III', 'Engenharias III'), ('Engenharias IV', 'Engenharias IV'), ('Ensino', 'Ensino'), ('Farmácia', 'Farmácia'), ('Filosofia', 'Filosofia'), ('Geociências', 'Geociências'), ('Geografia', 'Geografia'), ('História', 'História'), ('Interdisciplinar', 'Interdisciplinar'), ('Linguística e Literatura', 'Linguística e Literatura'), ('Matemática / Probabilidade e Estatística', 'Matemática / Probabilidade e Estatística'), ('Materiais', 'Materiais'), ('Medicina I', 'Medicina I'), ('Medicina II', 'Medicina II'), ('Medicina III', 'Medicina III'), ('Medicina Veterinária', 'Medicina Veterinária'), ('Nutrição', 'Nutrição'), ('Odontologia', 'Odontologia'), ('Planejamento Urbano e Regional / Demografia', 'Planejamento Urbano e Regional / Demografia'), ('Psicologia', 'Psicologia'), ('Química', 'Química'), ('Saúde Coletiva', 'Saúde Coletiva'), ('Serviço Social', 'Serviço Social'), ('Sociologia', 'Sociologia'), ('Zootecnia / Recursos Pesqueiros', 'Zootecnia / Recursos Pesqueiros')], help_text='Here the thematic colleges of CAPES must be registered, more about these areas access: https://www.gov.br/capes/pt-br/acesso-a-informacao/acoes-e-programas/avaliacao/sobre-a-avaliacao/areas-avaliacao/sobre-as-areas-de-avaliacao/sobre-as-areas-de-avaliacao', max_length=255, null=True, verbose_name='Level 2'),
        ),
        migrations.CreateModel(
            name='ThematicAreaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('is_valid', models.BooleanField(blank=True, default=False, null=True, verbose_name='Is valid?')),
                ('line_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='Number of lines')),
                ('attachment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Attachment')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='thematicareafile_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thematicareafile_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
            ],
            options={
                'verbose_name_plural': 'Thematic Areas Upload',
            },
        ),
    ]
