# Generated by Django 5.0.8 on 2025-05-26 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("thematic_areas", "0002_alter_genericthematicarea_level"),
        ("thematic_areas", "0002_alter_genericthematicarea_options_and_more"),
    ]

    operations = []
