# Generated by Django 4.1.7 on 2023-02-28 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_language"),
        ("thematic_areas", "0002_alter_genericthematicarea_creator_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="genericthematicarea",
            name="lang",
        ),
        migrations.AddField(
            model_name="genericthematicarea",
            name="language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.language",
                verbose_name="Idioma",
            ),
        ),
    ]
