# Generated by Django 4.1.7 on 2023-03-02 12:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("thematic_areas", "0003_alter_genericthematicarea_level_up_and_more"),
        ("thematic_areas", "0003_remove_genericthematicarea_lang_and_more"),
    ]

    operations = []
