# Generated by Django 5.0.8 on 2025-05-26 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thematic_areas", "0003_merge_20250526_1846"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genericthematicarea",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", ""),
                    ("UNDEFINED", "NÃO_DEFINIDO"),
                    ("0", "Nível 0"),
                    ("1", "Nível 1"),
                    ("2", "Nível 2"),
                    ("3", "Nível 3"),
                ],
                max_length=20,
                null=True,
                verbose_name="Nível",
            ),
        ),
    ]
