# Generated by Django 3.2.12 on 2022-11-17 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thematic_areas', '0003_genericthematicarea_genericthematicareafile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GenericThematicAreaFile',
        ),
    ]
