# Generated by Django 5.2.3 on 2025-09-01 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_language_options_alter_license_options_and_more"),
        ("thematic_areas", "0004_alter_genericthematicarea_level"),
        ("wagtaildocs", "0014_alter_document_file_size"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="genericthematicarea",
            options={
                "verbose_name": "Generic Thematic Area",
                "verbose_name_plural": "Generic Thematic Areas",
            },
        ),
        migrations.AlterModelOptions(
            name="genericthematicareafile",
            options={"verbose_name_plural": "Generic Thematic Areas Upload"},
        ),
        migrations.AlterModelOptions(
            name="thematicarea",
            options={
                "verbose_name": "Thematic Area",
                "verbose_name_plural": "Thematic Areas",
            },
        ),
        migrations.AlterModelOptions(
            name="thematicareafile",
            options={"verbose_name_plural": "Thematic Areas Upload"},
        ),
        migrations.AlterField(
            model_name="genericthematicarea",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creation date"),
        ),
        migrations.AlterField(
            model_name="genericthematicarea",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AlterField(
            model_name="genericthematicarea",
            name="language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.language",
                verbose_name="Language",
            ),
        ),
        migrations.AlterField(
            model_name="genericthematicarea",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", ""),
                    ("UNDEFINED", "UNDEFINED"),
                    ("0", "Level 0"),
                    ("1", "Level 1"),
                    ("2", "Level 2"),
                    ("3", "Level 3"),
                ],
                max_length=20,
                null=True,
                verbose_name="Level",
            ),
        ),
        migrations.AlterField(
            model_name="genericthematicarea",
            name="origin",
            field=models.TextField(
                blank=True, null=True, verbose_name="Origin Data Base"
            ),
        ),
        migrations.AlterField(
            model_name="genericthematicarea",
            name="text",
            field=models.TextField(blank=True, null=True, verbose_name="Thematic Area"),
        ),
        migrations.AlterField(
            model_name="genericthematicarea",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Last update date"),
        ),
        migrations.AlterField(
            model_name="genericthematicarea",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updater",
            ),
        ),
        migrations.AlterField(
            model_name="genericthematicareafile",
            name="attachment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtaildocs.document",
                verbose_name="Attachment",
            ),
        ),
        migrations.AlterField(
            model_name="genericthematicareafile",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creation date"),
        ),
        migrations.AlterField(
            model_name="genericthematicareafile",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AlterField(
            model_name="genericthematicareafile",
            name="is_valid",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Is valid?"
            ),
        ),
        migrations.AlterField(
            model_name="genericthematicareafile",
            name="line_count",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Number of lines"
            ),
        ),
        migrations.AlterField(
            model_name="genericthematicareafile",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Last update date"),
        ),
        migrations.AlterField(
            model_name="genericthematicareafile",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updater",
            ),
        ),
        migrations.AlterField(
            model_name="thematicarea",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creation date"),
        ),
        migrations.AlterField(
            model_name="thematicarea",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AlterField(
            model_name="thematicarea",
            name="level0",
            field=models.TextField(
                blank=True,
                help_text="Here the thematic colleges of CAPES must be registered, more about these areas access: https://www.gov.br/capes/pt-br/acesso-a-informacao/acoes-e-programas/avaliacao/sobre-a-avaliacao/areas-avaliacao/sobre-as-areas-de-avaliacao/sobre-as-areas-de-avaliacao",
                null=True,
                verbose_name="Level 0",
            ),
        ),
        migrations.AlterField(
            model_name="thematicarea",
            name="level1",
            field=models.TextField(
                blank=True,
                help_text="Here the thematic colleges of CAPES must be registered, more about these areas access: https://www.gov.br/capes/pt-br/acesso-a-informacao/acoes-e-programas/avaliacao/sobre-a-avaliacao/areas-avaliacao/sobre-as-areas-de-avaliacao/sobre-as-areas-de-avaliacao",
                null=True,
                verbose_name="Level 1",
            ),
        ),
        migrations.AlterField(
            model_name="thematicarea",
            name="level2",
            field=models.TextField(
                blank=True,
                help_text="Here the thematic colleges of CAPES must be registered, more about these areas access: https://www.gov.br/capes/pt-br/acesso-a-informacao/acoes-e-programas/avaliacao/sobre-a-avaliacao/areas-avaliacao/sobre-as-areas-de-avaliacao/sobre-as-areas-de-avaliacao",
                null=True,
                verbose_name="Level 2",
            ),
        ),
        migrations.AlterField(
            model_name="thematicarea",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Last update date"),
        ),
        migrations.AlterField(
            model_name="thematicarea",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updater",
            ),
        ),
        migrations.AlterField(
            model_name="thematicareafile",
            name="attachment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtaildocs.document",
                verbose_name="Attachment",
            ),
        ),
        migrations.AlterField(
            model_name="thematicareafile",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creation date"),
        ),
        migrations.AlterField(
            model_name="thematicareafile",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AlterField(
            model_name="thematicareafile",
            name="is_valid",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Is valid?"
            ),
        ),
        migrations.AlterField(
            model_name="thematicareafile",
            name="line_count",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Number of lines"
            ),
        ),
        migrations.AlterField(
            model_name="thematicareafile",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Last update date"),
        ),
        migrations.AlterField(
            model_name="thematicareafile",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updater",
            ),
        ),
    ]
