# Generated by Django 3.2.12 on 2022-11-17 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thematic_areas', '0004_delete_genericthematicareafile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericthematicarea',
            name='level0',
        ),
        migrations.RemoveField(
            model_name='genericthematicarea',
            name='level1',
        ),
        migrations.RemoveField(
            model_name='genericthematicarea',
            name='level2',
        ),
        migrations.AddField(
            model_name='genericthematicarea',
            name='level',
            field=models.CharField(blank=True, choices=[('', ''), ('UNDEFINED', 'UNDEFINED'), ('0', 'Level 0'), ('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3')], max_length=20, null=True, verbose_name='Nível'),
        ),
        migrations.CreateModel(
            name='GenericThematicAreaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('is_valid', models.BooleanField(blank=True, default=False, null=True, verbose_name='Is valid?')),
                ('line_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='Number of lines')),
                ('attachment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Attachment')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='genericthematicareafile_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genericthematicareafile_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
            ],
            options={
                'verbose_name_plural': 'Generic Thematic Areas Upload',
            },
        ),
    ]
