# Generated by Django 3.2.12 on 2022-11-17 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thematic_areas', '0005_auto_20221117_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericthematicarea',
            name='level_down',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='GenericThematicAreaLevelDown', to='thematic_areas.genericthematicarea'),
        ),
        migrations.AddField(
            model_name='genericthematicarea',
            name='level_up',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='GenericThematicAreaLevelUp', to='thematic_areas.genericthematicarea'),
        ),
    ]
