# Generated by Django 3.2.12 on 2022-11-17 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thematic_areas', '0006_auto_20221117_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericthematicarea',
            name='level_down',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='GenericThematic_Area_Level_Down', to='thematic_areas.genericthematicarea'),
        ),
        migrations.AlterField(
            model_name='genericthematicarea',
            name='level_up',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='GenericThematic_Area_Level_Up', to='thematic_areas.genericthematicarea'),
        ),
    ]
