# Generated by Django 3.2.12 on 2022-11-17 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thematic_areas', '0007_auto_20221117_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericthematicarea',
            name='level_down',
        ),
    ]
