from django.utils.translation import gettext_lazy as _


journal_permissions = [
    ("can_edit_official", _("Can edit official journal")),
    ("can_edit_title", _("Can edit title")),
    ("can_edit_short_title", _("Can edit short title")),
    ("can_edit_submission_online_url", _("Can edit submission online url")),
    ("can_edit_contact_name", _("Can edit contact name")),
    ("can_edit_contact_address", _("Can edit contact address")),
    ("can_edit_contact_location", _("Can edit contact location")),
    ("can_edit_open_access", _("Can edit open access")),
    ("can_edit_url_oa", _("Can edit url Open Science accordance form")),
    ("can_edit_main_collection", _("Can edit main collection")),
    ("can_edit_frequency", _("Can edit frequency")),
    ("can_edit_publishing_model", _("Can edit publishing model")),
    ("can_edit_subject_descriptor", _("Can edit subject descriptor")),
    ("can_edit_subject", _("Can edit subject")),
    ("can_edit_wos_db", _("Can edit Web of Knowledge Databases")),
    ("can_edit_wos_area", _("Can edit Web of Knowledge Subject Categories")),
    ("can_edit_abstract_language", _("Can edit abstract language")),
    ("can_edit_standard", _("Can edit standard")),
    ("can_edit_alphabet", _("Can edit alphabet")),
    ("can_edit_type_of_literature", _("Can edit type of literature")),
    ("can_edit_treatment_level", _("Can edit treatment level")),
    ("can_edit_level_of_publication", _("Can edit level of publication")),
    ("can_edit_national_code", _("Can edit national code")),
    ("can_edit_classification", _("Can edit classification")),
    ("can_edit_vocabulary", _("Can edit vocabulary")),
    ("can_edit_indexed_at", _("Can edit indexed at")),
    ("can_edit_additional_indexed_at", _("Can edit additional indexed at")),
    ("can_edit_journal_url", _("Can edit journal url")),
    ("can_edit_use_license", _("Can edit use license")),
    ("can_edit_journal_use_license", _("Can edit journal use license")),
    ("can_edit_center_code", _("Can edit center code")),
    ("can_edit_identification_number", _("Can edit identification number")),
    ("can_edit_ftp", _("Can edit ftp")),
    ("can_edit_user_subscription", _("Can edit user subscription")),
    ("can_edit_subtitle", _("Can edit subtitle")),
    ("can_edit_section", _("Can edit section")),
    ("can_edit_has_supplement", _("Can edit has supplement")),
    ("can_edit_is_supplement", _("Can edit is supplement")),
    ("can_edit_acronym_letters", _("Can edit acronym letters")),
    ("can_edit_author_name", _("Can edit author name")),
    ("can_edit_manuscript_length", _("Can edit manuscript length")),
    ("can_edit_format_check_list", _("Can edit format check list")),
    ("can_edit_digital_pa", _("Can edit digital pa")),
    ("can_edit_doi_prefix", _("Can edit doi prefix")),
    ("can_edit_mission", _("Can edit mission")),
    ("can_edit_owner_history", _("Can edit owner history")),
    ("can_edit_publisher_history", _("Can edit publisher history")),
    ("can_edit_sponsor_history", _("Can edit sponsor history")),
    ("can_edit_copyright_holder_history", _("Can edit copyright holder history")),
    ("can_edit_journalsocialnetwork", _("Can edit journalsocialnetwork")),
    ("can_edit_file_oa", _("Can edit file oa")),
    ("can_edit_journal_email", _("Can edit journal email")),
    ("can_edit_history", _("Can edit history")),
    ("can_edit_focus", _("Can edit focus")),
    ("can_edit_thematic_area", _("Can edit thematic area")),
    ("can_edit_annotation", _("Can edit annotation")),
    ("can_edit_ecommittee", _("Can edit ecommittee")),
    ("can_edit_other_titles", _("Can edit other titles")),
    ("can_edit_related_journal_urls", _("Can edit related journal urls")),
    ("can_edit_open_data", _("Can edit open data")),
    ("can_edit_preprint", _("Can edit preprint")),
    ("can_edit_review", _("Can edit review")),
    ("can_edit_open_science_compliance", _("Can edit open science compliance")),
    ("can_edit_ethics", _("Can edit ethics")),
    ("can_edit_copyrigth", _("Can edit copyrigth")),
    ("can_edit_website_responsibility", _("Can edit website responsibility")),
    ("can_edit_author_responsibility", _("Can edit author responsibility")),
    ("can_edit_policies", _("Can edit policies")),
    ("can_edit_digital_preservation", _("Can edit digital preservation")),
    ("can_edit_conflict_policy", _("Can edit conflict policy")),
    ("can_edit_software_adoption", _("Can edit software adoption")),
    ("can_edit_gender_issues", _("Can edit Gender Issues")),
    ("can_edit_fee_charging", _("Can edit Fee Charging")),
    ("can_edit_editorial_policy", _("Can edit Editorial Policy")),
    ("can_edit_accepted_documment_types", _("Can edit Accepted Document Types")),
    ("can_edit_authors_contributions", _("Can edit Authors Contributions")),
    ("can_edit_preparing_manuscript", _("Can edit Preparing Manuscript")),
    ("can_edit_digital_assets", _("Can edit Digital Assets")),
    ("can_edit_citations_and_references", _("Can edit Citations and References")),
    (
        "can_edit_supp_docs_submission",
        _("Can edit Supplementary Documents Required for Submission"),
    ),
    ("can_edit_financing_statement", _("Can edit Financing Statement")),
    ("can_edit_acknowledgements", _("Can edit Acknowledgements")),
    ("can_edit_additional_information", _("Can edit Additional Information")),
    ("can_edit_text_language", _("Can edit Text Language")),
    ("can_edit_logo", _("Can edit logo")),
    ("can_edit_title_in_database", _("Can edit title in database")),
    ("can_edit_copyright", _("Can edit copyright")),
]
