# Generated by Django 4.1.10 on 2023-10-31 13:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("xmlsps", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="xmljournal",
            unique_together={("issn_electronic", "issn_print")},
        ),
    ]
