# Generated by Django 4.1.8 on 2023-07-14 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("xmlsps", "0002_remove_xmlsps_xml_xmlversion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="xmlsps",
            name="xml_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="xmlsps.xmlversion",
            ),
        ),
    ]
