# Generated by Django 4.1.8 on 2023-07-29 22:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("xmlsps", "0004_xmlsps_is_published"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="xmlsps",
            name="xmlsps_xmls_xml_jou_77fb2b_idx",
        ),
        migrations.RemoveIndex(
            model_name="xmlsps",
            name="xmlsps_xmls_xml_iss_44159b_idx",
        ),
    ]
