# Generated by Django 3.2.12 on 2022-11-30 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_date', models.DateField(blank=True, null=True, verbose_name='Initial Date')),
                ('final_date', models.DateField(blank=True, null=True, verbose_name='Final Date')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='institution.institution')),
            ],
        ),
    ]
