# Generated by Django 3.2.12 on 2023-01-27 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('institution_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='institution.institution')),
            ],
            options={
                'abstract': False,
            },
            bases=('institution.institution',),
        ),
        migrations.AddField(
            model_name='institution',
            name='is_official',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('unknow', 'unknow')], default='unknow', max_length=6, verbose_name='Is official'),
        ),
        migrations.AddField(
            model_name='institution',
            name='official',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.institution'),
        ),
    ]
