# Generated by Django 3.2.12 on 2022-10-16 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institution', '0002_auto_20220826_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='acronym',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Institution Acronym'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='creator',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='institution_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='level_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Organization Level 1'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='level_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Organization Level 2'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='level_3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Organization Level 3'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Last update date'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institution_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater'),
        ),
    ]
