# Generated by Django 4.1.10 on 2023-09-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institution", "0002_institution_institution_name_955317_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="copyright_holder",
            field=models.TextField(
                blank=True, null=True, verbose_name="Copy Right Holder"
            ),
        ),
    ]
