# Generated by Django 4.1.10 on 2023-10-05 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("institution", "0003_institution_copyright_holder"),
    ]

    operations = [
        migrations.CreateModel(
            name="CopyRightHolder",
            fields=[
                (
                    "institution_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="institution.institution",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("institution.institution",),
        ),
        migrations.RemoveField(
            model_name="institution",
            name="copyright_holder",
        ),
    ]
