# Generated by Django 4.2.7 on 2024-03-15 01:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institution", "0004_institutiontype"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="institution_type_mec",
            field=models.ManyToManyField(
                blank=True,
                to="institution.institutiontype",
                verbose_name="Institution Type (MEC)",
            ),
        ),
    ]
