# Generated by Django 4.2.7 on 2023-12-11 04:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("institution", "0004_remove_institution_institution_name_955317_idx_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="copyrightholder",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="editorialmanager",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="owner",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="publisher",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="sponsor",
            unique_together=set(),
        ),
    ]
