# Generated by Django 4.1.10 on 2023-10-09 19:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("institution", "0004_copyrightholder_remove_institution_copyright_holder"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CopyRightHolder",
        ),
    ]
