# Generated by Django 4.2.7 on 2023-12-12 16:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("institution", "0005_alter_copyrightholder_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="copyrightholder",
            unique_together={("institution",)},
        ),
        migrations.AlterUniqueTogether(
            name="editorialmanager",
            unique_together={("institution",)},
        ),
        migrations.AlterUniqueTogether(
            name="owner",
            unique_together={("institution",)},
        ),
        migrations.AlterUniqueTogether(
            name="publisher",
            unique_together={("institution",)},
        ),
        migrations.AlterUniqueTogether(
            name="sponsor",
            unique_together={("institution",)},
        ),
    ]
