# Generated by Django 4.1.10 on 2023-10-11 19:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "institution",
            "0006_copyrightholder_editorialmanager_owner_publisher_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="copyrightholderhistoryitem",
            old_name="copyright_holder",
            new_name="institution",
        ),
        migrations.RenameField(
            model_name="editorialmanagerhistoryitem",
            old_name="editorial_manager",
            new_name="institution",
        ),
        migrations.RenameField(
            model_name="ownerhistoryitem",
            old_name="owner",
            new_name="institution",
        ),
        migrations.RenameField(
            model_name="publisherhistoryitem",
            old_name="publisher",
            new_name="institution",
        ),
        migrations.RenameField(
            model_name="sponsorhistoryitem",
            old_name="sponsor",
            new_name="institution",
        ),
    ]
