# Generated by Django 5.2.7 on 2026-03-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institution", "0007_alter_copyrightholder_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="url",
            field=models.URLField(blank=True, null=True, verbose_name="URL"),
        ),
        migrations.AlterField(
            model_name="scimago",
            name="url",
            field=models.URLField(blank=True, null=True, verbose_name="URL"),
        ),
    ]
