# Generated by Django 4.1.10 on 2023-10-12 01:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("institution", "0003_scimagofile_scimago_and_more"),
        (
            "institution",
            "0007_rename_copyright_holder_copyrightholderhistoryitem_institution_and_more",
        ),
    ]

    operations = []
