# Generated by Django 4.1.10 on 2023-11-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pid_provider", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pidrequest",
            name="v3",
            field=models.CharField(
                blank=True, max_length=23, null=True, verbose_name="PID v3"
            ),
        ),
        migrations.AddIndex(
            model_name="pidrequest",
            index=models.Index(fields=["v3"], name="pid_provide_v3_afbea7_idx"),
        ),
    ]
