# Generated by Django 4.1.8 on 2023-07-12 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("xmlsps", "0001_initial"),
        ("pid_provider", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pidproviderxml",
            name="current_xml",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="xmlsps.xmlsps",
            ),
        ),
        migrations.AlterField(
            model_name="pidproviderxml",
            name="issue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="xmlsps.xmlissue",
            ),
        ),
        migrations.AlterField(
            model_name="pidproviderxml",
            name="journal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="xmlsps.xmljournal",
            ),
        ),
        migrations.DeleteModel(
            name="XMLIssue",
        ),
        migrations.DeleteModel(
            name="XMLJournal",
        ),
    ]
