# Generated by Django 4.1.10 on 2023-08-02 02:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pid_provider", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pidproviderxml",
            name="origin_date",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Origin date"
            ),
        ),
    ]
