# Generated by Django 4.2.7 on 2024-03-17 22:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pid_provider", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pidproviderxml",
            options={"ordering": ["-updated", "-created", "pkg_name"]},
        ),
    ]
