# Generated by Django 4.2.6 on 2023-11-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pid_provider", "0002_pidrequest_v3_pidrequest_pid_provide_v3_afbea7_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="pidrequest",
            name="times",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="pidrequest",
            index=models.Index(fields=["times"], name="pid_provide_times_03e559_idx"),
        ),
        migrations.AddIndex(
            model_name="pidrequest",
            index=models.Index(fields=["detail"], name="pid_provide_detail_eeef1e_idx"),
        ),
    ]
