# Generated by Django 4.2.7 on 2023-12-31 15:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pid_provider", "0002_alter_collectionpidrequest_unique_together"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="pidrequest",
            name="pid_provide_times_03e559_idx",
        ),
        migrations.RemoveIndex(
            model_name="pidrequest",
            name="pid_provide_detail_eeef1e_idx",
        ),
    ]
