# Generated by Django 4.1.8 on 2023-07-13 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pid_provider", "0002_pidproviderxml_current_xml_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PidChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "pid_type",
                    models.CharField(
                        blank=True, max_length=23, null=True, verbose_name="PID type"
                    ),
                ),
                (
                    "old",
                    models.CharField(
                        blank=True, max_length=23, null=True, verbose_name="PID old"
                    ),
                ),
                (
                    "new",
                    models.CharField(
                        blank=True, max_length=23, null=True, verbose_name="PID new"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pid_provider.xmlversion",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="pidchange",
            index=models.Index(fields=["old"], name="pid_provide_old_74f4ac_idx"),
        ),
        migrations.AddIndex(
            model_name="pidchange",
            index=models.Index(fields=["new"], name="pid_provide_new_7260e5_idx"),
        ),
        migrations.AddIndex(
            model_name="pidchange",
            index=models.Index(
                fields=["pid_type"], name="pid_provide_pid_typ_cb60fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pidchange",
            index=models.Index(
                fields=["version"], name="pid_provide_version_f0e2c3_idx"
            ),
        ),
    ]
