# Generated by Django 4.2.7 on 2024-03-30 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pid_provider", "0002_alter_pidproviderxml_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="PidProviderEndpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        choices=[("fix-pid-v2", "fix-pid-v2")],
                        max_length=16,
                        null=True,
                        verbose_name="Endpoint name",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Endpoint URL",
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                (
                    "config",
                    modelcluster.fields.ParentalKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="endpoint",
                        to="pid_provider.pidproviderconfig",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["name"], name="pid_provide_name_870abe_idx"),
                    models.Index(
                        fields=["enabled"], name="pid_provide_enabled_5b5f83_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FixPidV2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "incorrect_pid_v2",
                    models.CharField(
                        blank=True,
                        max_length=24,
                        null=True,
                        verbose_name="Incorrect v2",
                    ),
                ),
                (
                    "correct_pid_v2",
                    models.CharField(
                        blank=True, max_length=24, null=True, verbose_name="Correct v2"
                    ),
                ),
                (
                    "fixed_in_upload",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "fixed_in_core",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "pid_provider_xml",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pid_provider.pidproviderxml",
                        unique=True,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated", "-created"],
                "indexes": [
                    models.Index(
                        fields=["incorrect_pid_v2"],
                        name="pid_provide_incorre_17a11a_idx",
                    ),
                    models.Index(
                        fields=["correct_pid_v2"], name="pid_provide_correct_ac149d_idx"
                    ),
                    models.Index(
                        fields=["fixed_in_core"], name="pid_provide_fixed_i_4e3bd1_idx"
                    ),
                    models.Index(
                        fields=["fixed_in_upload"],
                        name="pid_provide_fixed_i_0109bc_idx",
                    ),
                ],
            },
        ),
    ]
