# Generated by Django 4.2.7 on 2024-01-15 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("xmlsps", "0001_initial"),
        (
            "pid_provider",
            "0003_remove_pidrequest_pid_provide_times_03e559_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchedPid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OtherPid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "pid_type",
                    models.CharField(
                        blank=True, max_length=7, null=True, verbose_name="PID type"
                    ),
                ),
                (
                    "pid_in_xml",
                    models.CharField(
                        blank=True,
                        max_length=23,
                        null=True,
                        verbose_name="PID pid_in_xml",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PidConflict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "v3",
                    models.CharField(
                        blank=True, max_length=23, null=True, verbose_name="PID v3"
                    ),
                ),
                ("conflict_count", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name="pidchange",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="pidchange",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="pidchange",
            name="version",
        ),
        migrations.RemoveField(
            model_name="pidproviderxml",
            name="website_publication_date",
        ),
        migrations.AddField(
            model_name="pidproviderxml",
            name="available_since",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Available since"
            ),
        ),
        migrations.AddField(
            model_name="pidproviderxml",
            name="other_pid_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pidproviderxml",
            name="z_journal_title",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="journal title"
            ),
        ),
        migrations.AlterField(
            model_name="pidproviderxml",
            name="aop_pid",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="AOP PID"
            ),
        ),
        migrations.AlterField(
            model_name="pidproviderxml",
            name="elocation_id",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="elocation id"
            ),
        ),
        migrations.AlterField(
            model_name="pidproviderxml",
            name="fpage",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="fpage"
            ),
        ),
        migrations.AlterField(
            model_name="pidproviderxml",
            name="fpage_seq",
            field=models.CharField(
                blank=True, max_length=8, null=True, verbose_name="fpage_seq"
            ),
        ),
        migrations.AlterField(
            model_name="pidproviderxml",
            name="issn_electronic",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="issn_epub"
            ),
        ),
        migrations.AlterField(
            model_name="pidproviderxml",
            name="issn_print",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="issn_ppub"
            ),
        ),
        migrations.AlterField(
            model_name="pidproviderxml",
            name="lpage",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="lpage"
            ),
        ),
        migrations.AlterField(
            model_name="pidproviderxml",
            name="number",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="number"
            ),
        ),
        migrations.AlterField(
            model_name="pidproviderxml",
            name="suppl",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="suppl"
            ),
        ),
        migrations.AlterField(
            model_name="pidproviderxml",
            name="v2",
            field=models.CharField(
                blank=True, max_length=24, null=True, verbose_name="v2"
            ),
        ),
        migrations.AlterField(
            model_name="pidproviderxml",
            name="volume",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="volume"
            ),
        ),
        migrations.AddIndex(
            model_name="pidproviderxml",
            index=models.Index(
                fields=["z_journal_title"], name="pid_provide_z_journ_1dc283_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pidproviderxml",
            index=models.Index(
                fields=["other_pid_count"], name="pid_provide_other_p_409926_idx"
            ),
        ),
        migrations.DeleteModel(
            name="PidChange",
        ),
        migrations.AddField(
            model_name="pidconflict",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AddField(
            model_name="pidconflict",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updater",
            ),
        ),
        migrations.AddField(
            model_name="otherpid",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AddField(
            model_name="otherpid",
            name="pid_provider_xml",
            field=modelcluster.fields.ParentalKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pid_changes",
                to="pid_provider.pidproviderxml",
            ),
        ),
        migrations.AddField(
            model_name="otherpid",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updater",
            ),
        ),
        migrations.AddField(
            model_name="otherpid",
            name="version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="xmlsps.xmlversion",
            ),
        ),
        migrations.AddField(
            model_name="matchedpid",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AddField(
            model_name="matchedpid",
            name="pid_conflict",
            field=modelcluster.fields.ParentalKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owners",
                to="pid_provider.pidconflict",
            ),
        ),
        migrations.AddField(
            model_name="matchedpid",
            name="pid_provider_xml",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pid_provider.pidproviderxml",
            ),
        ),
        migrations.AddField(
            model_name="matchedpid",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updater",
            ),
        ),
        migrations.AddIndex(
            model_name="pidconflict",
            index=models.Index(fields=["v3"], name="pid_provide_v3_7f9e6e_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="pidconflict",
            unique_together={("v3",)},
        ),
        migrations.AddIndex(
            model_name="otherpid",
            index=models.Index(
                fields=["pid_in_xml"], name="pid_provide_pid_in__f806db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="otherpid",
            index=models.Index(
                fields=["pid_type"], name="pid_provide_pid_typ_2267e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="otherpid",
            index=models.Index(
                fields=["version"], name="pid_provide_version_027f86_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matchedpid",
            index=models.Index(
                fields=["pid_conflict"], name="pid_provide_pid_con_015bc3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matchedpid",
            index=models.Index(
                fields=["pid_provider_xml"], name="pid_provide_pid_pro_ac8b6f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="matchedpid",
            unique_together={("pid_conflict", "pid_provider_xml")},
        ),
    ]
