# Generated by Django 4.1.10 on 2023-08-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pid_provider", "0003_remove_xmlrelateditem_creator_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="pidrequest",
            index=models.Index(fields=["origin"], name="pid_provide_origin_5fc5d3_idx"),
        ),
        migrations.AddIndex(
            model_name="pidrequest",
            index=models.Index(
                fields=["result_type"], name="pid_provide_result__f42960_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pidrequest",
            index=models.Index(
                fields=["result_msg"], name="pid_provide_result__e08f74_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pidrequest",
            index=models.Index(
                fields=["origin_date"], name="pid_provide_origin__5ea28e_idx"
            ),
        ),
    ]
