# Generated by Django 5.0.8 on 2025-05-28 12:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pid_provider", "0004_alter_collectionpidrequest_created_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="otherpid",
            name="pid_provide_pid_in__f806db_idx",
        ),
        migrations.RemoveIndex(
            model_name="otherpid",
            name="pid_provide_pid_typ_2267e6_idx",
        ),
        migrations.RemoveIndex(
            model_name="otherpid",
            name="pid_provide_version_027f86_idx",
        ),
        migrations.RemoveIndex(
            model_name="pidproviderxml",
            name="pid_provide_pub_yea_2cf929_idx",
        ),
        migrations.RemoveIndex(
            model_name="pidproviderxml",
            name="pid_provide_volume_6abc53_idx",
        ),
        migrations.RemoveIndex(
            model_name="pidproviderxml",
            name="pid_provide_number_a56cd7_idx",
        ),
        migrations.RemoveIndex(
            model_name="pidproviderxml",
            name="pid_provide_suppl_b4294e_idx",
        ),
        migrations.RemoveIndex(
            model_name="pidproviderxml",
            name="pid_provide_elocati_088a9b_idx",
        ),
        migrations.RemoveIndex(
            model_name="pidproviderxml",
            name="pid_provide_fpage_aa4aa3_idx",
        ),
        migrations.RemoveIndex(
            model_name="pidproviderxml",
            name="pid_provide_fpage_s_cd49cb_idx",
        ),
        migrations.RemoveIndex(
            model_name="pidproviderxml",
            name="pid_provide_lpage_7a7852_idx",
        ),
        migrations.RemoveIndex(
            model_name="pidproviderxml",
            name="pid_provide_article_e25491_idx",
        ),
        migrations.RemoveIndex(
            model_name="pidproviderxml",
            name="pid_provide_z_artic_a6a417_idx",
        ),
        migrations.RemoveIndex(
            model_name="pidproviderxml",
            name="pid_provide_z_surna_2f3ee3_idx",
        ),
        migrations.RemoveIndex(
            model_name="pidproviderxml",
            name="pid_provide_z_colla_c14f41_idx",
        ),
        migrations.RemoveIndex(
            model_name="pidproviderxml",
            name="pid_provide_z_links_ed20b4_idx",
        ),
        migrations.RemoveIndex(
            model_name="pidproviderxml",
            name="pid_provide_z_parti_6ab872_idx",
        ),
        migrations.RemoveIndex(
            model_name="pidproviderxml",
            name="pid_provide_z_journ_1dc283_idx",
        ),
        migrations.RemoveIndex(
            model_name="pidproviderxml",
            name="pid_provide_other_p_409926_idx",
        ),
        migrations.RemoveIndex(
            model_name="pidrequest",
            name="pid_provide_v3_afbea7_idx",
        ),
        migrations.RemoveField(
            model_name="pidproviderxml",
            name="main_toc_section",
        ),
        migrations.RemoveField(
            model_name="pidproviderxml",
            name="z_article_titles_texts",
        ),
        migrations.RemoveField(
            model_name="pidproviderxml",
            name="z_journal_title",
        ),
        migrations.RemoveField(
            model_name="pidrequest",
            name="v3",
        ),
        migrations.RemoveField(
            model_name="pidrequest",
            name="xml_version",
        ),
        migrations.AlterField(
            model_name="pidproviderconfig",
            name="api_password",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Senha da API"
            ),
        ),
        migrations.AlterField(
            model_name="pidproviderconfig",
            name="api_username",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Nome de usuário da API",
            ),
        ),
        migrations.AlterField(
            model_name="pidproviderconfig",
            name="pid_provider_api_get_token",
            field=models.CharField(
                blank=True,
                max_length=2048,
                null=True,
                verbose_name="Obter URI do Token",
            ),
        ),
        migrations.AlterField(
            model_name="pidproviderconfig",
            name="pid_provider_api_post_xml",
            field=models.CharField(
                blank=True,
                max_length=2048,
                null=True,
                verbose_name="URI de Postagem XML",
            ),
        ),
        migrations.AlterField(
            model_name="pidproviderxml",
            name="main_doi",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="DOI"
            ),
        ),
        migrations.AlterField(
            model_name="pidproviderxml",
            name="pkg_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Nome do Pacote"
            ),
        ),
        migrations.AlterField(
            model_name="pidproviderxml",
            name="registered_in_core",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="pidrequest",
            name="result_type",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Tipo de Resultado"
            ),
        ),
        migrations.AddIndex(
            model_name="otherpid",
            index=models.Index(
                fields=["pid_provider_xml", "pid_in_xml", "version"],
                name="pid_provide_pid_pro_d24c63_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pidproviderxml",
            index=models.Index(fields=["v2"], name="pid_provide_v2_d0f65a_idx"),
        ),
        migrations.AddIndex(
            model_name="pidproviderxml",
            index=models.Index(
                fields=["issn_electronic", "pub_year", "article_pub_year"],
                name="pid_provide_issn_el_0847cd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pidproviderxml",
            index=models.Index(
                fields=["issn_print", "pub_year", "article_pub_year"],
                name="pid_provide_issn_pr_e919b3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pidproviderxml",
            index=models.Index(
                fields=["pub_year", "volume", "number", "suppl"],
                name="pid_provide_pub_yea_07b83d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pidproviderxml",
            index=models.Index(
                fields=["issn_electronic", "main_doi"],
                name="pid_provide_issn_el_6a6308_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pidproviderxml",
            index=models.Index(
                fields=["issn_print", "main_doi"], name="pid_provide_issn_pr_228186_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pidproviderxml",
            index=models.Index(
                fields=["issn_electronic", "elocation_id"],
                name="pid_provide_issn_el_0a43ae_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pidproviderxml",
            index=models.Index(
                fields=["z_surnames", "pub_year"], name="pid_provide_z_surna_9a54a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pidproviderxml",
            index=models.Index(
                fields=["z_collab", "pub_year"], name="pid_provide_z_colla_e9f3bc_idx"
            ),
        ),
    ]
