# Generated by Django 4.2.6 on 2023-11-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pid_provider", "0004_collectionpidrequest"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="pidproviderxml",
            name="pid_provide_journal_bef662_idx",
        ),
        migrations.RemoveIndex(
            model_name="pidproviderxml",
            name="pid_provide_issue_i_e27cba_idx",
        ),
        migrations.RemoveField(
            model_name="pidproviderxml",
            name="issue",
        ),
        migrations.RemoveField(
            model_name="pidproviderxml",
            name="journal",
        ),
        migrations.AddField(
            model_name="pidproviderxml",
            name="issn_electronic",
            field=models.CharField(
                blank=True, max_length=9, null=True, verbose_name="issn_epub"
            ),
        ),
        migrations.AddField(
            model_name="pidproviderxml",
            name="issn_print",
            field=models.CharField(
                blank=True, max_length=9, null=True, verbose_name="issn_ppub"
            ),
        ),
        migrations.AddField(
            model_name="pidproviderxml",
            name="number",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="number"
            ),
        ),
        migrations.AddField(
            model_name="pidproviderxml",
            name="pub_year",
            field=models.CharField(
                blank=True, max_length=4, null=True, verbose_name="pub_year"
            ),
        ),
        migrations.AddField(
            model_name="pidproviderxml",
            name="suppl",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="suppl"
            ),
        ),
        migrations.AddField(
            model_name="pidproviderxml",
            name="volume",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="volume"
            ),
        ),
        migrations.AddField(
            model_name="pidproviderxml",
            name="website_publication_date",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Website publication date",
            ),
        ),
        migrations.AddIndex(
            model_name="pidproviderxml",
            index=models.Index(
                fields=["issn_electronic"], name="pid_provide_issn_el_2f7625_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pidproviderxml",
            index=models.Index(
                fields=["issn_print"], name="pid_provide_issn_pr_988775_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pidproviderxml",
            index=models.Index(
                fields=["pub_year"], name="pid_provide_pub_yea_2cf929_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pidproviderxml",
            index=models.Index(fields=["volume"], name="pid_provide_volume_6abc53_idx"),
        ),
        migrations.AddIndex(
            model_name="pidproviderxml",
            index=models.Index(fields=["number"], name="pid_provide_number_a56cd7_idx"),
        ),
        migrations.AddIndex(
            model_name="pidproviderxml",
            index=models.Index(fields=["suppl"], name="pid_provide_suppl_b4294e_idx"),
        ),
    ]
