# Generated by Django 4.1.8 on 2023-07-14 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("xmlsps", "0002_remove_xmlsps_xml_xmlversion_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pid_provider", "0004_migration"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Migration",
            new_name="KernelXMLMigration",
        ),
        migrations.AlterField(
            model_name="kernelxmlmigration",
            name="xml_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="xmlsps.xmlversion",
            ),
        ),
        migrations.AlterField(
            model_name="pidchange",
            name="version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="xmlsps.xmlversion",
            ),
        ),
        migrations.AlterField(
            model_name="pidproviderxml",
            name="current_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="xmlsps.xmlversion",
            ),
        ),
        migrations.DeleteModel(
            name="XMLVersion",
        ),
    ]
