# Generated by Django 4.1.8 on 2023-07-27 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("xmlsps", "0003_xmlsps_xml_version"),
        ("pid_provider", "0005_rename_migration_kernelxmlmigration_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PidRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        blank=True,
                        max_length=124,
                        null=True,
                        verbose_name="Request origin",
                    ),
                ),
                (
                    "result_type",
                    models.TextField(blank=True, null=True, verbose_name="Result type"),
                ),
                (
                    "result_msg",
                    models.TextField(
                        blank=True, null=True, verbose_name="Result message"
                    ),
                ),
                (
                    "detail",
                    models.JSONField(blank=True, null=True, verbose_name="Detail"),
                ),
                (
                    "origin_date",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Origin date"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
                (
                    "xml_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="xmlsps.xmlversion",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="pidproviderbadrequest",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="pidproviderbadrequest",
            name="updated_by",
        ),
        migrations.DeleteModel(
            name="KernelXMLMigration",
        ),
        migrations.DeleteModel(
            name="PidProviderBadRequest",
        ),
    ]
