# Generated by Django 5.0.8 on 2025-05-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pid_provider",
            "0005_remove_otherpid_pid_provide_pid_in__f806db_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="pidproviderxml",
            name="proc_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TODO", "A fazer"),
                    ("DONE", "Feito"),
                    ("WAIT", "waiting"),
                    ("IGNORE", "ignore"),
                    ("UNDEF", "undefined"),
                ],
                default="TODO",
                max_length=6,
                null=True,
                verbose_name="processing status",
            ),
        ),
    ]
