# Generated by Django 4.1.8 on 2023-07-25 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("xmlsps", "0003_xmlsps_xml_version"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pid_provider", "0005_rename_migration_kernelxmlmigration_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PidRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "pid_v2",
                    models.CharField(
                        blank=True, max_length=23, null=True, verbose_name="PID v2"
                    ),
                ),
                (
                    "pid_v3",
                    models.CharField(
                        blank=True, max_length=23, null=True, verbose_name="PID v3"
                    ),
                ),
                (
                    "pkg_name",
                    models.CharField(
                        blank=True,
                        max_length=23,
                        null=True,
                        verbose_name="Package name",
                    ),
                ),
                (
                    "collection_acron",
                    models.CharField(
                        blank=True,
                        max_length=23,
                        null=True,
                        verbose_name="Collection Acron",
                    ),
                ),
                (
                    "journal_acron",
                    models.CharField(
                        blank=True,
                        max_length=23,
                        null=True,
                        verbose_name="Journal Acron",
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        blank=True, max_length=4, null=True, verbose_name="Year"
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        blank=True,
                        max_length=124,
                        null=True,
                        verbose_name="Request origin",
                    ),
                ),
                (
                    "error_type",
                    models.TextField(blank=True, null=True, verbose_name="Error type"),
                ),
                (
                    "error_msg",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mensagem de erro"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
                (
                    "xml_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="xmlsps.xmlversion",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
