# Generated by Django 5.0.8 on 2025-07-04 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pid_provider", "0006_pidproviderxml_proc_status"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PidProviderEndpoint",
        ),
    ]
