# Generated by Django 4.1.8 on 2023-07-28 15:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "pid_provider",
            "0006_pidrequest_remove_pidproviderbadrequest_creator_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pidproviderxml",
            name="current_xml",
        ),
    ]
