# Generated by Django 4.1.8 on 2023-07-25 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pid_provider", "0006_pidrequest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pidrequest",
            name="error_msg",
        ),
        migrations.RemoveField(
            model_name="pidrequest",
            name="error_type",
        ),
        migrations.AddField(
            model_name="pidrequest",
            name="result_msg",
            field=models.TextField(
                blank=True, null=True, verbose_name="Result message"
            ),
        ),
        migrations.AddField(
            model_name="pidrequest",
            name="result_type",
            field=models.TextField(blank=True, null=True, verbose_name="Result type"),
        ),
    ]
