# Generated by Django 5.2.3 on 2025-08-08 23:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pid_provider", "0007_delete_pidproviderendpoint"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="xmlversion",
            options={"ordering": ["-created"]},
        ),
        migrations.RemoveIndex(
            model_name="pidproviderxml",
            name="pid_provide_issn_el_2f7625_idx",
        ),
        migrations.RemoveIndex(
            model_name="pidproviderxml",
            name="pid_provide_issn_pr_988775_idx",
        ),
        migrations.RemoveIndex(
            model_name="pidproviderxml",
            name="pid_provide_main_do_7fb3c9_idx",
        ),
        migrations.RemoveIndex(
            model_name="pidproviderxml",
            name="pid_provide_issn_el_0847cd_idx",
        ),
        migrations.RemoveIndex(
            model_name="pidproviderxml",
            name="pid_provide_issn_pr_e919b3_idx",
        ),
        migrations.RemoveIndex(
            model_name="pidproviderxml",
            name="pid_provide_pub_yea_07b83d_idx",
        ),
        migrations.RemoveIndex(
            model_name="pidproviderxml",
            name="pid_provide_issn_el_6a6308_idx",
        ),
        migrations.RemoveIndex(
            model_name="pidproviderxml",
            name="pid_provide_issn_pr_228186_idx",
        ),
        migrations.RemoveIndex(
            model_name="pidproviderxml",
            name="pid_provide_issn_el_0a43ae_idx",
        ),
        migrations.RemoveIndex(
            model_name="pidproviderxml",
            name="pid_provide_z_surna_9a54a0_idx",
        ),
        migrations.RemoveIndex(
            model_name="pidproviderxml",
            name="pid_provide_z_colla_e9f3bc_idx",
        ),
        migrations.RemoveIndex(
            model_name="xmlversion",
            name="pid_provide_finger__df9abb_idx",
        ),
        migrations.RemoveIndex(
            model_name="xmlversion",
            name="pid_provide_pid_pro_8d8a70_idx",
        ),
        migrations.AddIndex(
            model_name="pidproviderxml",
            index=models.Index(
                condition=models.Q(("aop_pid__isnull", False)),
                fields=["aop_pid"],
                name="ppx_aop_pid",
            ),
        ),
        migrations.AddIndex(
            model_name="pidproviderxml",
            index=models.Index(
                condition=models.Q(("main_doi__isnull", False)),
                fields=["main_doi"],
                name="ppx_main_doi",
            ),
        ),
        migrations.AddIndex(
            model_name="pidproviderxml",
            index=models.Index(
                condition=models.Q(("issn_electronic__isnull", False)),
                fields=["issn_electronic"],
                name="ppx_issn_electronic",
            ),
        ),
        migrations.AddIndex(
            model_name="pidproviderxml",
            index=models.Index(
                condition=models.Q(("issn_print__isnull", False)),
                fields=["issn_print"],
                name="ppx_issn_print",
            ),
        ),
        migrations.AddIndex(
            model_name="pidproviderxml",
            index=models.Index(
                condition=models.Q(("z_surnames__isnull", False)),
                fields=["z_surnames"],
                name="ppx_z_surnames",
            ),
        ),
        migrations.AddIndex(
            model_name="pidproviderxml",
            index=models.Index(
                condition=models.Q(("z_collab__isnull", False)),
                fields=["z_collab"],
                name="ppx_z_collab",
            ),
        ),
        migrations.AddIndex(
            model_name="pidproviderxml",
            index=models.Index(
                fields=["-updated"], name="pid_provide_updated_3b790a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pidproviderxml",
            index=models.Index(
                fields=["-created"], name="pid_provide_created_f41483_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pidproviderxml",
            index=models.Index(
                fields=["proc_status"], name="pid_provide_proc_st_f95303_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pidproviderxml",
            index=models.Index(
                fields=["available_since", "-updated"],
                name="pid_provide_availab_1ce6f3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pidproviderxml",
            index=models.Index(
                condition=models.Q(
                    ("elocation_id__isnull", False), ("issn_electronic__isnull", False)
                ),
                fields=["issn_electronic", "elocation_id"],
                name="ppx_elocation_id",
            ),
        ),
        migrations.AddIndex(
            model_name="pidproviderxml",
            index=models.Index(
                condition=models.Q(("issn_electronic__isnull", False)),
                fields=["issn_electronic", "pub_year", "volume", "number", "suppl"],
                name="ppx_eissue",
            ),
        ),
        migrations.AddIndex(
            model_name="pidproviderxml",
            index=models.Index(
                condition=models.Q(("issn_print__isnull", False)),
                fields=["issn_print", "pub_year", "volume", "number", "suppl"],
                name="ppx_pissue",
            ),
        ),
        migrations.AddIndex(
            model_name="pidproviderxml",
            index=models.Index(
                condition=models.Q(("fpage__isnull", False)),
                fields=["fpage", "fpage_seq", "lpage"],
                name="ppx_fpage",
            ),
        ),
        migrations.AddIndex(
            model_name="pidproviderxml",
            index=models.Index(
                fields=["current_version"], name="pid_provide_current_8222ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="xmlversion",
            index=models.Index(
                fields=["pid_provider_xml", "finger_print"],
                name="pid_provide_pid_pro_91cb7b_idx",
            ),
        ),
    ]
