# Generated by Django 5.2.3 on 2025-09-01 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pid_provider", "0008_alter_xmlversion_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectionpidrequest",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creation date"),
        ),
        migrations.AlterField(
            model_name="collectionpidrequest",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AlterField(
            model_name="collectionpidrequest",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Last update date"),
        ),
        migrations.AlterField(
            model_name="collectionpidrequest",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updater",
            ),
        ),
        migrations.AlterField(
            model_name="fixpidv2",
            name="correct_pid_v2",
            field=models.CharField(
                blank=True, max_length=24, null=True, verbose_name="Correct v2"
            ),
        ),
        migrations.AlterField(
            model_name="fixpidv2",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creation date"),
        ),
        migrations.AlterField(
            model_name="fixpidv2",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AlterField(
            model_name="fixpidv2",
            name="incorrect_pid_v2",
            field=models.CharField(
                blank=True, max_length=24, null=True, verbose_name="Incorrect v2"
            ),
        ),
        migrations.AlterField(
            model_name="fixpidv2",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Last update date"),
        ),
        migrations.AlterField(
            model_name="fixpidv2",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updater",
            ),
        ),
        migrations.AlterField(
            model_name="otherpid",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creation date"),
        ),
        migrations.AlterField(
            model_name="otherpid",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AlterField(
            model_name="otherpid",
            name="pid_type",
            field=models.CharField(
                blank=True, max_length=7, null=True, verbose_name="PID type"
            ),
        ),
        migrations.AlterField(
            model_name="otherpid",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Last update date"),
        ),
        migrations.AlterField(
            model_name="otherpid",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updater",
            ),
        ),
        migrations.AlterField(
            model_name="pidproviderconfig",
            name="api_password",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="API Password"
            ),
        ),
        migrations.AlterField(
            model_name="pidproviderconfig",
            name="api_username",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="API Username"
            ),
        ),
        migrations.AlterField(
            model_name="pidproviderconfig",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creation date"),
        ),
        migrations.AlterField(
            model_name="pidproviderconfig",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AlterField(
            model_name="pidproviderconfig",
            name="pid_provider_api_get_token",
            field=models.CharField(
                blank=True, max_length=2048, null=True, verbose_name="Get Token URI"
            ),
        ),
        migrations.AlterField(
            model_name="pidproviderconfig",
            name="pid_provider_api_post_xml",
            field=models.CharField(
                blank=True, max_length=2048, null=True, verbose_name="XML Post URI"
            ),
        ),
        migrations.AlterField(
            model_name="pidproviderconfig",
            name="timeout",
            field=models.IntegerField(blank=True, null=True, verbose_name="Timeout"),
        ),
        migrations.AlterField(
            model_name="pidproviderconfig",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Last update date"),
        ),
        migrations.AlterField(
            model_name="pidproviderconfig",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updater",
            ),
        ),
        migrations.AlterField(
            model_name="pidproviderxml",
            name="aop_pid",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="AOP PID"
            ),
        ),
        migrations.AlterField(
            model_name="pidproviderxml",
            name="article_pub_year",
            field=models.CharField(
                blank=True,
                max_length=4,
                null=True,
                verbose_name="Document Publication Year",
            ),
        ),
        migrations.AlterField(
            model_name="pidproviderxml",
            name="available_since",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Available since"
            ),
        ),
        migrations.AlterField(
            model_name="pidproviderxml",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creation date"),
        ),
        migrations.AlterField(
            model_name="pidproviderxml",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AlterField(
            model_name="pidproviderxml",
            name="elocation_id",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="elocation id"
            ),
        ),
        migrations.AlterField(
            model_name="pidproviderxml",
            name="fpage",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="fpage"
            ),
        ),
        migrations.AlterField(
            model_name="pidproviderxml",
            name="fpage_seq",
            field=models.CharField(
                blank=True, max_length=8, null=True, verbose_name="fpage_seq"
            ),
        ),
        migrations.AlterField(
            model_name="pidproviderxml",
            name="lpage",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="lpage"
            ),
        ),
        migrations.AlterField(
            model_name="pidproviderxml",
            name="number",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="number"
            ),
        ),
        migrations.AlterField(
            model_name="pidproviderxml",
            name="origin_date",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Origin date"
            ),
        ),
        migrations.AlterField(
            model_name="pidproviderxml",
            name="pkg_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Package name"
            ),
        ),
        migrations.AlterField(
            model_name="pidproviderxml",
            name="proc_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TODO", "To do"),
                    ("DONE", "Done"),
                    ("WAIT", "waiting"),
                    ("IGNORE", "ignore"),
                    ("UNDEF", "undefined"),
                ],
                default="TODO",
                max_length=6,
                null=True,
                verbose_name="processing status",
            ),
        ),
        migrations.AlterField(
            model_name="pidproviderxml",
            name="pub_year",
            field=models.CharField(
                blank=True, max_length=4, null=True, verbose_name="pub_year"
            ),
        ),
        migrations.AlterField(
            model_name="pidproviderxml",
            name="suppl",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="suppl"
            ),
        ),
        migrations.AlterField(
            model_name="pidproviderxml",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Last update date"),
        ),
        migrations.AlterField(
            model_name="pidproviderxml",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updater",
            ),
        ),
        migrations.AlterField(
            model_name="pidproviderxml",
            name="z_collab",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="collab"
            ),
        ),
        migrations.AlterField(
            model_name="pidproviderxml",
            name="z_partial_body",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="partial_body"
            ),
        ),
        migrations.AlterField(
            model_name="pidproviderxml",
            name="z_surnames",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="surnames"
            ),
        ),
        migrations.AlterField(
            model_name="pidrequest",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creation date"),
        ),
        migrations.AlterField(
            model_name="pidrequest",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AlterField(
            model_name="pidrequest",
            name="detail",
            field=models.JSONField(blank=True, null=True, verbose_name="Detail"),
        ),
        migrations.AlterField(
            model_name="pidrequest",
            name="origin",
            field=models.CharField(
                blank=True, max_length=124, null=True, verbose_name="Request origin"
            ),
        ),
        migrations.AlterField(
            model_name="pidrequest",
            name="origin_date",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Origin date"
            ),
        ),
        migrations.AlterField(
            model_name="pidrequest",
            name="result_msg",
            field=models.TextField(
                blank=True, null=True, verbose_name="Result message"
            ),
        ),
        migrations.AlterField(
            model_name="pidrequest",
            name="result_type",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Result type"
            ),
        ),
        migrations.AlterField(
            model_name="pidrequest",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Last update date"),
        ),
        migrations.AlterField(
            model_name="pidrequest",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updater",
            ),
        ),
        migrations.AlterField(
            model_name="xmlversion",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creation date"),
        ),
        migrations.AlterField(
            model_name="xmlversion",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AlterField(
            model_name="xmlversion",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Last update date"),
        ),
        migrations.AlterField(
            model_name="xmlversion",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updater",
            ),
        ),
    ]
