# Generated by Django 5.2.3 on 2025-09-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pid_provider", "0009_alter_collectionpidrequest_created_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pidrequest",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="pidrequest",
            name="updated_by",
        ),
        migrations.AlterField(
            model_name="pidproviderxml",
            name="proc_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TODO", "To do"),
                    ("DONE", "Done"),
                    ("WAIT", "waiting"),
                    ("IGNORE", "ignore"),
                    ("UNDEF", "undefined"),
                    ("NVALID", "invalid"),
                ],
                default="TODO",
                max_length=7,
                null=True,
                verbose_name="processing status",
            ),
        ),
        migrations.DeleteModel(
            name="CollectionPidRequest",
        ),
        migrations.DeleteModel(
            name="PidRequest",
        ),
    ]
