# Generated by Django 5.2.3 on 2025-09-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pid_provider", "0010_remove_pidrequest_creator_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pidproviderxml",
            name="issn_electronic",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Electronic ISSN"
            ),
        ),
        migrations.AlterField(
            model_name="pidproviderxml",
            name="issn_print",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Print ISSN"
            ),
        ),
        migrations.AlterField(
            model_name="pidproviderxml",
            name="pub_year",
            field=models.CharField(
                blank=True, max_length=4, null=True, verbose_name="publication year"
            ),
        ),
    ]
