# Generated by Django 5.2.3 on 2025-09-24 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "collection",
            "0006_alter_collection_options_alter_collection_acron2_and_more",
        ),
        ("pid_provider", "0011_alter_pidproviderxml_issn_electronic_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pidproviderxml",
            name="collections",
            field=models.ManyToManyField(blank=True, to="collection.collection"),
        ),
    ]
