# Generated by Django 5.2.3 on 2025-10-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pid_provider", "0012_pidproviderxml_collections"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pidproviderxml",
            name="proc_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TODO", "To do"),
                    ("DONE", "Done"),
                    ("WAIT", "waiting"),
                    ("IGNORE", "ignore"),
                    ("UNDEF", "undefined"),
                    ("NVALID", "invalid"),
                    ("DUP", "duplicated"),
                    ("DEDUP", "deduplicated"),
                ],
                default="TODO",
                max_length=7,
                null=True,
                verbose_name="processing status",
            ),
        ),
    ]
