# Generated by Django 5.2.3 on 2025-10-28 21:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pid_provider", "0013_alter_pidproviderxml_proc_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="xmlversion",
            name="pid_provide_pid_pro_91cb7b_idx",
        ),
        migrations.AddIndex(
            model_name="xmlversion",
            index=models.Index(
                fields=["pid_provider_xml"], name="pid_provide_pid_pro_8d8a70_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="xmlversion",
            index=models.Index(
                fields=["finger_print"], name="pid_provide_finger__df9abb_idx"
            ),
        ),
    ]
