# Generated by Django 5.2.7 on 2026-03-01 15:15

import django.db.models.deletion
import pid_provider.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pid_provider",
            "0014_remove_xmlversion_pid_provide_pid_pro_91cb7b_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="xmlversion",
            name="file",
            field=models.FileField(
                blank=True,
                max_length=300,
                null=True,
                upload_to=pid_provider.models.xml_directory_path,
            ),
        ),
        migrations.CreateModel(
            name="XMLURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                ("url", models.URLField(max_length=500, verbose_name="URL")),
                (
                    "status",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Status"
                    ),
                ),
                (
                    "pid",
                    models.CharField(
                        blank=True, max_length=23, null=True, verbose_name="Article PID"
                    ),
                ),
                (
                    "zipfile",
                    models.FileField(
                        blank=True,
                        max_length=300,
                        null=True,
                        upload_to=pid_provider.models.xml_url_zipfile_path,
                        verbose_name="ZIP File",
                    ),
                ),
                (
                    "exceptions",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Exceptions"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
            options={
                "verbose_name": "XML URL",
                "verbose_name_plural": "XML URLs",
                "ordering": ["-updated", "-created"],
                "indexes": [
                    models.Index(fields=["url"], name="pid_provide_url_d6fff2_idx"),
                    models.Index(
                        fields=["status"], name="pid_provide_status_39bead_idx"
                    ),
                    models.Index(fields=["pid"], name="pid_provide_pid_588ddc_idx"),
                ],
            },
        ),
    ]
