# Generated by Django 5.2.7 on 2026-07-21 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pid_provider", "0016_alter_pidproviderxml_proc_status_xmlevent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PidProviderXMLRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "pkg_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Package name",
                    ),
                ),
                (
                    "event_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("created", "created"),
                            ("updated", "updated"),
                            ("skipped", "skipped"),
                            ("forbidden", "forbidden"),
                            ("conflict", "conflict"),
                            ("unmatched", "unmatched"),
                            ("bad_request", "bad_request"),
                            ("error", "error"),
                        ],
                        max_length=15,
                        null=True,
                        verbose_name="Event status",
                    ),
                ),
                (
                    "detail",
                    models.JSONField(blank=True, null=True, verbose_name="Detail"),
                ),
            ],
            options={
                "verbose_name": "PidProviderXML Registration",
                "verbose_name_plural": "PidProviderXML Registrations",
                "ordering": ["-created"],
            },
        ),
        migrations.AddField(
            model_name="pidproviderxml",
            name="readable_data",
            field=models.JSONField(blank=True, null=True, verbose_name="Readable data"),
        ),
        migrations.AddField(
            model_name="xmlurl",
            name="detail",
            field=models.JSONField(blank=True, null=True, verbose_name="Detail"),
        ),
        migrations.AddField(
            model_name="xmlurl",
            name="is_public",
            field=models.BooleanField(
                blank=True, default=None, null=True, verbose_name="Is Public"
            ),
        ),
        migrations.AlterField(
            model_name="xmlurl",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("success", "Success"),
                    ("xml_fetch_failed", "XML fetch failed"),
                    ("pid_provider_xml_failed", "PID provider XML failed"),
                ],
                max_length=50,
                null=True,
                verbose_name="Status",
            ),
        ),
        migrations.AddIndex(
            model_name="xmlurl",
            index=models.Index(fields=["is_public"], name="pid_provide_is_public_idx"),
        ),
        migrations.AddField(
            model_name="pidproviderxmlregistration",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AddField(
            model_name="pidproviderxmlregistration",
            name="pid_provider_xml",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="registration_events",
                to="pid_provider.pidproviderxml",
            ),
        ),
        migrations.AddField(
            model_name="pidproviderxmlregistration",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updater",
            ),
        ),
        migrations.AddIndex(
            model_name="pidproviderxmlregistration",
            index=models.Index(
                fields=["pkg_name"], name="pid_provide_pkg_nam_2db0b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pidproviderxmlregistration",
            index=models.Index(
                fields=["event_status"], name="pid_provide_event_s_3c9ae7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pidproviderxmlregistration",
            index=models.Index(
                fields=["-created"], name="pid_provide_created_94fb08_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pidproviderxmlregistration",
            index=models.Index(
                fields=["pid_provider_xml"], name="pid_provide_pid_pro_c9fb0e_idx"
            ),
        ),
    ]
