# Generated by Django 5.2.7 on 2026-07-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pid_provider", "0017_pidproviderxmlregistration_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="xmlurl",
            name="exceptions",
        ),
        migrations.AlterField(
            model_name="xmlurl",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("success", "Success"),
                    ("unexpected_failure", "Unexpected failure"),
                    ("xml_fetch_failed", "XML fetch failed"),
                    ("pid_provider_xml_failed", "PID provider XML failed"),
                ],
                max_length=50,
                null=True,
                verbose_name="Status",
            ),
        ),
    ]
