# Generated by Django 5.2.7 on 2026-08-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pid_provider", "0017_pidproviderxmlregistration_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PidProviderSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "record_all_registration_events",
                    models.BooleanField(
                        default=False,
                        help_text="Quando ativo, grava auditoria em PidProviderXMLRegistration mesmo para fluxos limpos (created, updated, skipped).",
                        verbose_name="Gravar todos os eventos de auditoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configurações do PID Provider",
            },
        ),
    ]
