# Generated by Django 5.2.7 on 2026-09-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pid_provider", "0020_xmlevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pidproviderxmlregistration",
            name="event_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("created", "created"),
                    ("updated", "updated"),
                    ("skipped", "skipped"),
                    ("forbidden", "forbidden"),
                    ("conflict", "conflict"),
                    ("multiple", "multiple"),
                    ("unmatched", "unmatched"),
                    ("bad_request", "bad_request"),
                    ("error", "error"),
                ],
                max_length=15,
                null=True,
                verbose_name="Event status",
            ),
        ),
    ]
