# Generated by Django 4.1.10 on 2023-08-31 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vocabulary", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vocabulary",
            name="name",
            field=models.TextField(
                blank=True, null=True, verbose_name="Vocabulary name"
            ),
        ),
    ]
