# Generated by Django 4.1.7 on 2023-02-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vocabulary", "0002_alter_keyword_creator_alter_keyword_updated_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keyword",
            name="text",
            field=models.TextField(blank=True, null=True, verbose_name="Texto"),
        ),
        migrations.AlterField(
            model_name="vocabulary",
            name="name",
            field=models.TextField(
                default="", unique=True, verbose_name="Vocabulary name"
            ),
            preserve_default=False,
        ),
    ]
