# Generated by Django 4.1.8 on 2023-05-23 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_license_options_rename_license_license_url_and_more"),
        ("vocabulary", "0003_alter_keyword_text_alter_vocabulary_name"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="keyword",
            new_name="vocabulary__languag_479020_idx",
            old_name="vocabulary__languag_a11f3d_idx",
        ),
        migrations.AlterField(
            model_name="keyword",
            name="language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.language",
                verbose_name="Idioma",
            ),
        ),
    ]
