# Generated by Django 5.2.3 on 2025-09-01 17:24

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_language_options_alter_license_options_and_more"),
        ("vocabulary", "0004_alter_keyword_created_alter_keyword_creator_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="keyword",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creation date"),
        ),
        migrations.AlterField(
            model_name="keyword",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AlterField(
            model_name="keyword",
            name="html_text",
            field=wagtail.fields.RichTextField(
                blank=True, null=True, verbose_name="Rich Text"
            ),
        ),
        migrations.AlterField(
            model_name="keyword",
            name="language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.language",
                verbose_name="Language",
            ),
        ),
        migrations.AlterField(
            model_name="keyword",
            name="text",
            field=models.TextField(blank=True, null=True, verbose_name="Text"),
        ),
        migrations.AlterField(
            model_name="keyword",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Last update date"),
        ),
        migrations.AlterField(
            model_name="keyword",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updater",
            ),
        ),
        migrations.AlterField(
            model_name="keyword",
            name="vocabulary",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="vocabulary.vocabulary",
                verbose_name="Vocabulary",
            ),
        ),
        migrations.AlterField(
            model_name="vocabulary",
            name="acronym",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Vocabulary acronym"
            ),
        ),
        migrations.AlterField(
            model_name="vocabulary",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creation date"),
        ),
        migrations.AlterField(
            model_name="vocabulary",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AlterField(
            model_name="vocabulary",
            name="name",
            field=models.TextField(
                blank=True, null=True, verbose_name="Vocabulary name"
            ),
        ),
        migrations.AlterField(
            model_name="vocabulary",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Last update date"),
        ),
        migrations.AlterField(
            model_name="vocabulary",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updater",
            ),
        ),
    ]
