# Generated by Django 4.1.8 on 2023-05-23 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_license_options_rename_license_license_url_and_more"),
        ("doi", "0002_alter_doi_creator_alter_doi_updated_by_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="doi",
            name="doi_doi_lang_1f447b_idx",
        ),
        migrations.RemoveField(
            model_name="doi",
            name="lang",
        ),
        migrations.AddField(
            model_name="doi",
            name="language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.language",
                verbose_name="Language",
            ),
        ),
        migrations.AddIndex(
            model_name="doi",
            index=models.Index(fields=["language"], name="doi_doi_languag_804943_idx"),
        ),
    ]
