# Generated by Django 5.2.3 on 2025-08-05 00:09

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_aboutscieloorgpage_listpagejournalbypublisher"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutscieloorgpage",
            name="body",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="aboutscieloorgpage",
            name="external_link",
            field=models.URLField(blank=True, null=True, verbose_name="Link externo"),
        ),
    ]
