# Generated by Django 5.2.3 on 2025-08-05 01:44

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_aboutscieloorgpage_body_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aboutscieloorgpage",
            name="body",
        ),
        migrations.AddField(
            model_name="aboutscieloorgpage",
            name="body_br",
            field=wagtail.fields.RichTextField(blank=True, verbose_name="Body PT"),
        ),
        migrations.AddField(
            model_name="aboutscieloorgpage",
            name="body_en",
            field=wagtail.fields.RichTextField(blank=True, verbose_name="Body EN"),
        ),
        migrations.AddField(
            model_name="aboutscieloorgpage",
            name="body_es",
            field=wagtail.fields.RichTextField(blank=True, verbose_name="Body ES"),
        ),
        migrations.AddField(
            model_name="aboutscieloorgpage",
            name="title_br",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Título PT"
            ),
        ),
        migrations.AddField(
            model_name="aboutscieloorgpage",
            name="title_en",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Título EN"
            ),
        ),
        migrations.AddField(
            model_name="aboutscieloorgpage",
            name="title_es",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Título ES"
            ),
        ),
        migrations.AlterField(
            model_name="aboutscieloorgpage",
            name="list_page",
            field=wagtail.fields.StreamField(
                [("page", 0), ("multilang_text", 4), ("url", 5), ("document", 6)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.PageChooserBlock", (), {}),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Português", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Inglês", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Espanhol", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("br", 1), ("en", 2), ("es", 3)]],
                        {},
                    ),
                    5: ("wagtail.blocks.URLBlock", (), {}),
                    6: ("wagtail.documents.blocks.DocumentChooserBlock", (), {}),
                },
            ),
        ),
    ]
