# Generated by Django 5.2.3 on 2025-08-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_remove_aboutscieloorgpage_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutscieloorgpage",
            name="external_link",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Link externo"
            ),
        ),
    ]
