# Generated by Django 5.2.3 on 2025-08-11 00:18

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_aboutscieloorgpage_external_link"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutscieloorgpage",
            options={"verbose_name": "Página Sobre SciELO"},
        ),
        migrations.RemoveField(
            model_name="aboutscieloorgpage",
            name="body_br",
        ),
        migrations.RemoveField(
            model_name="aboutscieloorgpage",
            name="body_en",
        ),
        migrations.RemoveField(
            model_name="aboutscieloorgpage",
            name="body_es",
        ),
        migrations.RemoveField(
            model_name="aboutscieloorgpage",
            name="title_br",
        ),
        migrations.RemoveField(
            model_name="aboutscieloorgpage",
            name="title_en",
        ),
        migrations.RemoveField(
            model_name="aboutscieloorgpage",
            name="title_es",
        ),
        migrations.AddField(
            model_name="aboutscieloorgpage",
            name="body",
            field=wagtail.fields.RichTextField(blank=True, verbose_name="Body"),
        ),
    ]
