# Generated by Django 4.1.10 on 2023-09-12 19:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_homeorgpage_rename_homepage_homebrpage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HomeBRPage",
        ),
    ]
