# Generated by Django 4.1.10 on 2023-09-14 19:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
        ("home", "0006_homeorgpage_rename_homepage_homebrpage"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HomeORGPage",
            new_name="ListJournal",
        ),
    ]
