# Generated by Django 4.1.10 on 2023-10-12 01:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_homeorgpage_rename_homepage_homebrpage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HomeORGPage",
        ),
    ]
