# Generated by Django 5.2.3 on 2025-08-17 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_alter_aboutscieloorgpage_options_and_more"),
        ("wagtaildocs", "0014_alter_document_file_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutscieloorgpage",
            name="attached_document",
            field=models.ForeignKey(
                blank=True,
                help_text="Documento principal desta página",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtaildocs.document",
            ),
        ),
    ]
