# Generated by Django 5.2.3 on 2025-08-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_aboutscieloorgpage_attached_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutscieloorgpage",
            name="external_link",
            field=models.URLField(
                blank=True, max_length=2000, null=True, verbose_name="Link externo"
            ),
        ),
    ]
