# Generated by Django 5.2.3 on 2025-08-29 12:29

import wagtail.fields
import wagtailtables.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_alter_aboutscieloorgpage_external_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aboutscieloorgpage",
            name="attached_document",
        ),
        migrations.RemoveField(
            model_name="aboutscieloorgpage",
            name="body",
        ),
        migrations.RemoveField(
            model_name="aboutscieloorgpage",
            name="external_link",
        ),
        migrations.AlterField(
            model_name="aboutscieloorgpage",
            name="list_page",
            field=wagtail.fields.StreamField(
                [
                    ("text", 0),
                    ("url", 1),
                    ("table", 7),
                    ("document", 8),
                    ("page", 9),
                    ("faq", 12),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {}),
                    1: ("wagtail.blocks.URLBlock", (), {}),
                    2: ("wagtail.blocks.TextBlock", (), {"default": "[]"}),
                    3: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    4: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    5: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": wagtailtables.blocks.get_choices},
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("table_data", 2),
                                ("caption", 3),
                                ("header_row", 4),
                                ("header_col", 4),
                                ("table_type", 5),
                            ]
                        ],
                        {},
                    ),
                    7: ("wagtail.blocks.StreamBlock", [[("table_block", 6)]], {}),
                    8: ("wagtail.documents.blocks.DocumentChooserBlock", (), {}),
                    9: ("wagtail.blocks.PageChooserBlock", (), {}),
                    10: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    11: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 10), ("body", 11)]],
                        {},
                    ),
                },
            ),
        ),
    ]
