# Generated by Django 5.2.3 on 2025-09-01 17:45

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_alter_aboutscieloorgpage_external_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutscieloorgpage",
            name="list_page",
            field=wagtail.fields.StreamField(
                [("faq_item", 2)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 0), ("body", 1)]],
                        {},
                    ),
                },
            ),
        ),
    ]
