# Generated by Django 5.2.3 on 2025-09-09 17:53

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_alter_aboutscieloorgpage_list_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutscieloorgpage",
            name="updated",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="aboutscieloorgpage",
            name="list_page",
            field=wagtail.fields.StreamField(
                [("faq_item", 3)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                    2: ("wagtail.blocks.DateBlock", (), {"required": False}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 0), ("body", 1), ("updated", 2)]],
                        {},
                    ),
                },
            ),
        ),
    ]
