# Generated by Django 5.2.3 on 2025-11-13 14:55

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_listpagejournalbycategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutscieloorgpage",
            name="list_page",
            field=wagtail.fields.StreamField(
                [("faq_item", 3), ("bibliographic_reference", 6)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                    2: ("wagtail.blocks.DateBlock", (), {"required": False}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 0), ("body", 1), ("updated", 2)]],
                        {},
                    ),
                    4: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Digite a referência bibliográfica completa",
                            "label": "Referência Bibliográfica",
                            "required": True,
                        },
                    ),
                    5: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {
                            "help_text": "Selecione um ícone para exibir ao lado da referência",
                            "label": "Ícone",
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("reference", 4), ("icon", 5)]],
                        {},
                    ),
                },
            ),
        ),
    ]
