# Generated by Django 5.2.7 on 2026-03-12 14:11

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_homepagesponsor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formpage",
            name="thank_you_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Adicione a mensagem que será exibida após o envio do formulário.",
            ),
        ),
    ]
