# Generated by Django 5.2.7 on 2026-05-22 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0015_alter_formpage_thank_you_text"),
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.CreateModel(
            name="FreePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "embed",
                    models.TextField(
                        blank=True,
                        help_text="Embed content for the page, such as an iframe or other embed code.",
                        null=True,
                        verbose_name="Embed",
                    ),
                ),
                (
                    "use_only_embed",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, the page will only display the embed content without the body text.",
                        verbose_name="Set only embed",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
