# Generated by Django 4.1.7 on 2023-02-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("processing_errors", "0002_alter_processingerror_creator_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="processingerror",
            name="type",
        ),
        migrations.AddField(
            model_name="processingerror",
            name="type_field",
            field=models.TextField(blank=True, null=True, verbose_name="Error type"),
        ),
        migrations.AlterField(
            model_name="processingerror",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Error description"
            ),
        ),
        migrations.AlterField(
            model_name="processingerror",
            name="item",
            field=models.TextField(blank=True, null=True, verbose_name="Error item"),
        ),
        migrations.AlterField(
            model_name="processingerror",
            name="step",
            field=models.TextField(
                blank=True, null=True, verbose_name="Error occurrence step"
            ),
        ),
    ]
