# Generated by Django 4.2.7 on 2023-12-21 20:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UnexpectedEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "exception_type",
                    models.TextField(
                        blank=True, null=True, verbose_name="Exception Type"
                    ),
                ),
                (
                    "exception_msg",
                    models.TextField(
                        blank=True, null=True, verbose_name="Exception Msg"
                    ),
                ),
                ("traceback", models.JSONField(blank=True, null=True)),
                ("detail", models.JSONField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["exception_type"], name="tracker_une_excepti_47ede4_idx"
                    )
                ],
            },
        ),
    ]
