# Generated by Django 4.2.7 on 2024-02-07 18:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hello",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("status", models.BooleanField(blank=True, default=None, null=True)),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "exception_type",
                    models.TextField(
                        blank=True, null=True, verbose_name="Exception Type"
                    ),
                ),
                (
                    "exception_msg",
                    models.TextField(
                        blank=True, null=True, verbose_name="Exception Msg"
                    ),
                ),
                ("traceback", models.JSONField(blank=True, null=True)),
                ("detail", models.JSONField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status"], name="tracker_hel_status_cfcbfa_idx"
                    ),
                    models.Index(
                        fields=["exception_type"], name="tracker_hel_excepti_a64469_idx"
                    ),
                ],
            },
        ),
    ]
