# Generated by Django 4.2.7 on 2024-03-19 19:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "tracker",
            "0003_alter_unexpectedevent_options_unexpectedevent_action_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hello",
            options={"ordering": ["-created"]},
        ),
    ]
