# Generated by Django 5.2.7 on 2026-07-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_alter_hello_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="unexpectedevent",
            options={"ordering": ["-updated", "-created"]},
        ),
        migrations.AddField(
            model_name="unexpectedevent",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Last update date"),
        ),
        migrations.AlterField(
            model_name="unexpectedevent",
            name="exception_msg",
            field=models.CharField(
                blank=True, max_length=400, null=True, verbose_name="Exception Msg"
            ),
        ),
        migrations.AlterField(
            model_name="unexpectedevent",
            name="exception_type",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Exception Type"
            ),
        ),
    ]
